/*
 * EODHistoricalDataFundamentalLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.eodhistoricaldata.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.Map;

/**
 * This is a model class for BalanceSheet type.
 */
public class BalanceSheet {
    private String currencysymbol;
    private Map<String, GeneratedObject17> quarterly;

    /**
     * Default constructor.
     */
    public BalanceSheet() {
    }

    /**
     * Initialization constructor.
     * @param  currencysymbol  String value for currencysymbol.
     * @param  quarterly  Map of String, value for quarterly.
     */
    public BalanceSheet(
            String currencysymbol,
            Map<String, GeneratedObject17> quarterly) {
        this.currencysymbol = currencysymbol;
        this.quarterly = quarterly;
    }

    /**
     * Getter for Currencysymbol.
     * @return Returns the String
     */
    @JsonGetter("currencysymbol")
    public String getCurrencysymbol() {
        return currencysymbol;
    }

    /**
     * Setter for Currencysymbol.
     * @param currencysymbol Value for String
     */
    @JsonSetter("currencysymbol")
    public void setCurrencysymbol(String currencysymbol) {
        this.currencysymbol = currencysymbol;
    }

    /**
     * Getter for Quarterly.
     * @return Returns the Map of String, GeneratedObject17
     */
    @JsonGetter("quarterly")
    public Map<String, GeneratedObject17> getQuarterly() {
        return quarterly;
    }

    /**
     * Setter for Quarterly.
     * @param quarterly Value for Map of String, GeneratedObject17
     */
    @JsonSetter("quarterly")
    public void setQuarterly(Map<String, GeneratedObject17> quarterly) {
        this.quarterly = quarterly;
    }

    /**
     * Converts this BalanceSheet into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BalanceSheet [" + "currencysymbol=" + currencysymbol + ", quarterly=" + quarterly
                + "]";
    }

    /**
     * Builds a new {@link BalanceSheet.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link BalanceSheet.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(currencysymbol, quarterly);
        return builder;
    }

    /**
     * Class to build instances of {@link BalanceSheet}.
     */
    public static class Builder {
        private String currencysymbol;
        private Map<String, GeneratedObject17> quarterly;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  currencysymbol  String value for currencysymbol.
         * @param  quarterly  Map of String, value for quarterly.
         */
        public Builder(String currencysymbol, Map<String, GeneratedObject17> quarterly) {
            this.currencysymbol = currencysymbol;
            this.quarterly = quarterly;
        }

        /**
         * Setter for currencysymbol.
         * @param  currencysymbol  String value for currencysymbol.
         * @return Builder
         */
        public Builder currencysymbol(String currencysymbol) {
            this.currencysymbol = currencysymbol;
            return this;
        }

        /**
         * Setter for quarterly.
         * @param  quarterly  Map of String, value for quarterly.
         * @return Builder
         */
        public Builder quarterly(Map<String, GeneratedObject17> quarterly) {
            this.quarterly = quarterly;
            return this;
        }

        /**
         * Builds a new {@link BalanceSheet} object using the set fields.
         * @return {@link BalanceSheet}
         */
        public BalanceSheet build() {
            return new BalanceSheet(currencysymbol, quarterly);
        }
    }
}
