/*
 * EODHistoricalDataFundamentalLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.eodhistoricaldata.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.Map;

/**
 * This is a model class for ESGScores type.
 */
public class ESGScores {
    private String disclaimer;
    private String ratingDate;
    private double totalEsg;
    private double totalEsgPercentile;
    private double environmentScore;
    private int environmentScorePercentile;
    private double socialScore;
    private int socialScorePercentile;
    private double governanceScore;
    private int governanceScorePercentile;
    private int controversyLevel;
    private Map<String, GeneratedObject9> activitiesInvolvement;

    /**
     * Default constructor.
     */
    public ESGScores() {
    }

    /**
     * Initialization constructor.
     * @param  disclaimer  String value for disclaimer.
     * @param  ratingDate  String value for ratingDate.
     * @param  totalEsg  double value for totalEsg.
     * @param  totalEsgPercentile  double value for totalEsgPercentile.
     * @param  environmentScore  double value for environmentScore.
     * @param  environmentScorePercentile  int value for environmentScorePercentile.
     * @param  socialScore  double value for socialScore.
     * @param  socialScorePercentile  int value for socialScorePercentile.
     * @param  governanceScore  double value for governanceScore.
     * @param  governanceScorePercentile  int value for governanceScorePercentile.
     * @param  controversyLevel  int value for controversyLevel.
     * @param  activitiesInvolvement  Map of String, value for activitiesInvolvement.
     */
    public ESGScores(
            String disclaimer,
            String ratingDate,
            double totalEsg,
            double totalEsgPercentile,
            double environmentScore,
            int environmentScorePercentile,
            double socialScore,
            int socialScorePercentile,
            double governanceScore,
            int governanceScorePercentile,
            int controversyLevel,
            Map<String, GeneratedObject9> activitiesInvolvement) {
        this.disclaimer = disclaimer;
        this.ratingDate = ratingDate;
        this.totalEsg = totalEsg;
        this.totalEsgPercentile = totalEsgPercentile;
        this.environmentScore = environmentScore;
        this.environmentScorePercentile = environmentScorePercentile;
        this.socialScore = socialScore;
        this.socialScorePercentile = socialScorePercentile;
        this.governanceScore = governanceScore;
        this.governanceScorePercentile = governanceScorePercentile;
        this.controversyLevel = controversyLevel;
        this.activitiesInvolvement = activitiesInvolvement;
    }

    /**
     * Getter for Disclaimer.
     * @return Returns the String
     */
    @JsonGetter("Disclaimer")
    public String getDisclaimer() {
        return disclaimer;
    }

    /**
     * Setter for Disclaimer.
     * @param disclaimer Value for String
     */
    @JsonSetter("Disclaimer")
    public void setDisclaimer(String disclaimer) {
        this.disclaimer = disclaimer;
    }

    /**
     * Getter for RatingDate.
     * @return Returns the String
     */
    @JsonGetter("RatingDate")
    public String getRatingDate() {
        return ratingDate;
    }

    /**
     * Setter for RatingDate.
     * @param ratingDate Value for String
     */
    @JsonSetter("RatingDate")
    public void setRatingDate(String ratingDate) {
        this.ratingDate = ratingDate;
    }

    /**
     * Getter for TotalEsg.
     * @return Returns the double
     */
    @JsonGetter("TotalEsg")
    public double getTotalEsg() {
        return totalEsg;
    }

    /**
     * Setter for TotalEsg.
     * @param totalEsg Value for double
     */
    @JsonSetter("TotalEsg")
    public void setTotalEsg(double totalEsg) {
        this.totalEsg = totalEsg;
    }

    /**
     * Getter for TotalEsgPercentile.
     * @return Returns the double
     */
    @JsonGetter("TotalEsgPercentile")
    public double getTotalEsgPercentile() {
        return totalEsgPercentile;
    }

    /**
     * Setter for TotalEsgPercentile.
     * @param totalEsgPercentile Value for double
     */
    @JsonSetter("TotalEsgPercentile")
    public void setTotalEsgPercentile(double totalEsgPercentile) {
        this.totalEsgPercentile = totalEsgPercentile;
    }

    /**
     * Getter for EnvironmentScore.
     * @return Returns the double
     */
    @JsonGetter("EnvironmentScore")
    public double getEnvironmentScore() {
        return environmentScore;
    }

    /**
     * Setter for EnvironmentScore.
     * @param environmentScore Value for double
     */
    @JsonSetter("EnvironmentScore")
    public void setEnvironmentScore(double environmentScore) {
        this.environmentScore = environmentScore;
    }

    /**
     * Getter for EnvironmentScorePercentile.
     * @return Returns the int
     */
    @JsonGetter("EnvironmentScorePercentile")
    public int getEnvironmentScorePercentile() {
        return environmentScorePercentile;
    }

    /**
     * Setter for EnvironmentScorePercentile.
     * @param environmentScorePercentile Value for int
     */
    @JsonSetter("EnvironmentScorePercentile")
    public void setEnvironmentScorePercentile(int environmentScorePercentile) {
        this.environmentScorePercentile = environmentScorePercentile;
    }

    /**
     * Getter for SocialScore.
     * @return Returns the double
     */
    @JsonGetter("SocialScore")
    public double getSocialScore() {
        return socialScore;
    }

    /**
     * Setter for SocialScore.
     * @param socialScore Value for double
     */
    @JsonSetter("SocialScore")
    public void setSocialScore(double socialScore) {
        this.socialScore = socialScore;
    }

    /**
     * Getter for SocialScorePercentile.
     * @return Returns the int
     */
    @JsonGetter("SocialScorePercentile")
    public int getSocialScorePercentile() {
        return socialScorePercentile;
    }

    /**
     * Setter for SocialScorePercentile.
     * @param socialScorePercentile Value for int
     */
    @JsonSetter("SocialScorePercentile")
    public void setSocialScorePercentile(int socialScorePercentile) {
        this.socialScorePercentile = socialScorePercentile;
    }

    /**
     * Getter for GovernanceScore.
     * @return Returns the double
     */
    @JsonGetter("GovernanceScore")
    public double getGovernanceScore() {
        return governanceScore;
    }

    /**
     * Setter for GovernanceScore.
     * @param governanceScore Value for double
     */
    @JsonSetter("GovernanceScore")
    public void setGovernanceScore(double governanceScore) {
        this.governanceScore = governanceScore;
    }

    /**
     * Getter for GovernanceScorePercentile.
     * @return Returns the int
     */
    @JsonGetter("GovernanceScorePercentile")
    public int getGovernanceScorePercentile() {
        return governanceScorePercentile;
    }

    /**
     * Setter for GovernanceScorePercentile.
     * @param governanceScorePercentile Value for int
     */
    @JsonSetter("GovernanceScorePercentile")
    public void setGovernanceScorePercentile(int governanceScorePercentile) {
        this.governanceScorePercentile = governanceScorePercentile;
    }

    /**
     * Getter for ControversyLevel.
     * @return Returns the int
     */
    @JsonGetter("ControversyLevel")
    public int getControversyLevel() {
        return controversyLevel;
    }

    /**
     * Setter for ControversyLevel.
     * @param controversyLevel Value for int
     */
    @JsonSetter("ControversyLevel")
    public void setControversyLevel(int controversyLevel) {
        this.controversyLevel = controversyLevel;
    }

    /**
     * Getter for ActivitiesInvolvement.
     * @return Returns the Map of String, GeneratedObject9
     */
    @JsonGetter("ActivitiesInvolvement")
    public Map<String, GeneratedObject9> getActivitiesInvolvement() {
        return activitiesInvolvement;
    }

    /**
     * Setter for ActivitiesInvolvement.
     * @param activitiesInvolvement Value for Map of String, GeneratedObject9
     */
    @JsonSetter("ActivitiesInvolvement")
    public void setActivitiesInvolvement(Map<String, GeneratedObject9> activitiesInvolvement) {
        this.activitiesInvolvement = activitiesInvolvement;
    }

    /**
     * Converts this ESGScores into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ESGScores [" + "disclaimer=" + disclaimer + ", ratingDate=" + ratingDate
                + ", totalEsg=" + totalEsg + ", totalEsgPercentile=" + totalEsgPercentile
                + ", environmentScore=" + environmentScore + ", environmentScorePercentile="
                + environmentScorePercentile + ", socialScore=" + socialScore
                + ", socialScorePercentile=" + socialScorePercentile + ", governanceScore="
                + governanceScore + ", governanceScorePercentile=" + governanceScorePercentile
                + ", controversyLevel=" + controversyLevel + ", activitiesInvolvement="
                + activitiesInvolvement + "]";
    }

    /**
     * Builds a new {@link ESGScores.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ESGScores.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(disclaimer, ratingDate, totalEsg, totalEsgPercentile,
                environmentScore, environmentScorePercentile, socialScore, socialScorePercentile,
                governanceScore, governanceScorePercentile, controversyLevel, activitiesInvolvement);
        return builder;
    }

    /**
     * Class to build instances of {@link ESGScores}.
     */
    public static class Builder {
        private String disclaimer;
        private String ratingDate;
        private double totalEsg;
        private double totalEsgPercentile;
        private double environmentScore;
        private int environmentScorePercentile;
        private double socialScore;
        private int socialScorePercentile;
        private double governanceScore;
        private int governanceScorePercentile;
        private int controversyLevel;
        private Map<String, GeneratedObject9> activitiesInvolvement;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  disclaimer  String value for disclaimer.
         * @param  ratingDate  String value for ratingDate.
         * @param  totalEsg  double value for totalEsg.
         * @param  totalEsgPercentile  double value for totalEsgPercentile.
         * @param  environmentScore  double value for environmentScore.
         * @param  environmentScorePercentile  int value for environmentScorePercentile.
         * @param  socialScore  double value for socialScore.
         * @param  socialScorePercentile  int value for socialScorePercentile.
         * @param  governanceScore  double value for governanceScore.
         * @param  governanceScorePercentile  int value for governanceScorePercentile.
         * @param  controversyLevel  int value for controversyLevel.
         * @param  activitiesInvolvement  Map of String, value for activitiesInvolvement.
         */
        public Builder(String disclaimer, String ratingDate, double totalEsg,
                double totalEsgPercentile, double environmentScore, int environmentScorePercentile,
                double socialScore, int socialScorePercentile, double governanceScore,
                int governanceScorePercentile, int controversyLevel,
                Map<String, GeneratedObject9> activitiesInvolvement) {
            this.disclaimer = disclaimer;
            this.ratingDate = ratingDate;
            this.totalEsg = totalEsg;
            this.totalEsgPercentile = totalEsgPercentile;
            this.environmentScore = environmentScore;
            this.environmentScorePercentile = environmentScorePercentile;
            this.socialScore = socialScore;
            this.socialScorePercentile = socialScorePercentile;
            this.governanceScore = governanceScore;
            this.governanceScorePercentile = governanceScorePercentile;
            this.controversyLevel = controversyLevel;
            this.activitiesInvolvement = activitiesInvolvement;
        }

        /**
         * Setter for disclaimer.
         * @param  disclaimer  String value for disclaimer.
         * @return Builder
         */
        public Builder disclaimer(String disclaimer) {
            this.disclaimer = disclaimer;
            return this;
        }

        /**
         * Setter for ratingDate.
         * @param  ratingDate  String value for ratingDate.
         * @return Builder
         */
        public Builder ratingDate(String ratingDate) {
            this.ratingDate = ratingDate;
            return this;
        }

        /**
         * Setter for totalEsg.
         * @param  totalEsg  double value for totalEsg.
         * @return Builder
         */
        public Builder totalEsg(double totalEsg) {
            this.totalEsg = totalEsg;
            return this;
        }

        /**
         * Setter for totalEsgPercentile.
         * @param  totalEsgPercentile  double value for totalEsgPercentile.
         * @return Builder
         */
        public Builder totalEsgPercentile(double totalEsgPercentile) {
            this.totalEsgPercentile = totalEsgPercentile;
            return this;
        }

        /**
         * Setter for environmentScore.
         * @param  environmentScore  double value for environmentScore.
         * @return Builder
         */
        public Builder environmentScore(double environmentScore) {
            this.environmentScore = environmentScore;
            return this;
        }

        /**
         * Setter for environmentScorePercentile.
         * @param  environmentScorePercentile  int value for environmentScorePercentile.
         * @return Builder
         */
        public Builder environmentScorePercentile(int environmentScorePercentile) {
            this.environmentScorePercentile = environmentScorePercentile;
            return this;
        }

        /**
         * Setter for socialScore.
         * @param  socialScore  double value for socialScore.
         * @return Builder
         */
        public Builder socialScore(double socialScore) {
            this.socialScore = socialScore;
            return this;
        }

        /**
         * Setter for socialScorePercentile.
         * @param  socialScorePercentile  int value for socialScorePercentile.
         * @return Builder
         */
        public Builder socialScorePercentile(int socialScorePercentile) {
            this.socialScorePercentile = socialScorePercentile;
            return this;
        }

        /**
         * Setter for governanceScore.
         * @param  governanceScore  double value for governanceScore.
         * @return Builder
         */
        public Builder governanceScore(double governanceScore) {
            this.governanceScore = governanceScore;
            return this;
        }

        /**
         * Setter for governanceScorePercentile.
         * @param  governanceScorePercentile  int value for governanceScorePercentile.
         * @return Builder
         */
        public Builder governanceScorePercentile(int governanceScorePercentile) {
            this.governanceScorePercentile = governanceScorePercentile;
            return this;
        }

        /**
         * Setter for controversyLevel.
         * @param  controversyLevel  int value for controversyLevel.
         * @return Builder
         */
        public Builder controversyLevel(int controversyLevel) {
            this.controversyLevel = controversyLevel;
            return this;
        }

        /**
         * Setter for activitiesInvolvement.
         * @param  activitiesInvolvement  Map of String, value for activitiesInvolvement.
         * @return Builder
         */
        public Builder activitiesInvolvement(
                Map<String, GeneratedObject9> activitiesInvolvement) {
            this.activitiesInvolvement = activitiesInvolvement;
            return this;
        }

        /**
         * Builds a new {@link ESGScores} object using the set fields.
         * @return {@link ESGScores}
         */
        public ESGScores build() {
            return new ESGScores(disclaimer, ratingDate, totalEsg, totalEsgPercentile,
                    environmentScore, environmentScorePercentile, socialScore,
                    socialScorePercentile, governanceScore, governanceScorePercentile,
                    controversyLevel, activitiesInvolvement);
        }
    }
}
