/*
 * EODHistoricalDataFundamentalLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.eodhistoricaldata.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for GeneratedObject1 type.
 */
public class GeneratedObject1 {
    private String name;
    private String title;
    private String yearBorn;

    /**
     * Default constructor.
     */
    public GeneratedObject1() {
    }

    /**
     * Initialization constructor.
     * @param  name  String value for name.
     * @param  title  String value for title.
     * @param  yearBorn  String value for yearBorn.
     */
    public GeneratedObject1(
            String name,
            String title,
            String yearBorn) {
        this.name = name;
        this.title = title;
        this.yearBorn = yearBorn;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("Name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("Name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for Title.
     * @return Returns the String
     */
    @JsonGetter("Title")
    public String getTitle() {
        return title;
    }

    /**
     * Setter for Title.
     * @param title Value for String
     */
    @JsonSetter("Title")
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for YearBorn.
     * @return Returns the String
     */
    @JsonGetter("YearBorn")
    public String getYearBorn() {
        return yearBorn;
    }

    /**
     * Setter for YearBorn.
     * @param yearBorn Value for String
     */
    @JsonSetter("YearBorn")
    public void setYearBorn(String yearBorn) {
        this.yearBorn = yearBorn;
    }

    /**
     * Converts this GeneratedObject1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GeneratedObject1 [" + "name=" + name + ", title=" + title + ", yearBorn=" + yearBorn
                + "]";
    }

    /**
     * Builds a new {@link GeneratedObject1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GeneratedObject1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(name, title, yearBorn);
        return builder;
    }

    /**
     * Class to build instances of {@link GeneratedObject1}.
     */
    public static class Builder {
        private String name;
        private String title;
        private String yearBorn;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  name  String value for name.
         * @param  title  String value for title.
         * @param  yearBorn  String value for yearBorn.
         */
        public Builder(String name, String title, String yearBorn) {
            this.name = name;
            this.title = title;
            this.yearBorn = yearBorn;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for title.
         * @param  title  String value for title.
         * @return Builder
         */
        public Builder title(String title) {
            this.title = title;
            return this;
        }

        /**
         * Setter for yearBorn.
         * @param  yearBorn  String value for yearBorn.
         * @return Builder
         */
        public Builder yearBorn(String yearBorn) {
            this.yearBorn = yearBorn;
            return this;
        }

        /**
         * Builds a new {@link GeneratedObject1} object using the set fields.
         * @return {@link GeneratedObject1}
         */
        public GeneratedObject1 build() {
            return new GeneratedObject1(name, title, yearBorn);
        }
    }
}
