/*
 * EODHistoricalDataFundamentalLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.eodhistoricaldata.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for GeneratedObject19 type.
 */
public class GeneratedObject19 {
    private String date;
    private String filingDate;
    private String currencySymbol;
    private String investments;
    private String changeToLiabilities;
    private String totalCashflowsFromInvestingActivities;
    private String netBorrowings;
    private String totalCashFromFinancingActivities;
    private String changeToOperatingActivities;
    private String netIncome;
    private String changeInCash;
    private String beginPeriodCashFlow;
    private String endPeriodCashFlow;
    private String totalCashFromOperatingActivities;
    private String depreciation;
    private String otherCashflowsFromInvestingActivities;
    private String dividendsPaid;
    private String changeToInventory;
    private String changeToAccountReceivables;
    private String salePurchaseOfStock;
    private String otherCashflowsFromFinancingActivities;
    private String changeToNetincome;
    private String capitalExpenditures;
    private String changeReceivables;
    private String cashFlowsOtherOperating;
    private String exchangeRateChanges;
    private String cashAndCashEquivalentsChanges;
    private String changeInWorkingCapital;
    private String otherNonCashItems;
    private String freeCashFlow;

    /**
     * Default constructor.
     */
    public GeneratedObject19() {
    }

    /**
     * Initialization constructor.
     * @param  date  String value for date.
     * @param  filingDate  String value for filingDate.
     * @param  currencySymbol  String value for currencySymbol.
     * @param  investments  String value for investments.
     * @param  changeToLiabilities  String value for changeToLiabilities.
     * @param  totalCashflowsFromInvestingActivities  String value for
     *         totalCashflowsFromInvestingActivities.
     * @param  netBorrowings  String value for netBorrowings.
     * @param  totalCashFromFinancingActivities  String value for totalCashFromFinancingActivities.
     * @param  changeToOperatingActivities  String value for changeToOperatingActivities.
     * @param  netIncome  String value for netIncome.
     * @param  changeInCash  String value for changeInCash.
     * @param  beginPeriodCashFlow  String value for beginPeriodCashFlow.
     * @param  endPeriodCashFlow  String value for endPeriodCashFlow.
     * @param  totalCashFromOperatingActivities  String value for totalCashFromOperatingActivities.
     * @param  depreciation  String value for depreciation.
     * @param  otherCashflowsFromInvestingActivities  String value for
     *         otherCashflowsFromInvestingActivities.
     * @param  dividendsPaid  String value for dividendsPaid.
     * @param  changeToInventory  String value for changeToInventory.
     * @param  changeToAccountReceivables  String value for changeToAccountReceivables.
     * @param  salePurchaseOfStock  String value for salePurchaseOfStock.
     * @param  otherCashflowsFromFinancingActivities  String value for
     *         otherCashflowsFromFinancingActivities.
     * @param  changeToNetincome  String value for changeToNetincome.
     * @param  capitalExpenditures  String value for capitalExpenditures.
     * @param  changeReceivables  String value for changeReceivables.
     * @param  cashFlowsOtherOperating  String value for cashFlowsOtherOperating.
     * @param  exchangeRateChanges  String value for exchangeRateChanges.
     * @param  cashAndCashEquivalentsChanges  String value for cashAndCashEquivalentsChanges.
     * @param  changeInWorkingCapital  String value for changeInWorkingCapital.
     * @param  otherNonCashItems  String value for otherNonCashItems.
     * @param  freeCashFlow  String value for freeCashFlow.
     */
    public GeneratedObject19(
            String date,
            String filingDate,
            String currencySymbol,
            String investments,
            String changeToLiabilities,
            String totalCashflowsFromInvestingActivities,
            String netBorrowings,
            String totalCashFromFinancingActivities,
            String changeToOperatingActivities,
            String netIncome,
            String changeInCash,
            String beginPeriodCashFlow,
            String endPeriodCashFlow,
            String totalCashFromOperatingActivities,
            String depreciation,
            String otherCashflowsFromInvestingActivities,
            String dividendsPaid,
            String changeToInventory,
            String changeToAccountReceivables,
            String salePurchaseOfStock,
            String otherCashflowsFromFinancingActivities,
            String changeToNetincome,
            String capitalExpenditures,
            String changeReceivables,
            String cashFlowsOtherOperating,
            String exchangeRateChanges,
            String cashAndCashEquivalentsChanges,
            String changeInWorkingCapital,
            String otherNonCashItems,
            String freeCashFlow) {
        this.date = date;
        this.filingDate = filingDate;
        this.currencySymbol = currencySymbol;
        this.investments = investments;
        this.changeToLiabilities = changeToLiabilities;
        this.totalCashflowsFromInvestingActivities = totalCashflowsFromInvestingActivities;
        this.netBorrowings = netBorrowings;
        this.totalCashFromFinancingActivities = totalCashFromFinancingActivities;
        this.changeToOperatingActivities = changeToOperatingActivities;
        this.netIncome = netIncome;
        this.changeInCash = changeInCash;
        this.beginPeriodCashFlow = beginPeriodCashFlow;
        this.endPeriodCashFlow = endPeriodCashFlow;
        this.totalCashFromOperatingActivities = totalCashFromOperatingActivities;
        this.depreciation = depreciation;
        this.otherCashflowsFromInvestingActivities = otherCashflowsFromInvestingActivities;
        this.dividendsPaid = dividendsPaid;
        this.changeToInventory = changeToInventory;
        this.changeToAccountReceivables = changeToAccountReceivables;
        this.salePurchaseOfStock = salePurchaseOfStock;
        this.otherCashflowsFromFinancingActivities = otherCashflowsFromFinancingActivities;
        this.changeToNetincome = changeToNetincome;
        this.capitalExpenditures = capitalExpenditures;
        this.changeReceivables = changeReceivables;
        this.cashFlowsOtherOperating = cashFlowsOtherOperating;
        this.exchangeRateChanges = exchangeRateChanges;
        this.cashAndCashEquivalentsChanges = cashAndCashEquivalentsChanges;
        this.changeInWorkingCapital = changeInWorkingCapital;
        this.otherNonCashItems = otherNonCashItems;
        this.freeCashFlow = freeCashFlow;
    }

    /**
     * Getter for Date.
     * @return Returns the String
     */
    @JsonGetter("date")
    public String getDate() {
        return date;
    }

    /**
     * Setter for Date.
     * @param date Value for String
     */
    @JsonSetter("date")
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * Getter for FilingDate.
     * @return Returns the String
     */
    @JsonGetter("filing_date")
    public String getFilingDate() {
        return filingDate;
    }

    /**
     * Setter for FilingDate.
     * @param filingDate Value for String
     */
    @JsonSetter("filing_date")
    public void setFilingDate(String filingDate) {
        this.filingDate = filingDate;
    }

    /**
     * Getter for CurrencySymbol.
     * @return Returns the String
     */
    @JsonGetter("currency_symbol")
    public String getCurrencySymbol() {
        return currencySymbol;
    }

    /**
     * Setter for CurrencySymbol.
     * @param currencySymbol Value for String
     */
    @JsonSetter("currency_symbol")
    public void setCurrencySymbol(String currencySymbol) {
        this.currencySymbol = currencySymbol;
    }

    /**
     * Getter for Investments.
     * @return Returns the String
     */
    @JsonGetter("investments")
    public String getInvestments() {
        return investments;
    }

    /**
     * Setter for Investments.
     * @param investments Value for String
     */
    @JsonSetter("investments")
    public void setInvestments(String investments) {
        this.investments = investments;
    }

    /**
     * Getter for ChangeToLiabilities.
     * @return Returns the String
     */
    @JsonGetter("changeToLiabilities")
    public String getChangeToLiabilities() {
        return changeToLiabilities;
    }

    /**
     * Setter for ChangeToLiabilities.
     * @param changeToLiabilities Value for String
     */
    @JsonSetter("changeToLiabilities")
    public void setChangeToLiabilities(String changeToLiabilities) {
        this.changeToLiabilities = changeToLiabilities;
    }

    /**
     * Getter for TotalCashflowsFromInvestingActivities.
     * @return Returns the String
     */
    @JsonGetter("totalCashflowsFromInvestingActivities")
    public String getTotalCashflowsFromInvestingActivities() {
        return totalCashflowsFromInvestingActivities;
    }

    /**
     * Setter for TotalCashflowsFromInvestingActivities.
     * @param totalCashflowsFromInvestingActivities Value for String
     */
    @JsonSetter("totalCashflowsFromInvestingActivities")
    public void setTotalCashflowsFromInvestingActivities(String totalCashflowsFromInvestingActivities) {
        this.totalCashflowsFromInvestingActivities = totalCashflowsFromInvestingActivities;
    }

    /**
     * Getter for NetBorrowings.
     * @return Returns the String
     */
    @JsonGetter("netBorrowings")
    public String getNetBorrowings() {
        return netBorrowings;
    }

    /**
     * Setter for NetBorrowings.
     * @param netBorrowings Value for String
     */
    @JsonSetter("netBorrowings")
    public void setNetBorrowings(String netBorrowings) {
        this.netBorrowings = netBorrowings;
    }

    /**
     * Getter for TotalCashFromFinancingActivities.
     * @return Returns the String
     */
    @JsonGetter("totalCashFromFinancingActivities")
    public String getTotalCashFromFinancingActivities() {
        return totalCashFromFinancingActivities;
    }

    /**
     * Setter for TotalCashFromFinancingActivities.
     * @param totalCashFromFinancingActivities Value for String
     */
    @JsonSetter("totalCashFromFinancingActivities")
    public void setTotalCashFromFinancingActivities(String totalCashFromFinancingActivities) {
        this.totalCashFromFinancingActivities = totalCashFromFinancingActivities;
    }

    /**
     * Getter for ChangeToOperatingActivities.
     * @return Returns the String
     */
    @JsonGetter("changeToOperatingActivities")
    public String getChangeToOperatingActivities() {
        return changeToOperatingActivities;
    }

    /**
     * Setter for ChangeToOperatingActivities.
     * @param changeToOperatingActivities Value for String
     */
    @JsonSetter("changeToOperatingActivities")
    public void setChangeToOperatingActivities(String changeToOperatingActivities) {
        this.changeToOperatingActivities = changeToOperatingActivities;
    }

    /**
     * Getter for NetIncome.
     * @return Returns the String
     */
    @JsonGetter("netIncome")
    public String getNetIncome() {
        return netIncome;
    }

    /**
     * Setter for NetIncome.
     * @param netIncome Value for String
     */
    @JsonSetter("netIncome")
    public void setNetIncome(String netIncome) {
        this.netIncome = netIncome;
    }

    /**
     * Getter for ChangeInCash.
     * @return Returns the String
     */
    @JsonGetter("changeInCash")
    public String getChangeInCash() {
        return changeInCash;
    }

    /**
     * Setter for ChangeInCash.
     * @param changeInCash Value for String
     */
    @JsonSetter("changeInCash")
    public void setChangeInCash(String changeInCash) {
        this.changeInCash = changeInCash;
    }

    /**
     * Getter for BeginPeriodCashFlow.
     * @return Returns the String
     */
    @JsonGetter("beginPeriodCashFlow")
    public String getBeginPeriodCashFlow() {
        return beginPeriodCashFlow;
    }

    /**
     * Setter for BeginPeriodCashFlow.
     * @param beginPeriodCashFlow Value for String
     */
    @JsonSetter("beginPeriodCashFlow")
    public void setBeginPeriodCashFlow(String beginPeriodCashFlow) {
        this.beginPeriodCashFlow = beginPeriodCashFlow;
    }

    /**
     * Getter for EndPeriodCashFlow.
     * @return Returns the String
     */
    @JsonGetter("endPeriodCashFlow")
    public String getEndPeriodCashFlow() {
        return endPeriodCashFlow;
    }

    /**
     * Setter for EndPeriodCashFlow.
     * @param endPeriodCashFlow Value for String
     */
    @JsonSetter("endPeriodCashFlow")
    public void setEndPeriodCashFlow(String endPeriodCashFlow) {
        this.endPeriodCashFlow = endPeriodCashFlow;
    }

    /**
     * Getter for TotalCashFromOperatingActivities.
     * @return Returns the String
     */
    @JsonGetter("totalCashFromOperatingActivities")
    public String getTotalCashFromOperatingActivities() {
        return totalCashFromOperatingActivities;
    }

    /**
     * Setter for TotalCashFromOperatingActivities.
     * @param totalCashFromOperatingActivities Value for String
     */
    @JsonSetter("totalCashFromOperatingActivities")
    public void setTotalCashFromOperatingActivities(String totalCashFromOperatingActivities) {
        this.totalCashFromOperatingActivities = totalCashFromOperatingActivities;
    }

    /**
     * Getter for Depreciation.
     * @return Returns the String
     */
    @JsonGetter("depreciation")
    public String getDepreciation() {
        return depreciation;
    }

    /**
     * Setter for Depreciation.
     * @param depreciation Value for String
     */
    @JsonSetter("depreciation")
    public void setDepreciation(String depreciation) {
        this.depreciation = depreciation;
    }

    /**
     * Getter for OtherCashflowsFromInvestingActivities.
     * @return Returns the String
     */
    @JsonGetter("otherCashflowsFromInvestingActivities")
    public String getOtherCashflowsFromInvestingActivities() {
        return otherCashflowsFromInvestingActivities;
    }

    /**
     * Setter for OtherCashflowsFromInvestingActivities.
     * @param otherCashflowsFromInvestingActivities Value for String
     */
    @JsonSetter("otherCashflowsFromInvestingActivities")
    public void setOtherCashflowsFromInvestingActivities(String otherCashflowsFromInvestingActivities) {
        this.otherCashflowsFromInvestingActivities = otherCashflowsFromInvestingActivities;
    }

    /**
     * Getter for DividendsPaid.
     * @return Returns the String
     */
    @JsonGetter("dividendsPaid")
    public String getDividendsPaid() {
        return dividendsPaid;
    }

    /**
     * Setter for DividendsPaid.
     * @param dividendsPaid Value for String
     */
    @JsonSetter("dividendsPaid")
    public void setDividendsPaid(String dividendsPaid) {
        this.dividendsPaid = dividendsPaid;
    }

    /**
     * Getter for ChangeToInventory.
     * @return Returns the String
     */
    @JsonGetter("changeToInventory")
    public String getChangeToInventory() {
        return changeToInventory;
    }

    /**
     * Setter for ChangeToInventory.
     * @param changeToInventory Value for String
     */
    @JsonSetter("changeToInventory")
    public void setChangeToInventory(String changeToInventory) {
        this.changeToInventory = changeToInventory;
    }

    /**
     * Getter for ChangeToAccountReceivables.
     * @return Returns the String
     */
    @JsonGetter("changeToAccountReceivables")
    public String getChangeToAccountReceivables() {
        return changeToAccountReceivables;
    }

    /**
     * Setter for ChangeToAccountReceivables.
     * @param changeToAccountReceivables Value for String
     */
    @JsonSetter("changeToAccountReceivables")
    public void setChangeToAccountReceivables(String changeToAccountReceivables) {
        this.changeToAccountReceivables = changeToAccountReceivables;
    }

    /**
     * Getter for SalePurchaseOfStock.
     * @return Returns the String
     */
    @JsonGetter("salePurchaseOfStock")
    public String getSalePurchaseOfStock() {
        return salePurchaseOfStock;
    }

    /**
     * Setter for SalePurchaseOfStock.
     * @param salePurchaseOfStock Value for String
     */
    @JsonSetter("salePurchaseOfStock")
    public void setSalePurchaseOfStock(String salePurchaseOfStock) {
        this.salePurchaseOfStock = salePurchaseOfStock;
    }

    /**
     * Getter for OtherCashflowsFromFinancingActivities.
     * @return Returns the String
     */
    @JsonGetter("otherCashflowsFromFinancingActivities")
    public String getOtherCashflowsFromFinancingActivities() {
        return otherCashflowsFromFinancingActivities;
    }

    /**
     * Setter for OtherCashflowsFromFinancingActivities.
     * @param otherCashflowsFromFinancingActivities Value for String
     */
    @JsonSetter("otherCashflowsFromFinancingActivities")
    public void setOtherCashflowsFromFinancingActivities(String otherCashflowsFromFinancingActivities) {
        this.otherCashflowsFromFinancingActivities = otherCashflowsFromFinancingActivities;
    }

    /**
     * Getter for ChangeToNetincome.
     * @return Returns the String
     */
    @JsonGetter("changeToNetincome")
    public String getChangeToNetincome() {
        return changeToNetincome;
    }

    /**
     * Setter for ChangeToNetincome.
     * @param changeToNetincome Value for String
     */
    @JsonSetter("changeToNetincome")
    public void setChangeToNetincome(String changeToNetincome) {
        this.changeToNetincome = changeToNetincome;
    }

    /**
     * Getter for CapitalExpenditures.
     * @return Returns the String
     */
    @JsonGetter("capitalExpenditures")
    public String getCapitalExpenditures() {
        return capitalExpenditures;
    }

    /**
     * Setter for CapitalExpenditures.
     * @param capitalExpenditures Value for String
     */
    @JsonSetter("capitalExpenditures")
    public void setCapitalExpenditures(String capitalExpenditures) {
        this.capitalExpenditures = capitalExpenditures;
    }

    /**
     * Getter for ChangeReceivables.
     * @return Returns the String
     */
    @JsonGetter("changeReceivables")
    public String getChangeReceivables() {
        return changeReceivables;
    }

    /**
     * Setter for ChangeReceivables.
     * @param changeReceivables Value for String
     */
    @JsonSetter("changeReceivables")
    public void setChangeReceivables(String changeReceivables) {
        this.changeReceivables = changeReceivables;
    }

    /**
     * Getter for CashFlowsOtherOperating.
     * @return Returns the String
     */
    @JsonGetter("cashFlowsOtherOperating")
    public String getCashFlowsOtherOperating() {
        return cashFlowsOtherOperating;
    }

    /**
     * Setter for CashFlowsOtherOperating.
     * @param cashFlowsOtherOperating Value for String
     */
    @JsonSetter("cashFlowsOtherOperating")
    public void setCashFlowsOtherOperating(String cashFlowsOtherOperating) {
        this.cashFlowsOtherOperating = cashFlowsOtherOperating;
    }

    /**
     * Getter for ExchangeRateChanges.
     * @return Returns the String
     */
    @JsonGetter("exchangeRateChanges")
    public String getExchangeRateChanges() {
        return exchangeRateChanges;
    }

    /**
     * Setter for ExchangeRateChanges.
     * @param exchangeRateChanges Value for String
     */
    @JsonSetter("exchangeRateChanges")
    public void setExchangeRateChanges(String exchangeRateChanges) {
        this.exchangeRateChanges = exchangeRateChanges;
    }

    /**
     * Getter for CashAndCashEquivalentsChanges.
     * @return Returns the String
     */
    @JsonGetter("cashAndCashEquivalentsChanges")
    public String getCashAndCashEquivalentsChanges() {
        return cashAndCashEquivalentsChanges;
    }

    /**
     * Setter for CashAndCashEquivalentsChanges.
     * @param cashAndCashEquivalentsChanges Value for String
     */
    @JsonSetter("cashAndCashEquivalentsChanges")
    public void setCashAndCashEquivalentsChanges(String cashAndCashEquivalentsChanges) {
        this.cashAndCashEquivalentsChanges = cashAndCashEquivalentsChanges;
    }

    /**
     * Getter for ChangeInWorkingCapital.
     * @return Returns the String
     */
    @JsonGetter("changeInWorkingCapital")
    public String getChangeInWorkingCapital() {
        return changeInWorkingCapital;
    }

    /**
     * Setter for ChangeInWorkingCapital.
     * @param changeInWorkingCapital Value for String
     */
    @JsonSetter("changeInWorkingCapital")
    public void setChangeInWorkingCapital(String changeInWorkingCapital) {
        this.changeInWorkingCapital = changeInWorkingCapital;
    }

    /**
     * Getter for OtherNonCashItems.
     * @return Returns the String
     */
    @JsonGetter("otherNonCashItems")
    public String getOtherNonCashItems() {
        return otherNonCashItems;
    }

    /**
     * Setter for OtherNonCashItems.
     * @param otherNonCashItems Value for String
     */
    @JsonSetter("otherNonCashItems")
    public void setOtherNonCashItems(String otherNonCashItems) {
        this.otherNonCashItems = otherNonCashItems;
    }

    /**
     * Getter for FreeCashFlow.
     * @return Returns the String
     */
    @JsonGetter("freeCashFlow")
    public String getFreeCashFlow() {
        return freeCashFlow;
    }

    /**
     * Setter for FreeCashFlow.
     * @param freeCashFlow Value for String
     */
    @JsonSetter("freeCashFlow")
    public void setFreeCashFlow(String freeCashFlow) {
        this.freeCashFlow = freeCashFlow;
    }

    /**
     * Converts this GeneratedObject19 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GeneratedObject19 [" + "date=" + date + ", filingDate=" + filingDate
                + ", currencySymbol=" + currencySymbol + ", investments=" + investments
                + ", changeToLiabilities=" + changeToLiabilities
                + ", totalCashflowsFromInvestingActivities=" + totalCashflowsFromInvestingActivities
                + ", netBorrowings=" + netBorrowings + ", totalCashFromFinancingActivities="
                + totalCashFromFinancingActivities + ", changeToOperatingActivities="
                + changeToOperatingActivities + ", netIncome=" + netIncome + ", changeInCash="
                + changeInCash + ", beginPeriodCashFlow=" + beginPeriodCashFlow
                + ", endPeriodCashFlow=" + endPeriodCashFlow + ", totalCashFromOperatingActivities="
                + totalCashFromOperatingActivities + ", depreciation=" + depreciation
                + ", otherCashflowsFromInvestingActivities=" + otherCashflowsFromInvestingActivities
                + ", dividendsPaid=" + dividendsPaid + ", changeToInventory=" + changeToInventory
                + ", changeToAccountReceivables=" + changeToAccountReceivables
                + ", salePurchaseOfStock=" + salePurchaseOfStock
                + ", otherCashflowsFromFinancingActivities=" + otherCashflowsFromFinancingActivities
                + ", changeToNetincome=" + changeToNetincome + ", capitalExpenditures="
                + capitalExpenditures + ", changeReceivables=" + changeReceivables
                + ", cashFlowsOtherOperating=" + cashFlowsOtherOperating + ", exchangeRateChanges="
                + exchangeRateChanges + ", cashAndCashEquivalentsChanges="
                + cashAndCashEquivalentsChanges + ", changeInWorkingCapital="
                + changeInWorkingCapital + ", otherNonCashItems=" + otherNonCashItems
                + ", freeCashFlow=" + freeCashFlow + "]";
    }

    /**
     * Builds a new {@link GeneratedObject19.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GeneratedObject19.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(date, filingDate, currencySymbol, investments,
                changeToLiabilities, totalCashflowsFromInvestingActivities, netBorrowings,
                totalCashFromFinancingActivities, changeToOperatingActivities, netIncome,
                changeInCash, beginPeriodCashFlow, endPeriodCashFlow,
                totalCashFromOperatingActivities, depreciation,
                otherCashflowsFromInvestingActivities, dividendsPaid, changeToInventory,
                changeToAccountReceivables, salePurchaseOfStock,
                otherCashflowsFromFinancingActivities, changeToNetincome, capitalExpenditures,
                changeReceivables, cashFlowsOtherOperating, exchangeRateChanges,
                cashAndCashEquivalentsChanges, changeInWorkingCapital, otherNonCashItems,
                freeCashFlow);
        return builder;
    }

    /**
     * Class to build instances of {@link GeneratedObject19}.
     */
    public static class Builder {
        private String date;
        private String filingDate;
        private String currencySymbol;
        private String investments;
        private String changeToLiabilities;
        private String totalCashflowsFromInvestingActivities;
        private String netBorrowings;
        private String totalCashFromFinancingActivities;
        private String changeToOperatingActivities;
        private String netIncome;
        private String changeInCash;
        private String beginPeriodCashFlow;
        private String endPeriodCashFlow;
        private String totalCashFromOperatingActivities;
        private String depreciation;
        private String otherCashflowsFromInvestingActivities;
        private String dividendsPaid;
        private String changeToInventory;
        private String changeToAccountReceivables;
        private String salePurchaseOfStock;
        private String otherCashflowsFromFinancingActivities;
        private String changeToNetincome;
        private String capitalExpenditures;
        private String changeReceivables;
        private String cashFlowsOtherOperating;
        private String exchangeRateChanges;
        private String cashAndCashEquivalentsChanges;
        private String changeInWorkingCapital;
        private String otherNonCashItems;
        private String freeCashFlow;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  date  String value for date.
         * @param  filingDate  String value for filingDate.
         * @param  currencySymbol  String value for currencySymbol.
         * @param  investments  String value for investments.
         * @param  changeToLiabilities  String value for changeToLiabilities.
         * @param  totalCashflowsFromInvestingActivities  String value for
         *         totalCashflowsFromInvestingActivities.
         * @param  netBorrowings  String value for netBorrowings.
         * @param  totalCashFromFinancingActivities  String value for
         *         totalCashFromFinancingActivities.
         * @param  changeToOperatingActivities  String value for changeToOperatingActivities.
         * @param  netIncome  String value for netIncome.
         * @param  changeInCash  String value for changeInCash.
         * @param  beginPeriodCashFlow  String value for beginPeriodCashFlow.
         * @param  endPeriodCashFlow  String value for endPeriodCashFlow.
         * @param  totalCashFromOperatingActivities  String value for
         *         totalCashFromOperatingActivities.
         * @param  depreciation  String value for depreciation.
         * @param  otherCashflowsFromInvestingActivities  String value for
         *         otherCashflowsFromInvestingActivities.
         * @param  dividendsPaid  String value for dividendsPaid.
         * @param  changeToInventory  String value for changeToInventory.
         * @param  changeToAccountReceivables  String value for changeToAccountReceivables.
         * @param  salePurchaseOfStock  String value for salePurchaseOfStock.
         * @param  otherCashflowsFromFinancingActivities  String value for
         *         otherCashflowsFromFinancingActivities.
         * @param  changeToNetincome  String value for changeToNetincome.
         * @param  capitalExpenditures  String value for capitalExpenditures.
         * @param  changeReceivables  String value for changeReceivables.
         * @param  cashFlowsOtherOperating  String value for cashFlowsOtherOperating.
         * @param  exchangeRateChanges  String value for exchangeRateChanges.
         * @param  cashAndCashEquivalentsChanges  String value for cashAndCashEquivalentsChanges.
         * @param  changeInWorkingCapital  String value for changeInWorkingCapital.
         * @param  otherNonCashItems  String value for otherNonCashItems.
         * @param  freeCashFlow  String value for freeCashFlow.
         */
        public Builder(String date, String filingDate, String currencySymbol, String investments,
                String changeToLiabilities, String totalCashflowsFromInvestingActivities,
                String netBorrowings, String totalCashFromFinancingActivities,
                String changeToOperatingActivities, String netIncome, String changeInCash,
                String beginPeriodCashFlow, String endPeriodCashFlow,
                String totalCashFromOperatingActivities, String depreciation,
                String otherCashflowsFromInvestingActivities, String dividendsPaid,
                String changeToInventory, String changeToAccountReceivables,
                String salePurchaseOfStock, String otherCashflowsFromFinancingActivities,
                String changeToNetincome, String capitalExpenditures, String changeReceivables,
                String cashFlowsOtherOperating, String exchangeRateChanges,
                String cashAndCashEquivalentsChanges, String changeInWorkingCapital,
                String otherNonCashItems, String freeCashFlow) {
            this.date = date;
            this.filingDate = filingDate;
            this.currencySymbol = currencySymbol;
            this.investments = investments;
            this.changeToLiabilities = changeToLiabilities;
            this.totalCashflowsFromInvestingActivities = totalCashflowsFromInvestingActivities;
            this.netBorrowings = netBorrowings;
            this.totalCashFromFinancingActivities = totalCashFromFinancingActivities;
            this.changeToOperatingActivities = changeToOperatingActivities;
            this.netIncome = netIncome;
            this.changeInCash = changeInCash;
            this.beginPeriodCashFlow = beginPeriodCashFlow;
            this.endPeriodCashFlow = endPeriodCashFlow;
            this.totalCashFromOperatingActivities = totalCashFromOperatingActivities;
            this.depreciation = depreciation;
            this.otherCashflowsFromInvestingActivities = otherCashflowsFromInvestingActivities;
            this.dividendsPaid = dividendsPaid;
            this.changeToInventory = changeToInventory;
            this.changeToAccountReceivables = changeToAccountReceivables;
            this.salePurchaseOfStock = salePurchaseOfStock;
            this.otherCashflowsFromFinancingActivities = otherCashflowsFromFinancingActivities;
            this.changeToNetincome = changeToNetincome;
            this.capitalExpenditures = capitalExpenditures;
            this.changeReceivables = changeReceivables;
            this.cashFlowsOtherOperating = cashFlowsOtherOperating;
            this.exchangeRateChanges = exchangeRateChanges;
            this.cashAndCashEquivalentsChanges = cashAndCashEquivalentsChanges;
            this.changeInWorkingCapital = changeInWorkingCapital;
            this.otherNonCashItems = otherNonCashItems;
            this.freeCashFlow = freeCashFlow;
        }

        /**
         * Setter for date.
         * @param  date  String value for date.
         * @return Builder
         */
        public Builder date(String date) {
            this.date = date;
            return this;
        }

        /**
         * Setter for filingDate.
         * @param  filingDate  String value for filingDate.
         * @return Builder
         */
        public Builder filingDate(String filingDate) {
            this.filingDate = filingDate;
            return this;
        }

        /**
         * Setter for currencySymbol.
         * @param  currencySymbol  String value for currencySymbol.
         * @return Builder
         */
        public Builder currencySymbol(String currencySymbol) {
            this.currencySymbol = currencySymbol;
            return this;
        }

        /**
         * Setter for investments.
         * @param  investments  String value for investments.
         * @return Builder
         */
        public Builder investments(String investments) {
            this.investments = investments;
            return this;
        }

        /**
         * Setter for changeToLiabilities.
         * @param  changeToLiabilities  String value for changeToLiabilities.
         * @return Builder
         */
        public Builder changeToLiabilities(String changeToLiabilities) {
            this.changeToLiabilities = changeToLiabilities;
            return this;
        }

        /**
         * Setter for totalCashflowsFromInvestingActivities.
         * @param  totalCashflowsFromInvestingActivities  String value for
         *         totalCashflowsFromInvestingActivities.
         * @return Builder
         */
        public Builder totalCashflowsFromInvestingActivities(
                String totalCashflowsFromInvestingActivities) {
            this.totalCashflowsFromInvestingActivities = totalCashflowsFromInvestingActivities;
            return this;
        }

        /**
         * Setter for netBorrowings.
         * @param  netBorrowings  String value for netBorrowings.
         * @return Builder
         */
        public Builder netBorrowings(String netBorrowings) {
            this.netBorrowings = netBorrowings;
            return this;
        }

        /**
         * Setter for totalCashFromFinancingActivities.
         * @param  totalCashFromFinancingActivities  String value for
         *         totalCashFromFinancingActivities.
         * @return Builder
         */
        public Builder totalCashFromFinancingActivities(String totalCashFromFinancingActivities) {
            this.totalCashFromFinancingActivities = totalCashFromFinancingActivities;
            return this;
        }

        /**
         * Setter for changeToOperatingActivities.
         * @param  changeToOperatingActivities  String value for changeToOperatingActivities.
         * @return Builder
         */
        public Builder changeToOperatingActivities(String changeToOperatingActivities) {
            this.changeToOperatingActivities = changeToOperatingActivities;
            return this;
        }

        /**
         * Setter for netIncome.
         * @param  netIncome  String value for netIncome.
         * @return Builder
         */
        public Builder netIncome(String netIncome) {
            this.netIncome = netIncome;
            return this;
        }

        /**
         * Setter for changeInCash.
         * @param  changeInCash  String value for changeInCash.
         * @return Builder
         */
        public Builder changeInCash(String changeInCash) {
            this.changeInCash = changeInCash;
            return this;
        }

        /**
         * Setter for beginPeriodCashFlow.
         * @param  beginPeriodCashFlow  String value for beginPeriodCashFlow.
         * @return Builder
         */
        public Builder beginPeriodCashFlow(String beginPeriodCashFlow) {
            this.beginPeriodCashFlow = beginPeriodCashFlow;
            return this;
        }

        /**
         * Setter for endPeriodCashFlow.
         * @param  endPeriodCashFlow  String value for endPeriodCashFlow.
         * @return Builder
         */
        public Builder endPeriodCashFlow(String endPeriodCashFlow) {
            this.endPeriodCashFlow = endPeriodCashFlow;
            return this;
        }

        /**
         * Setter for totalCashFromOperatingActivities.
         * @param  totalCashFromOperatingActivities  String value for
         *         totalCashFromOperatingActivities.
         * @return Builder
         */
        public Builder totalCashFromOperatingActivities(String totalCashFromOperatingActivities) {
            this.totalCashFromOperatingActivities = totalCashFromOperatingActivities;
            return this;
        }

        /**
         * Setter for depreciation.
         * @param  depreciation  String value for depreciation.
         * @return Builder
         */
        public Builder depreciation(String depreciation) {
            this.depreciation = depreciation;
            return this;
        }

        /**
         * Setter for otherCashflowsFromInvestingActivities.
         * @param  otherCashflowsFromInvestingActivities  String value for
         *         otherCashflowsFromInvestingActivities.
         * @return Builder
         */
        public Builder otherCashflowsFromInvestingActivities(
                String otherCashflowsFromInvestingActivities) {
            this.otherCashflowsFromInvestingActivities = otherCashflowsFromInvestingActivities;
            return this;
        }

        /**
         * Setter for dividendsPaid.
         * @param  dividendsPaid  String value for dividendsPaid.
         * @return Builder
         */
        public Builder dividendsPaid(String dividendsPaid) {
            this.dividendsPaid = dividendsPaid;
            return this;
        }

        /**
         * Setter for changeToInventory.
         * @param  changeToInventory  String value for changeToInventory.
         * @return Builder
         */
        public Builder changeToInventory(String changeToInventory) {
            this.changeToInventory = changeToInventory;
            return this;
        }

        /**
         * Setter for changeToAccountReceivables.
         * @param  changeToAccountReceivables  String value for changeToAccountReceivables.
         * @return Builder
         */
        public Builder changeToAccountReceivables(String changeToAccountReceivables) {
            this.changeToAccountReceivables = changeToAccountReceivables;
            return this;
        }

        /**
         * Setter for salePurchaseOfStock.
         * @param  salePurchaseOfStock  String value for salePurchaseOfStock.
         * @return Builder
         */
        public Builder salePurchaseOfStock(String salePurchaseOfStock) {
            this.salePurchaseOfStock = salePurchaseOfStock;
            return this;
        }

        /**
         * Setter for otherCashflowsFromFinancingActivities.
         * @param  otherCashflowsFromFinancingActivities  String value for
         *         otherCashflowsFromFinancingActivities.
         * @return Builder
         */
        public Builder otherCashflowsFromFinancingActivities(
                String otherCashflowsFromFinancingActivities) {
            this.otherCashflowsFromFinancingActivities = otherCashflowsFromFinancingActivities;
            return this;
        }

        /**
         * Setter for changeToNetincome.
         * @param  changeToNetincome  String value for changeToNetincome.
         * @return Builder
         */
        public Builder changeToNetincome(String changeToNetincome) {
            this.changeToNetincome = changeToNetincome;
            return this;
        }

        /**
         * Setter for capitalExpenditures.
         * @param  capitalExpenditures  String value for capitalExpenditures.
         * @return Builder
         */
        public Builder capitalExpenditures(String capitalExpenditures) {
            this.capitalExpenditures = capitalExpenditures;
            return this;
        }

        /**
         * Setter for changeReceivables.
         * @param  changeReceivables  String value for changeReceivables.
         * @return Builder
         */
        public Builder changeReceivables(String changeReceivables) {
            this.changeReceivables = changeReceivables;
            return this;
        }

        /**
         * Setter for cashFlowsOtherOperating.
         * @param  cashFlowsOtherOperating  String value for cashFlowsOtherOperating.
         * @return Builder
         */
        public Builder cashFlowsOtherOperating(String cashFlowsOtherOperating) {
            this.cashFlowsOtherOperating = cashFlowsOtherOperating;
            return this;
        }

        /**
         * Setter for exchangeRateChanges.
         * @param  exchangeRateChanges  String value for exchangeRateChanges.
         * @return Builder
         */
        public Builder exchangeRateChanges(String exchangeRateChanges) {
            this.exchangeRateChanges = exchangeRateChanges;
            return this;
        }

        /**
         * Setter for cashAndCashEquivalentsChanges.
         * @param  cashAndCashEquivalentsChanges  String value for cashAndCashEquivalentsChanges.
         * @return Builder
         */
        public Builder cashAndCashEquivalentsChanges(String cashAndCashEquivalentsChanges) {
            this.cashAndCashEquivalentsChanges = cashAndCashEquivalentsChanges;
            return this;
        }

        /**
         * Setter for changeInWorkingCapital.
         * @param  changeInWorkingCapital  String value for changeInWorkingCapital.
         * @return Builder
         */
        public Builder changeInWorkingCapital(String changeInWorkingCapital) {
            this.changeInWorkingCapital = changeInWorkingCapital;
            return this;
        }

        /**
         * Setter for otherNonCashItems.
         * @param  otherNonCashItems  String value for otherNonCashItems.
         * @return Builder
         */
        public Builder otherNonCashItems(String otherNonCashItems) {
            this.otherNonCashItems = otherNonCashItems;
            return this;
        }

        /**
         * Setter for freeCashFlow.
         * @param  freeCashFlow  String value for freeCashFlow.
         * @return Builder
         */
        public Builder freeCashFlow(String freeCashFlow) {
            this.freeCashFlow = freeCashFlow;
            return this;
        }

        /**
         * Builds a new {@link GeneratedObject19} object using the set fields.
         * @return {@link GeneratedObject19}
         */
        public GeneratedObject19 build() {
            return new GeneratedObject19(date, filingDate, currencySymbol, investments,
                    changeToLiabilities, totalCashflowsFromInvestingActivities, netBorrowings,
                    totalCashFromFinancingActivities, changeToOperatingActivities, netIncome,
                    changeInCash, beginPeriodCashFlow, endPeriodCashFlow,
                    totalCashFromOperatingActivities, depreciation,
                    otherCashflowsFromInvestingActivities, dividendsPaid, changeToInventory,
                    changeToAccountReceivables, salePurchaseOfStock,
                    otherCashflowsFromFinancingActivities, changeToNetincome, capitalExpenditures,
                    changeReceivables, cashFlowsOtherOperating, exchangeRateChanges,
                    cashAndCashEquivalentsChanges, changeInWorkingCapital, otherNonCashItems,
                    freeCashFlow);
        }
    }
}
