/*
 * EODHistoricalDataFundamentalLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.eodhistoricaldata.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for GeneratedObject17 type.
 */
public class GeneratedObject17 {
    private String date;
    private String filingDate;
    private String currencySymbol;
    private String totalAssets;
    private String intangibleAssets;
    private String earningAssets;
    private String otherCurrentAssets;
    private String totalLiab;
    private String totalStockholderEquity;
    private String deferredLongTermLiab;
    private String otherCurrentLiab;
    private String commonStock;
    private String capitalStock;
    private String retainedEarnings;
    private String otherLiab;
    private String goodWill;
    private String otherAssets;
    private String cash;
    private String cashAndEquivalents;
    private String totalCurrentLiabilities;
    private String netDebt;
    private String shortTermDebt;
    private String shortLongTermDebt;
    private String shortLongTermDebtTotal;
    private String otherStockholderEquity;
    private String propertyPlantEquipment;
    private String totalCurrentAssets;
    private String longTermInvestments;
    private String netTangibleAssets;
    private String shortTermInvestments;
    private String netReceivables;
    private String longTermDebt;
    private String inventory;
    private String accountsPayable;
    private String totalPermanentEquity;
    private String noncontrollingInterestInConsolidatedEntity;
    private String temporaryEquityRedeemableNoncontrollingInterests;
    private String accumulatedOtherComprehensiveIncome;
    private String additionalPaidInCapital;
    private String commonStockTotalEquity;
    private String preferredStockTotalEquity;
    private String retainedEarningsTotalEquity;
    private String treasuryStock;
    private String accumulatedAmortization;
    private String nonCurrrentAssetsOther;
    private String deferredLongTermAssetCharges;
    private String nonCurrentAssetsTotal;
    private String capitalLeaseObligations;
    private String longTermDebtTotal;
    private String nonCurrentLiabilitiesOther;
    private String nonCurrentLiabilitiesTotal;
    private String negativeGoodwill;
    private String warrants;
    private String preferredStockRedeemable;
    private String capitalSurpluse;
    private String liabilitiesAndStockholdersEquity;
    private String cashAndShortTermInvestments;
    private String propertyPlantAndEquipmentGross;
    private String propertyPlantAndEquipmentNet;
    private String accumulatedDepreciation;
    private String netWorkingCapital;
    private String netInvestedCapital;
    private String commonStockSharesOutstanding;

    /**
     * Default constructor.
     */
    public GeneratedObject17() {
    }

    /**
     * Initialization constructor.
     * @param  date  String value for date.
     * @param  filingDate  String value for filingDate.
     * @param  currencySymbol  String value for currencySymbol.
     * @param  totalAssets  String value for totalAssets.
     * @param  intangibleAssets  String value for intangibleAssets.
     * @param  earningAssets  String value for earningAssets.
     * @param  otherCurrentAssets  String value for otherCurrentAssets.
     * @param  totalLiab  String value for totalLiab.
     * @param  totalStockholderEquity  String value for totalStockholderEquity.
     * @param  deferredLongTermLiab  String value for deferredLongTermLiab.
     * @param  otherCurrentLiab  String value for otherCurrentLiab.
     * @param  commonStock  String value for commonStock.
     * @param  capitalStock  String value for capitalStock.
     * @param  retainedEarnings  String value for retainedEarnings.
     * @param  otherLiab  String value for otherLiab.
     * @param  goodWill  String value for goodWill.
     * @param  otherAssets  String value for otherAssets.
     * @param  cash  String value for cash.
     * @param  cashAndEquivalents  String value for cashAndEquivalents.
     * @param  totalCurrentLiabilities  String value for totalCurrentLiabilities.
     * @param  netDebt  String value for netDebt.
     * @param  shortTermDebt  String value for shortTermDebt.
     * @param  shortLongTermDebt  String value for shortLongTermDebt.
     * @param  shortLongTermDebtTotal  String value for shortLongTermDebtTotal.
     * @param  otherStockholderEquity  String value for otherStockholderEquity.
     * @param  propertyPlantEquipment  String value for propertyPlantEquipment.
     * @param  totalCurrentAssets  String value for totalCurrentAssets.
     * @param  longTermInvestments  String value for longTermInvestments.
     * @param  netTangibleAssets  String value for netTangibleAssets.
     * @param  shortTermInvestments  String value for shortTermInvestments.
     * @param  netReceivables  String value for netReceivables.
     * @param  longTermDebt  String value for longTermDebt.
     * @param  inventory  String value for inventory.
     * @param  accountsPayable  String value for accountsPayable.
     * @param  totalPermanentEquity  String value for totalPermanentEquity.
     * @param  noncontrollingInterestInConsolidatedEntity  String value for
     *         noncontrollingInterestInConsolidatedEntity.
     * @param  temporaryEquityRedeemableNoncontrollingInterests  String value for
     *         temporaryEquityRedeemableNoncontrollingInterests.
     * @param  accumulatedOtherComprehensiveIncome  String value for
     *         accumulatedOtherComprehensiveIncome.
     * @param  additionalPaidInCapital  String value for additionalPaidInCapital.
     * @param  commonStockTotalEquity  String value for commonStockTotalEquity.
     * @param  preferredStockTotalEquity  String value for preferredStockTotalEquity.
     * @param  retainedEarningsTotalEquity  String value for retainedEarningsTotalEquity.
     * @param  treasuryStock  String value for treasuryStock.
     * @param  accumulatedAmortization  String value for accumulatedAmortization.
     * @param  nonCurrrentAssetsOther  String value for nonCurrrentAssetsOther.
     * @param  deferredLongTermAssetCharges  String value for deferredLongTermAssetCharges.
     * @param  nonCurrentAssetsTotal  String value for nonCurrentAssetsTotal.
     * @param  capitalLeaseObligations  String value for capitalLeaseObligations.
     * @param  longTermDebtTotal  String value for longTermDebtTotal.
     * @param  nonCurrentLiabilitiesOther  String value for nonCurrentLiabilitiesOther.
     * @param  nonCurrentLiabilitiesTotal  String value for nonCurrentLiabilitiesTotal.
     * @param  negativeGoodwill  String value for negativeGoodwill.
     * @param  warrants  String value for warrants.
     * @param  preferredStockRedeemable  String value for preferredStockRedeemable.
     * @param  capitalSurpluse  String value for capitalSurpluse.
     * @param  liabilitiesAndStockholdersEquity  String value for liabilitiesAndStockholdersEquity.
     * @param  cashAndShortTermInvestments  String value for cashAndShortTermInvestments.
     * @param  propertyPlantAndEquipmentGross  String value for propertyPlantAndEquipmentGross.
     * @param  propertyPlantAndEquipmentNet  String value for propertyPlantAndEquipmentNet.
     * @param  accumulatedDepreciation  String value for accumulatedDepreciation.
     * @param  netWorkingCapital  String value for netWorkingCapital.
     * @param  netInvestedCapital  String value for netInvestedCapital.
     * @param  commonStockSharesOutstanding  String value for commonStockSharesOutstanding.
     */
    public GeneratedObject17(
            String date,
            String filingDate,
            String currencySymbol,
            String totalAssets,
            String intangibleAssets,
            String earningAssets,
            String otherCurrentAssets,
            String totalLiab,
            String totalStockholderEquity,
            String deferredLongTermLiab,
            String otherCurrentLiab,
            String commonStock,
            String capitalStock,
            String retainedEarnings,
            String otherLiab,
            String goodWill,
            String otherAssets,
            String cash,
            String cashAndEquivalents,
            String totalCurrentLiabilities,
            String netDebt,
            String shortTermDebt,
            String shortLongTermDebt,
            String shortLongTermDebtTotal,
            String otherStockholderEquity,
            String propertyPlantEquipment,
            String totalCurrentAssets,
            String longTermInvestments,
            String netTangibleAssets,
            String shortTermInvestments,
            String netReceivables,
            String longTermDebt,
            String inventory,
            String accountsPayable,
            String totalPermanentEquity,
            String noncontrollingInterestInConsolidatedEntity,
            String temporaryEquityRedeemableNoncontrollingInterests,
            String accumulatedOtherComprehensiveIncome,
            String additionalPaidInCapital,
            String commonStockTotalEquity,
            String preferredStockTotalEquity,
            String retainedEarningsTotalEquity,
            String treasuryStock,
            String accumulatedAmortization,
            String nonCurrrentAssetsOther,
            String deferredLongTermAssetCharges,
            String nonCurrentAssetsTotal,
            String capitalLeaseObligations,
            String longTermDebtTotal,
            String nonCurrentLiabilitiesOther,
            String nonCurrentLiabilitiesTotal,
            String negativeGoodwill,
            String warrants,
            String preferredStockRedeemable,
            String capitalSurpluse,
            String liabilitiesAndStockholdersEquity,
            String cashAndShortTermInvestments,
            String propertyPlantAndEquipmentGross,
            String propertyPlantAndEquipmentNet,
            String accumulatedDepreciation,
            String netWorkingCapital,
            String netInvestedCapital,
            String commonStockSharesOutstanding) {
        this.date = date;
        this.filingDate = filingDate;
        this.currencySymbol = currencySymbol;
        this.totalAssets = totalAssets;
        this.intangibleAssets = intangibleAssets;
        this.earningAssets = earningAssets;
        this.otherCurrentAssets = otherCurrentAssets;
        this.totalLiab = totalLiab;
        this.totalStockholderEquity = totalStockholderEquity;
        this.deferredLongTermLiab = deferredLongTermLiab;
        this.otherCurrentLiab = otherCurrentLiab;
        this.commonStock = commonStock;
        this.capitalStock = capitalStock;
        this.retainedEarnings = retainedEarnings;
        this.otherLiab = otherLiab;
        this.goodWill = goodWill;
        this.otherAssets = otherAssets;
        this.cash = cash;
        this.cashAndEquivalents = cashAndEquivalents;
        this.totalCurrentLiabilities = totalCurrentLiabilities;
        this.netDebt = netDebt;
        this.shortTermDebt = shortTermDebt;
        this.shortLongTermDebt = shortLongTermDebt;
        this.shortLongTermDebtTotal = shortLongTermDebtTotal;
        this.otherStockholderEquity = otherStockholderEquity;
        this.propertyPlantEquipment = propertyPlantEquipment;
        this.totalCurrentAssets = totalCurrentAssets;
        this.longTermInvestments = longTermInvestments;
        this.netTangibleAssets = netTangibleAssets;
        this.shortTermInvestments = shortTermInvestments;
        this.netReceivables = netReceivables;
        this.longTermDebt = longTermDebt;
        this.inventory = inventory;
        this.accountsPayable = accountsPayable;
        this.totalPermanentEquity = totalPermanentEquity;
        this.noncontrollingInterestInConsolidatedEntity =
                noncontrollingInterestInConsolidatedEntity;
        this.temporaryEquityRedeemableNoncontrollingInterests =
                temporaryEquityRedeemableNoncontrollingInterests;
        this.accumulatedOtherComprehensiveIncome = accumulatedOtherComprehensiveIncome;
        this.additionalPaidInCapital = additionalPaidInCapital;
        this.commonStockTotalEquity = commonStockTotalEquity;
        this.preferredStockTotalEquity = preferredStockTotalEquity;
        this.retainedEarningsTotalEquity = retainedEarningsTotalEquity;
        this.treasuryStock = treasuryStock;
        this.accumulatedAmortization = accumulatedAmortization;
        this.nonCurrrentAssetsOther = nonCurrrentAssetsOther;
        this.deferredLongTermAssetCharges = deferredLongTermAssetCharges;
        this.nonCurrentAssetsTotal = nonCurrentAssetsTotal;
        this.capitalLeaseObligations = capitalLeaseObligations;
        this.longTermDebtTotal = longTermDebtTotal;
        this.nonCurrentLiabilitiesOther = nonCurrentLiabilitiesOther;
        this.nonCurrentLiabilitiesTotal = nonCurrentLiabilitiesTotal;
        this.negativeGoodwill = negativeGoodwill;
        this.warrants = warrants;
        this.preferredStockRedeemable = preferredStockRedeemable;
        this.capitalSurpluse = capitalSurpluse;
        this.liabilitiesAndStockholdersEquity = liabilitiesAndStockholdersEquity;
        this.cashAndShortTermInvestments = cashAndShortTermInvestments;
        this.propertyPlantAndEquipmentGross = propertyPlantAndEquipmentGross;
        this.propertyPlantAndEquipmentNet = propertyPlantAndEquipmentNet;
        this.accumulatedDepreciation = accumulatedDepreciation;
        this.netWorkingCapital = netWorkingCapital;
        this.netInvestedCapital = netInvestedCapital;
        this.commonStockSharesOutstanding = commonStockSharesOutstanding;
    }

    /**
     * Getter for Date.
     * @return Returns the String
     */
    @JsonGetter("date")
    public String getDate() {
        return date;
    }

    /**
     * Setter for Date.
     * @param date Value for String
     */
    @JsonSetter("date")
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * Getter for FilingDate.
     * @return Returns the String
     */
    @JsonGetter("filing_date")
    public String getFilingDate() {
        return filingDate;
    }

    /**
     * Setter for FilingDate.
     * @param filingDate Value for String
     */
    @JsonSetter("filing_date")
    public void setFilingDate(String filingDate) {
        this.filingDate = filingDate;
    }

    /**
     * Getter for CurrencySymbol.
     * @return Returns the String
     */
    @JsonGetter("currency_symbol")
    public String getCurrencySymbol() {
        return currencySymbol;
    }

    /**
     * Setter for CurrencySymbol.
     * @param currencySymbol Value for String
     */
    @JsonSetter("currency_symbol")
    public void setCurrencySymbol(String currencySymbol) {
        this.currencySymbol = currencySymbol;
    }

    /**
     * Getter for TotalAssets.
     * @return Returns the String
     */
    @JsonGetter("totalAssets")
    public String getTotalAssets() {
        return totalAssets;
    }

    /**
     * Setter for TotalAssets.
     * @param totalAssets Value for String
     */
    @JsonSetter("totalAssets")
    public void setTotalAssets(String totalAssets) {
        this.totalAssets = totalAssets;
    }

    /**
     * Getter for IntangibleAssets.
     * @return Returns the String
     */
    @JsonGetter("intangibleAssets")
    public String getIntangibleAssets() {
        return intangibleAssets;
    }

    /**
     * Setter for IntangibleAssets.
     * @param intangibleAssets Value for String
     */
    @JsonSetter("intangibleAssets")
    public void setIntangibleAssets(String intangibleAssets) {
        this.intangibleAssets = intangibleAssets;
    }

    /**
     * Getter for EarningAssets.
     * @return Returns the String
     */
    @JsonGetter("earningAssets")
    public String getEarningAssets() {
        return earningAssets;
    }

    /**
     * Setter for EarningAssets.
     * @param earningAssets Value for String
     */
    @JsonSetter("earningAssets")
    public void setEarningAssets(String earningAssets) {
        this.earningAssets = earningAssets;
    }

    /**
     * Getter for OtherCurrentAssets.
     * @return Returns the String
     */
    @JsonGetter("otherCurrentAssets")
    public String getOtherCurrentAssets() {
        return otherCurrentAssets;
    }

    /**
     * Setter for OtherCurrentAssets.
     * @param otherCurrentAssets Value for String
     */
    @JsonSetter("otherCurrentAssets")
    public void setOtherCurrentAssets(String otherCurrentAssets) {
        this.otherCurrentAssets = otherCurrentAssets;
    }

    /**
     * Getter for TotalLiab.
     * @return Returns the String
     */
    @JsonGetter("totalLiab")
    public String getTotalLiab() {
        return totalLiab;
    }

    /**
     * Setter for TotalLiab.
     * @param totalLiab Value for String
     */
    @JsonSetter("totalLiab")
    public void setTotalLiab(String totalLiab) {
        this.totalLiab = totalLiab;
    }

    /**
     * Getter for TotalStockholderEquity.
     * @return Returns the String
     */
    @JsonGetter("totalStockholderEquity")
    public String getTotalStockholderEquity() {
        return totalStockholderEquity;
    }

    /**
     * Setter for TotalStockholderEquity.
     * @param totalStockholderEquity Value for String
     */
    @JsonSetter("totalStockholderEquity")
    public void setTotalStockholderEquity(String totalStockholderEquity) {
        this.totalStockholderEquity = totalStockholderEquity;
    }

    /**
     * Getter for DeferredLongTermLiab.
     * @return Returns the String
     */
    @JsonGetter("deferredLongTermLiab")
    public String getDeferredLongTermLiab() {
        return deferredLongTermLiab;
    }

    /**
     * Setter for DeferredLongTermLiab.
     * @param deferredLongTermLiab Value for String
     */
    @JsonSetter("deferredLongTermLiab")
    public void setDeferredLongTermLiab(String deferredLongTermLiab) {
        this.deferredLongTermLiab = deferredLongTermLiab;
    }

    /**
     * Getter for OtherCurrentLiab.
     * @return Returns the String
     */
    @JsonGetter("otherCurrentLiab")
    public String getOtherCurrentLiab() {
        return otherCurrentLiab;
    }

    /**
     * Setter for OtherCurrentLiab.
     * @param otherCurrentLiab Value for String
     */
    @JsonSetter("otherCurrentLiab")
    public void setOtherCurrentLiab(String otherCurrentLiab) {
        this.otherCurrentLiab = otherCurrentLiab;
    }

    /**
     * Getter for CommonStock.
     * @return Returns the String
     */
    @JsonGetter("commonStock")
    public String getCommonStock() {
        return commonStock;
    }

    /**
     * Setter for CommonStock.
     * @param commonStock Value for String
     */
    @JsonSetter("commonStock")
    public void setCommonStock(String commonStock) {
        this.commonStock = commonStock;
    }

    /**
     * Getter for CapitalStock.
     * @return Returns the String
     */
    @JsonGetter("capitalStock")
    public String getCapitalStock() {
        return capitalStock;
    }

    /**
     * Setter for CapitalStock.
     * @param capitalStock Value for String
     */
    @JsonSetter("capitalStock")
    public void setCapitalStock(String capitalStock) {
        this.capitalStock = capitalStock;
    }

    /**
     * Getter for RetainedEarnings.
     * @return Returns the String
     */
    @JsonGetter("retainedEarnings")
    public String getRetainedEarnings() {
        return retainedEarnings;
    }

    /**
     * Setter for RetainedEarnings.
     * @param retainedEarnings Value for String
     */
    @JsonSetter("retainedEarnings")
    public void setRetainedEarnings(String retainedEarnings) {
        this.retainedEarnings = retainedEarnings;
    }

    /**
     * Getter for OtherLiab.
     * @return Returns the String
     */
    @JsonGetter("otherLiab")
    public String getOtherLiab() {
        return otherLiab;
    }

    /**
     * Setter for OtherLiab.
     * @param otherLiab Value for String
     */
    @JsonSetter("otherLiab")
    public void setOtherLiab(String otherLiab) {
        this.otherLiab = otherLiab;
    }

    /**
     * Getter for GoodWill.
     * @return Returns the String
     */
    @JsonGetter("goodWill")
    public String getGoodWill() {
        return goodWill;
    }

    /**
     * Setter for GoodWill.
     * @param goodWill Value for String
     */
    @JsonSetter("goodWill")
    public void setGoodWill(String goodWill) {
        this.goodWill = goodWill;
    }

    /**
     * Getter for OtherAssets.
     * @return Returns the String
     */
    @JsonGetter("otherAssets")
    public String getOtherAssets() {
        return otherAssets;
    }

    /**
     * Setter for OtherAssets.
     * @param otherAssets Value for String
     */
    @JsonSetter("otherAssets")
    public void setOtherAssets(String otherAssets) {
        this.otherAssets = otherAssets;
    }

    /**
     * Getter for Cash.
     * @return Returns the String
     */
    @JsonGetter("cash")
    public String getCash() {
        return cash;
    }

    /**
     * Setter for Cash.
     * @param cash Value for String
     */
    @JsonSetter("cash")
    public void setCash(String cash) {
        this.cash = cash;
    }

    /**
     * Getter for CashAndEquivalents.
     * @return Returns the String
     */
    @JsonGetter("cashAndEquivalents")
    public String getCashAndEquivalents() {
        return cashAndEquivalents;
    }

    /**
     * Setter for CashAndEquivalents.
     * @param cashAndEquivalents Value for String
     */
    @JsonSetter("cashAndEquivalents")
    public void setCashAndEquivalents(String cashAndEquivalents) {
        this.cashAndEquivalents = cashAndEquivalents;
    }

    /**
     * Getter for TotalCurrentLiabilities.
     * @return Returns the String
     */
    @JsonGetter("totalCurrentLiabilities")
    public String getTotalCurrentLiabilities() {
        return totalCurrentLiabilities;
    }

    /**
     * Setter for TotalCurrentLiabilities.
     * @param totalCurrentLiabilities Value for String
     */
    @JsonSetter("totalCurrentLiabilities")
    public void setTotalCurrentLiabilities(String totalCurrentLiabilities) {
        this.totalCurrentLiabilities = totalCurrentLiabilities;
    }

    /**
     * Getter for NetDebt.
     * @return Returns the String
     */
    @JsonGetter("netDebt")
    public String getNetDebt() {
        return netDebt;
    }

    /**
     * Setter for NetDebt.
     * @param netDebt Value for String
     */
    @JsonSetter("netDebt")
    public void setNetDebt(String netDebt) {
        this.netDebt = netDebt;
    }

    /**
     * Getter for ShortTermDebt.
     * @return Returns the String
     */
    @JsonGetter("shortTermDebt")
    public String getShortTermDebt() {
        return shortTermDebt;
    }

    /**
     * Setter for ShortTermDebt.
     * @param shortTermDebt Value for String
     */
    @JsonSetter("shortTermDebt")
    public void setShortTermDebt(String shortTermDebt) {
        this.shortTermDebt = shortTermDebt;
    }

    /**
     * Getter for ShortLongTermDebt.
     * @return Returns the String
     */
    @JsonGetter("shortLongTermDebt")
    public String getShortLongTermDebt() {
        return shortLongTermDebt;
    }

    /**
     * Setter for ShortLongTermDebt.
     * @param shortLongTermDebt Value for String
     */
    @JsonSetter("shortLongTermDebt")
    public void setShortLongTermDebt(String shortLongTermDebt) {
        this.shortLongTermDebt = shortLongTermDebt;
    }

    /**
     * Getter for ShortLongTermDebtTotal.
     * @return Returns the String
     */
    @JsonGetter("shortLongTermDebtTotal")
    public String getShortLongTermDebtTotal() {
        return shortLongTermDebtTotal;
    }

    /**
     * Setter for ShortLongTermDebtTotal.
     * @param shortLongTermDebtTotal Value for String
     */
    @JsonSetter("shortLongTermDebtTotal")
    public void setShortLongTermDebtTotal(String shortLongTermDebtTotal) {
        this.shortLongTermDebtTotal = shortLongTermDebtTotal;
    }

    /**
     * Getter for OtherStockholderEquity.
     * @return Returns the String
     */
    @JsonGetter("otherStockholderEquity")
    public String getOtherStockholderEquity() {
        return otherStockholderEquity;
    }

    /**
     * Setter for OtherStockholderEquity.
     * @param otherStockholderEquity Value for String
     */
    @JsonSetter("otherStockholderEquity")
    public void setOtherStockholderEquity(String otherStockholderEquity) {
        this.otherStockholderEquity = otherStockholderEquity;
    }

    /**
     * Getter for PropertyPlantEquipment.
     * @return Returns the String
     */
    @JsonGetter("propertyPlantEquipment")
    public String getPropertyPlantEquipment() {
        return propertyPlantEquipment;
    }

    /**
     * Setter for PropertyPlantEquipment.
     * @param propertyPlantEquipment Value for String
     */
    @JsonSetter("propertyPlantEquipment")
    public void setPropertyPlantEquipment(String propertyPlantEquipment) {
        this.propertyPlantEquipment = propertyPlantEquipment;
    }

    /**
     * Getter for TotalCurrentAssets.
     * @return Returns the String
     */
    @JsonGetter("totalCurrentAssets")
    public String getTotalCurrentAssets() {
        return totalCurrentAssets;
    }

    /**
     * Setter for TotalCurrentAssets.
     * @param totalCurrentAssets Value for String
     */
    @JsonSetter("totalCurrentAssets")
    public void setTotalCurrentAssets(String totalCurrentAssets) {
        this.totalCurrentAssets = totalCurrentAssets;
    }

    /**
     * Getter for LongTermInvestments.
     * @return Returns the String
     */
    @JsonGetter("longTermInvestments")
    public String getLongTermInvestments() {
        return longTermInvestments;
    }

    /**
     * Setter for LongTermInvestments.
     * @param longTermInvestments Value for String
     */
    @JsonSetter("longTermInvestments")
    public void setLongTermInvestments(String longTermInvestments) {
        this.longTermInvestments = longTermInvestments;
    }

    /**
     * Getter for NetTangibleAssets.
     * @return Returns the String
     */
    @JsonGetter("netTangibleAssets")
    public String getNetTangibleAssets() {
        return netTangibleAssets;
    }

    /**
     * Setter for NetTangibleAssets.
     * @param netTangibleAssets Value for String
     */
    @JsonSetter("netTangibleAssets")
    public void setNetTangibleAssets(String netTangibleAssets) {
        this.netTangibleAssets = netTangibleAssets;
    }

    /**
     * Getter for ShortTermInvestments.
     * @return Returns the String
     */
    @JsonGetter("shortTermInvestments")
    public String getShortTermInvestments() {
        return shortTermInvestments;
    }

    /**
     * Setter for ShortTermInvestments.
     * @param shortTermInvestments Value for String
     */
    @JsonSetter("shortTermInvestments")
    public void setShortTermInvestments(String shortTermInvestments) {
        this.shortTermInvestments = shortTermInvestments;
    }

    /**
     * Getter for NetReceivables.
     * @return Returns the String
     */
    @JsonGetter("netReceivables")
    public String getNetReceivables() {
        return netReceivables;
    }

    /**
     * Setter for NetReceivables.
     * @param netReceivables Value for String
     */
    @JsonSetter("netReceivables")
    public void setNetReceivables(String netReceivables) {
        this.netReceivables = netReceivables;
    }

    /**
     * Getter for LongTermDebt.
     * @return Returns the String
     */
    @JsonGetter("longTermDebt")
    public String getLongTermDebt() {
        return longTermDebt;
    }

    /**
     * Setter for LongTermDebt.
     * @param longTermDebt Value for String
     */
    @JsonSetter("longTermDebt")
    public void setLongTermDebt(String longTermDebt) {
        this.longTermDebt = longTermDebt;
    }

    /**
     * Getter for Inventory.
     * @return Returns the String
     */
    @JsonGetter("inventory")
    public String getInventory() {
        return inventory;
    }

    /**
     * Setter for Inventory.
     * @param inventory Value for String
     */
    @JsonSetter("inventory")
    public void setInventory(String inventory) {
        this.inventory = inventory;
    }

    /**
     * Getter for AccountsPayable.
     * @return Returns the String
     */
    @JsonGetter("accountsPayable")
    public String getAccountsPayable() {
        return accountsPayable;
    }

    /**
     * Setter for AccountsPayable.
     * @param accountsPayable Value for String
     */
    @JsonSetter("accountsPayable")
    public void setAccountsPayable(String accountsPayable) {
        this.accountsPayable = accountsPayable;
    }

    /**
     * Getter for TotalPermanentEquity.
     * @return Returns the String
     */
    @JsonGetter("totalPermanentEquity")
    public String getTotalPermanentEquity() {
        return totalPermanentEquity;
    }

    /**
     * Setter for TotalPermanentEquity.
     * @param totalPermanentEquity Value for String
     */
    @JsonSetter("totalPermanentEquity")
    public void setTotalPermanentEquity(String totalPermanentEquity) {
        this.totalPermanentEquity = totalPermanentEquity;
    }

    /**
     * Getter for NoncontrollingInterestInConsolidatedEntity.
     * @return Returns the String
     */
    @JsonGetter("noncontrollingInterestInConsolidatedEntity")
    public String getNoncontrollingInterestInConsolidatedEntity() {
        return noncontrollingInterestInConsolidatedEntity;
    }

    /**
     * Setter for NoncontrollingInterestInConsolidatedEntity.
     * @param noncontrollingInterestInConsolidatedEntity Value for String
     */
    @JsonSetter("noncontrollingInterestInConsolidatedEntity")
    public void setNoncontrollingInterestInConsolidatedEntity(String noncontrollingInterestInConsolidatedEntity) {
        this.noncontrollingInterestInConsolidatedEntity = noncontrollingInterestInConsolidatedEntity;
    }

    /**
     * Getter for TemporaryEquityRedeemableNoncontrollingInterests.
     * @return Returns the String
     */
    @JsonGetter("temporaryEquityRedeemableNoncontrollingInterests")
    public String getTemporaryEquityRedeemableNoncontrollingInterests() {
        return temporaryEquityRedeemableNoncontrollingInterests;
    }

    /**
     * Setter for TemporaryEquityRedeemableNoncontrollingInterests.
     * @param temporaryEquityRedeemableNoncontrollingInterests Value for String
     */
    @JsonSetter("temporaryEquityRedeemableNoncontrollingInterests")
    public void setTemporaryEquityRedeemableNoncontrollingInterests(String temporaryEquityRedeemableNoncontrollingInterests) {
        this.temporaryEquityRedeemableNoncontrollingInterests = temporaryEquityRedeemableNoncontrollingInterests;
    }

    /**
     * Getter for AccumulatedOtherComprehensiveIncome.
     * @return Returns the String
     */
    @JsonGetter("accumulatedOtherComprehensiveIncome")
    public String getAccumulatedOtherComprehensiveIncome() {
        return accumulatedOtherComprehensiveIncome;
    }

    /**
     * Setter for AccumulatedOtherComprehensiveIncome.
     * @param accumulatedOtherComprehensiveIncome Value for String
     */
    @JsonSetter("accumulatedOtherComprehensiveIncome")
    public void setAccumulatedOtherComprehensiveIncome(String accumulatedOtherComprehensiveIncome) {
        this.accumulatedOtherComprehensiveIncome = accumulatedOtherComprehensiveIncome;
    }

    /**
     * Getter for AdditionalPaidInCapital.
     * @return Returns the String
     */
    @JsonGetter("additionalPaidInCapital")
    public String getAdditionalPaidInCapital() {
        return additionalPaidInCapital;
    }

    /**
     * Setter for AdditionalPaidInCapital.
     * @param additionalPaidInCapital Value for String
     */
    @JsonSetter("additionalPaidInCapital")
    public void setAdditionalPaidInCapital(String additionalPaidInCapital) {
        this.additionalPaidInCapital = additionalPaidInCapital;
    }

    /**
     * Getter for CommonStockTotalEquity.
     * @return Returns the String
     */
    @JsonGetter("commonStockTotalEquity")
    public String getCommonStockTotalEquity() {
        return commonStockTotalEquity;
    }

    /**
     * Setter for CommonStockTotalEquity.
     * @param commonStockTotalEquity Value for String
     */
    @JsonSetter("commonStockTotalEquity")
    public void setCommonStockTotalEquity(String commonStockTotalEquity) {
        this.commonStockTotalEquity = commonStockTotalEquity;
    }

    /**
     * Getter for PreferredStockTotalEquity.
     * @return Returns the String
     */
    @JsonGetter("preferredStockTotalEquity")
    public String getPreferredStockTotalEquity() {
        return preferredStockTotalEquity;
    }

    /**
     * Setter for PreferredStockTotalEquity.
     * @param preferredStockTotalEquity Value for String
     */
    @JsonSetter("preferredStockTotalEquity")
    public void setPreferredStockTotalEquity(String preferredStockTotalEquity) {
        this.preferredStockTotalEquity = preferredStockTotalEquity;
    }

    /**
     * Getter for RetainedEarningsTotalEquity.
     * @return Returns the String
     */
    @JsonGetter("retainedEarningsTotalEquity")
    public String getRetainedEarningsTotalEquity() {
        return retainedEarningsTotalEquity;
    }

    /**
     * Setter for RetainedEarningsTotalEquity.
     * @param retainedEarningsTotalEquity Value for String
     */
    @JsonSetter("retainedEarningsTotalEquity")
    public void setRetainedEarningsTotalEquity(String retainedEarningsTotalEquity) {
        this.retainedEarningsTotalEquity = retainedEarningsTotalEquity;
    }

    /**
     * Getter for TreasuryStock.
     * @return Returns the String
     */
    @JsonGetter("treasuryStock")
    public String getTreasuryStock() {
        return treasuryStock;
    }

    /**
     * Setter for TreasuryStock.
     * @param treasuryStock Value for String
     */
    @JsonSetter("treasuryStock")
    public void setTreasuryStock(String treasuryStock) {
        this.treasuryStock = treasuryStock;
    }

    /**
     * Getter for AccumulatedAmortization.
     * @return Returns the String
     */
    @JsonGetter("accumulatedAmortization")
    public String getAccumulatedAmortization() {
        return accumulatedAmortization;
    }

    /**
     * Setter for AccumulatedAmortization.
     * @param accumulatedAmortization Value for String
     */
    @JsonSetter("accumulatedAmortization")
    public void setAccumulatedAmortization(String accumulatedAmortization) {
        this.accumulatedAmortization = accumulatedAmortization;
    }

    /**
     * Getter for NonCurrrentAssetsOther.
     * @return Returns the String
     */
    @JsonGetter("nonCurrrentAssetsOther")
    public String getNonCurrrentAssetsOther() {
        return nonCurrrentAssetsOther;
    }

    /**
     * Setter for NonCurrrentAssetsOther.
     * @param nonCurrrentAssetsOther Value for String
     */
    @JsonSetter("nonCurrrentAssetsOther")
    public void setNonCurrrentAssetsOther(String nonCurrrentAssetsOther) {
        this.nonCurrrentAssetsOther = nonCurrrentAssetsOther;
    }

    /**
     * Getter for DeferredLongTermAssetCharges.
     * @return Returns the String
     */
    @JsonGetter("deferredLongTermAssetCharges")
    public String getDeferredLongTermAssetCharges() {
        return deferredLongTermAssetCharges;
    }

    /**
     * Setter for DeferredLongTermAssetCharges.
     * @param deferredLongTermAssetCharges Value for String
     */
    @JsonSetter("deferredLongTermAssetCharges")
    public void setDeferredLongTermAssetCharges(String deferredLongTermAssetCharges) {
        this.deferredLongTermAssetCharges = deferredLongTermAssetCharges;
    }

    /**
     * Getter for NonCurrentAssetsTotal.
     * @return Returns the String
     */
    @JsonGetter("nonCurrentAssetsTotal")
    public String getNonCurrentAssetsTotal() {
        return nonCurrentAssetsTotal;
    }

    /**
     * Setter for NonCurrentAssetsTotal.
     * @param nonCurrentAssetsTotal Value for String
     */
    @JsonSetter("nonCurrentAssetsTotal")
    public void setNonCurrentAssetsTotal(String nonCurrentAssetsTotal) {
        this.nonCurrentAssetsTotal = nonCurrentAssetsTotal;
    }

    /**
     * Getter for CapitalLeaseObligations.
     * @return Returns the String
     */
    @JsonGetter("capitalLeaseObligations")
    public String getCapitalLeaseObligations() {
        return capitalLeaseObligations;
    }

    /**
     * Setter for CapitalLeaseObligations.
     * @param capitalLeaseObligations Value for String
     */
    @JsonSetter("capitalLeaseObligations")
    public void setCapitalLeaseObligations(String capitalLeaseObligations) {
        this.capitalLeaseObligations = capitalLeaseObligations;
    }

    /**
     * Getter for LongTermDebtTotal.
     * @return Returns the String
     */
    @JsonGetter("longTermDebtTotal")
    public String getLongTermDebtTotal() {
        return longTermDebtTotal;
    }

    /**
     * Setter for LongTermDebtTotal.
     * @param longTermDebtTotal Value for String
     */
    @JsonSetter("longTermDebtTotal")
    public void setLongTermDebtTotal(String longTermDebtTotal) {
        this.longTermDebtTotal = longTermDebtTotal;
    }

    /**
     * Getter for NonCurrentLiabilitiesOther.
     * @return Returns the String
     */
    @JsonGetter("nonCurrentLiabilitiesOther")
    public String getNonCurrentLiabilitiesOther() {
        return nonCurrentLiabilitiesOther;
    }

    /**
     * Setter for NonCurrentLiabilitiesOther.
     * @param nonCurrentLiabilitiesOther Value for String
     */
    @JsonSetter("nonCurrentLiabilitiesOther")
    public void setNonCurrentLiabilitiesOther(String nonCurrentLiabilitiesOther) {
        this.nonCurrentLiabilitiesOther = nonCurrentLiabilitiesOther;
    }

    /**
     * Getter for NonCurrentLiabilitiesTotal.
     * @return Returns the String
     */
    @JsonGetter("nonCurrentLiabilitiesTotal")
    public String getNonCurrentLiabilitiesTotal() {
        return nonCurrentLiabilitiesTotal;
    }

    /**
     * Setter for NonCurrentLiabilitiesTotal.
     * @param nonCurrentLiabilitiesTotal Value for String
     */
    @JsonSetter("nonCurrentLiabilitiesTotal")
    public void setNonCurrentLiabilitiesTotal(String nonCurrentLiabilitiesTotal) {
        this.nonCurrentLiabilitiesTotal = nonCurrentLiabilitiesTotal;
    }

    /**
     * Getter for NegativeGoodwill.
     * @return Returns the String
     */
    @JsonGetter("negativeGoodwill")
    public String getNegativeGoodwill() {
        return negativeGoodwill;
    }

    /**
     * Setter for NegativeGoodwill.
     * @param negativeGoodwill Value for String
     */
    @JsonSetter("negativeGoodwill")
    public void setNegativeGoodwill(String negativeGoodwill) {
        this.negativeGoodwill = negativeGoodwill;
    }

    /**
     * Getter for Warrants.
     * @return Returns the String
     */
    @JsonGetter("warrants")
    public String getWarrants() {
        return warrants;
    }

    /**
     * Setter for Warrants.
     * @param warrants Value for String
     */
    @JsonSetter("warrants")
    public void setWarrants(String warrants) {
        this.warrants = warrants;
    }

    /**
     * Getter for PreferredStockRedeemable.
     * @return Returns the String
     */
    @JsonGetter("preferredStockRedeemable")
    public String getPreferredStockRedeemable() {
        return preferredStockRedeemable;
    }

    /**
     * Setter for PreferredStockRedeemable.
     * @param preferredStockRedeemable Value for String
     */
    @JsonSetter("preferredStockRedeemable")
    public void setPreferredStockRedeemable(String preferredStockRedeemable) {
        this.preferredStockRedeemable = preferredStockRedeemable;
    }

    /**
     * Getter for CapitalSurpluse.
     * @return Returns the String
     */
    @JsonGetter("capitalSurpluse")
    public String getCapitalSurpluse() {
        return capitalSurpluse;
    }

    /**
     * Setter for CapitalSurpluse.
     * @param capitalSurpluse Value for String
     */
    @JsonSetter("capitalSurpluse")
    public void setCapitalSurpluse(String capitalSurpluse) {
        this.capitalSurpluse = capitalSurpluse;
    }

    /**
     * Getter for LiabilitiesAndStockholdersEquity.
     * @return Returns the String
     */
    @JsonGetter("liabilitiesAndStockholdersEquity")
    public String getLiabilitiesAndStockholdersEquity() {
        return liabilitiesAndStockholdersEquity;
    }

    /**
     * Setter for LiabilitiesAndStockholdersEquity.
     * @param liabilitiesAndStockholdersEquity Value for String
     */
    @JsonSetter("liabilitiesAndStockholdersEquity")
    public void setLiabilitiesAndStockholdersEquity(String liabilitiesAndStockholdersEquity) {
        this.liabilitiesAndStockholdersEquity = liabilitiesAndStockholdersEquity;
    }

    /**
     * Getter for CashAndShortTermInvestments.
     * @return Returns the String
     */
    @JsonGetter("cashAndShortTermInvestments")
    public String getCashAndShortTermInvestments() {
        return cashAndShortTermInvestments;
    }

    /**
     * Setter for CashAndShortTermInvestments.
     * @param cashAndShortTermInvestments Value for String
     */
    @JsonSetter("cashAndShortTermInvestments")
    public void setCashAndShortTermInvestments(String cashAndShortTermInvestments) {
        this.cashAndShortTermInvestments = cashAndShortTermInvestments;
    }

    /**
     * Getter for PropertyPlantAndEquipmentGross.
     * @return Returns the String
     */
    @JsonGetter("propertyPlantAndEquipmentGross")
    public String getPropertyPlantAndEquipmentGross() {
        return propertyPlantAndEquipmentGross;
    }

    /**
     * Setter for PropertyPlantAndEquipmentGross.
     * @param propertyPlantAndEquipmentGross Value for String
     */
    @JsonSetter("propertyPlantAndEquipmentGross")
    public void setPropertyPlantAndEquipmentGross(String propertyPlantAndEquipmentGross) {
        this.propertyPlantAndEquipmentGross = propertyPlantAndEquipmentGross;
    }

    /**
     * Getter for PropertyPlantAndEquipmentNet.
     * @return Returns the String
     */
    @JsonGetter("propertyPlantAndEquipmentNet")
    public String getPropertyPlantAndEquipmentNet() {
        return propertyPlantAndEquipmentNet;
    }

    /**
     * Setter for PropertyPlantAndEquipmentNet.
     * @param propertyPlantAndEquipmentNet Value for String
     */
    @JsonSetter("propertyPlantAndEquipmentNet")
    public void setPropertyPlantAndEquipmentNet(String propertyPlantAndEquipmentNet) {
        this.propertyPlantAndEquipmentNet = propertyPlantAndEquipmentNet;
    }

    /**
     * Getter for AccumulatedDepreciation.
     * @return Returns the String
     */
    @JsonGetter("accumulatedDepreciation")
    public String getAccumulatedDepreciation() {
        return accumulatedDepreciation;
    }

    /**
     * Setter for AccumulatedDepreciation.
     * @param accumulatedDepreciation Value for String
     */
    @JsonSetter("accumulatedDepreciation")
    public void setAccumulatedDepreciation(String accumulatedDepreciation) {
        this.accumulatedDepreciation = accumulatedDepreciation;
    }

    /**
     * Getter for NetWorkingCapital.
     * @return Returns the String
     */
    @JsonGetter("netWorkingCapital")
    public String getNetWorkingCapital() {
        return netWorkingCapital;
    }

    /**
     * Setter for NetWorkingCapital.
     * @param netWorkingCapital Value for String
     */
    @JsonSetter("netWorkingCapital")
    public void setNetWorkingCapital(String netWorkingCapital) {
        this.netWorkingCapital = netWorkingCapital;
    }

    /**
     * Getter for NetInvestedCapital.
     * @return Returns the String
     */
    @JsonGetter("netInvestedCapital")
    public String getNetInvestedCapital() {
        return netInvestedCapital;
    }

    /**
     * Setter for NetInvestedCapital.
     * @param netInvestedCapital Value for String
     */
    @JsonSetter("netInvestedCapital")
    public void setNetInvestedCapital(String netInvestedCapital) {
        this.netInvestedCapital = netInvestedCapital;
    }

    /**
     * Getter for CommonStockSharesOutstanding.
     * @return Returns the String
     */
    @JsonGetter("commonStockSharesOutstanding")
    public String getCommonStockSharesOutstanding() {
        return commonStockSharesOutstanding;
    }

    /**
     * Setter for CommonStockSharesOutstanding.
     * @param commonStockSharesOutstanding Value for String
     */
    @JsonSetter("commonStockSharesOutstanding")
    public void setCommonStockSharesOutstanding(String commonStockSharesOutstanding) {
        this.commonStockSharesOutstanding = commonStockSharesOutstanding;
    }

    /**
     * Converts this GeneratedObject17 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GeneratedObject17 [" + "date=" + date + ", filingDate=" + filingDate
                + ", currencySymbol=" + currencySymbol + ", totalAssets=" + totalAssets
                + ", intangibleAssets=" + intangibleAssets + ", earningAssets=" + earningAssets
                + ", otherCurrentAssets=" + otherCurrentAssets + ", totalLiab=" + totalLiab
                + ", totalStockholderEquity=" + totalStockholderEquity + ", deferredLongTermLiab="
                + deferredLongTermLiab + ", otherCurrentLiab=" + otherCurrentLiab + ", commonStock="
                + commonStock + ", capitalStock=" + capitalStock + ", retainedEarnings="
                + retainedEarnings + ", otherLiab=" + otherLiab + ", goodWill=" + goodWill
                + ", otherAssets=" + otherAssets + ", cash=" + cash + ", cashAndEquivalents="
                + cashAndEquivalents + ", totalCurrentLiabilities=" + totalCurrentLiabilities
                + ", netDebt=" + netDebt + ", shortTermDebt=" + shortTermDebt
                + ", shortLongTermDebt=" + shortLongTermDebt + ", shortLongTermDebtTotal="
                + shortLongTermDebtTotal + ", otherStockholderEquity=" + otherStockholderEquity
                + ", propertyPlantEquipment=" + propertyPlantEquipment + ", totalCurrentAssets="
                + totalCurrentAssets + ", longTermInvestments=" + longTermInvestments
                + ", netTangibleAssets=" + netTangibleAssets + ", shortTermInvestments="
                + shortTermInvestments + ", netReceivables=" + netReceivables + ", longTermDebt="
                + longTermDebt + ", inventory=" + inventory + ", accountsPayable=" + accountsPayable
                + ", totalPermanentEquity=" + totalPermanentEquity
                + ", noncontrollingInterestInConsolidatedEntity="
                + noncontrollingInterestInConsolidatedEntity
                + ", temporaryEquityRedeemableNoncontrollingInterests="
                + temporaryEquityRedeemableNoncontrollingInterests
                + ", accumulatedOtherComprehensiveIncome=" + accumulatedOtherComprehensiveIncome
                + ", additionalPaidInCapital=" + additionalPaidInCapital
                + ", commonStockTotalEquity=" + commonStockTotalEquity
                + ", preferredStockTotalEquity=" + preferredStockTotalEquity
                + ", retainedEarningsTotalEquity=" + retainedEarningsTotalEquity
                + ", treasuryStock=" + treasuryStock + ", accumulatedAmortization="
                + accumulatedAmortization + ", nonCurrrentAssetsOther=" + nonCurrrentAssetsOther
                + ", deferredLongTermAssetCharges=" + deferredLongTermAssetCharges
                + ", nonCurrentAssetsTotal=" + nonCurrentAssetsTotal + ", capitalLeaseObligations="
                + capitalLeaseObligations + ", longTermDebtTotal=" + longTermDebtTotal
                + ", nonCurrentLiabilitiesOther=" + nonCurrentLiabilitiesOther
                + ", nonCurrentLiabilitiesTotal=" + nonCurrentLiabilitiesTotal
                + ", negativeGoodwill=" + negativeGoodwill + ", warrants=" + warrants
                + ", preferredStockRedeemable=" + preferredStockRedeemable + ", capitalSurpluse="
                + capitalSurpluse + ", liabilitiesAndStockholdersEquity="
                + liabilitiesAndStockholdersEquity + ", cashAndShortTermInvestments="
                + cashAndShortTermInvestments + ", propertyPlantAndEquipmentGross="
                + propertyPlantAndEquipmentGross + ", propertyPlantAndEquipmentNet="
                + propertyPlantAndEquipmentNet + ", accumulatedDepreciation="
                + accumulatedDepreciation + ", netWorkingCapital=" + netWorkingCapital
                + ", netInvestedCapital=" + netInvestedCapital + ", commonStockSharesOutstanding="
                + commonStockSharesOutstanding + "]";
    }

    /**
     * Builds a new {@link GeneratedObject17.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GeneratedObject17.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(date, filingDate, currencySymbol, totalAssets,
                intangibleAssets, earningAssets, otherCurrentAssets, totalLiab,
                totalStockholderEquity, deferredLongTermLiab, otherCurrentLiab, commonStock,
                capitalStock, retainedEarnings, otherLiab, goodWill, otherAssets, cash,
                cashAndEquivalents, totalCurrentLiabilities, netDebt, shortTermDebt,
                shortLongTermDebt, shortLongTermDebtTotal, otherStockholderEquity,
                propertyPlantEquipment, totalCurrentAssets, longTermInvestments, netTangibleAssets,
                shortTermInvestments, netReceivables, longTermDebt, inventory, accountsPayable,
                totalPermanentEquity, noncontrollingInterestInConsolidatedEntity,
                temporaryEquityRedeemableNoncontrollingInterests,
                accumulatedOtherComprehensiveIncome, additionalPaidInCapital,
                commonStockTotalEquity, preferredStockTotalEquity, retainedEarningsTotalEquity,
                treasuryStock, accumulatedAmortization, nonCurrrentAssetsOther,
                deferredLongTermAssetCharges, nonCurrentAssetsTotal, capitalLeaseObligations,
                longTermDebtTotal, nonCurrentLiabilitiesOther, nonCurrentLiabilitiesTotal,
                negativeGoodwill, warrants, preferredStockRedeemable, capitalSurpluse,
                liabilitiesAndStockholdersEquity, cashAndShortTermInvestments,
                propertyPlantAndEquipmentGross, propertyPlantAndEquipmentNet,
                accumulatedDepreciation, netWorkingCapital, netInvestedCapital,
                commonStockSharesOutstanding);
        return builder;
    }

    /**
     * Class to build instances of {@link GeneratedObject17}.
     */
    public static class Builder {
        private String date;
        private String filingDate;
        private String currencySymbol;
        private String totalAssets;
        private String intangibleAssets;
        private String earningAssets;
        private String otherCurrentAssets;
        private String totalLiab;
        private String totalStockholderEquity;
        private String deferredLongTermLiab;
        private String otherCurrentLiab;
        private String commonStock;
        private String capitalStock;
        private String retainedEarnings;
        private String otherLiab;
        private String goodWill;
        private String otherAssets;
        private String cash;
        private String cashAndEquivalents;
        private String totalCurrentLiabilities;
        private String netDebt;
        private String shortTermDebt;
        private String shortLongTermDebt;
        private String shortLongTermDebtTotal;
        private String otherStockholderEquity;
        private String propertyPlantEquipment;
        private String totalCurrentAssets;
        private String longTermInvestments;
        private String netTangibleAssets;
        private String shortTermInvestments;
        private String netReceivables;
        private String longTermDebt;
        private String inventory;
        private String accountsPayable;
        private String totalPermanentEquity;
        private String noncontrollingInterestInConsolidatedEntity;
        private String temporaryEquityRedeemableNoncontrollingInterests;
        private String accumulatedOtherComprehensiveIncome;
        private String additionalPaidInCapital;
        private String commonStockTotalEquity;
        private String preferredStockTotalEquity;
        private String retainedEarningsTotalEquity;
        private String treasuryStock;
        private String accumulatedAmortization;
        private String nonCurrrentAssetsOther;
        private String deferredLongTermAssetCharges;
        private String nonCurrentAssetsTotal;
        private String capitalLeaseObligations;
        private String longTermDebtTotal;
        private String nonCurrentLiabilitiesOther;
        private String nonCurrentLiabilitiesTotal;
        private String negativeGoodwill;
        private String warrants;
        private String preferredStockRedeemable;
        private String capitalSurpluse;
        private String liabilitiesAndStockholdersEquity;
        private String cashAndShortTermInvestments;
        private String propertyPlantAndEquipmentGross;
        private String propertyPlantAndEquipmentNet;
        private String accumulatedDepreciation;
        private String netWorkingCapital;
        private String netInvestedCapital;
        private String commonStockSharesOutstanding;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  date  String value for date.
         * @param  filingDate  String value for filingDate.
         * @param  currencySymbol  String value for currencySymbol.
         * @param  totalAssets  String value for totalAssets.
         * @param  intangibleAssets  String value for intangibleAssets.
         * @param  earningAssets  String value for earningAssets.
         * @param  otherCurrentAssets  String value for otherCurrentAssets.
         * @param  totalLiab  String value for totalLiab.
         * @param  totalStockholderEquity  String value for totalStockholderEquity.
         * @param  deferredLongTermLiab  String value for deferredLongTermLiab.
         * @param  otherCurrentLiab  String value for otherCurrentLiab.
         * @param  commonStock  String value for commonStock.
         * @param  capitalStock  String value for capitalStock.
         * @param  retainedEarnings  String value for retainedEarnings.
         * @param  otherLiab  String value for otherLiab.
         * @param  goodWill  String value for goodWill.
         * @param  otherAssets  String value for otherAssets.
         * @param  cash  String value for cash.
         * @param  cashAndEquivalents  String value for cashAndEquivalents.
         * @param  totalCurrentLiabilities  String value for totalCurrentLiabilities.
         * @param  netDebt  String value for netDebt.
         * @param  shortTermDebt  String value for shortTermDebt.
         * @param  shortLongTermDebt  String value for shortLongTermDebt.
         * @param  shortLongTermDebtTotal  String value for shortLongTermDebtTotal.
         * @param  otherStockholderEquity  String value for otherStockholderEquity.
         * @param  propertyPlantEquipment  String value for propertyPlantEquipment.
         * @param  totalCurrentAssets  String value for totalCurrentAssets.
         * @param  longTermInvestments  String value for longTermInvestments.
         * @param  netTangibleAssets  String value for netTangibleAssets.
         * @param  shortTermInvestments  String value for shortTermInvestments.
         * @param  netReceivables  String value for netReceivables.
         * @param  longTermDebt  String value for longTermDebt.
         * @param  inventory  String value for inventory.
         * @param  accountsPayable  String value for accountsPayable.
         * @param  totalPermanentEquity  String value for totalPermanentEquity.
         * @param  noncontrollingInterestInConsolidatedEntity  String value for
         *         noncontrollingInterestInConsolidatedEntity.
         * @param  temporaryEquityRedeemableNoncontrollingInterests  String value for
         *         temporaryEquityRedeemableNoncontrollingInterests.
         * @param  accumulatedOtherComprehensiveIncome  String value for
         *         accumulatedOtherComprehensiveIncome.
         * @param  additionalPaidInCapital  String value for additionalPaidInCapital.
         * @param  commonStockTotalEquity  String value for commonStockTotalEquity.
         * @param  preferredStockTotalEquity  String value for preferredStockTotalEquity.
         * @param  retainedEarningsTotalEquity  String value for retainedEarningsTotalEquity.
         * @param  treasuryStock  String value for treasuryStock.
         * @param  accumulatedAmortization  String value for accumulatedAmortization.
         * @param  nonCurrrentAssetsOther  String value for nonCurrrentAssetsOther.
         * @param  deferredLongTermAssetCharges  String value for deferredLongTermAssetCharges.
         * @param  nonCurrentAssetsTotal  String value for nonCurrentAssetsTotal.
         * @param  capitalLeaseObligations  String value for capitalLeaseObligations.
         * @param  longTermDebtTotal  String value for longTermDebtTotal.
         * @param  nonCurrentLiabilitiesOther  String value for nonCurrentLiabilitiesOther.
         * @param  nonCurrentLiabilitiesTotal  String value for nonCurrentLiabilitiesTotal.
         * @param  negativeGoodwill  String value for negativeGoodwill.
         * @param  warrants  String value for warrants.
         * @param  preferredStockRedeemable  String value for preferredStockRedeemable.
         * @param  capitalSurpluse  String value for capitalSurpluse.
         * @param  liabilitiesAndStockholdersEquity  String value for
         *         liabilitiesAndStockholdersEquity.
         * @param  cashAndShortTermInvestments  String value for cashAndShortTermInvestments.
         * @param  propertyPlantAndEquipmentGross  String value for propertyPlantAndEquipmentGross.
         * @param  propertyPlantAndEquipmentNet  String value for propertyPlantAndEquipmentNet.
         * @param  accumulatedDepreciation  String value for accumulatedDepreciation.
         * @param  netWorkingCapital  String value for netWorkingCapital.
         * @param  netInvestedCapital  String value for netInvestedCapital.
         * @param  commonStockSharesOutstanding  String value for commonStockSharesOutstanding.
         */
        public Builder(String date, String filingDate, String currencySymbol, String totalAssets,
                String intangibleAssets, String earningAssets, String otherCurrentAssets,
                String totalLiab, String totalStockholderEquity, String deferredLongTermLiab,
                String otherCurrentLiab, String commonStock, String capitalStock,
                String retainedEarnings, String otherLiab, String goodWill, String otherAssets,
                String cash, String cashAndEquivalents, String totalCurrentLiabilities,
                String netDebt, String shortTermDebt, String shortLongTermDebt,
                String shortLongTermDebtTotal, String otherStockholderEquity,
                String propertyPlantEquipment, String totalCurrentAssets,
                String longTermInvestments, String netTangibleAssets, String shortTermInvestments,
                String netReceivables, String longTermDebt, String inventory,
                String accountsPayable, String totalPermanentEquity,
                String noncontrollingInterestInConsolidatedEntity,
                String temporaryEquityRedeemableNoncontrollingInterests,
                String accumulatedOtherComprehensiveIncome, String additionalPaidInCapital,
                String commonStockTotalEquity, String preferredStockTotalEquity,
                String retainedEarningsTotalEquity, String treasuryStock,
                String accumulatedAmortization, String nonCurrrentAssetsOther,
                String deferredLongTermAssetCharges, String nonCurrentAssetsTotal,
                String capitalLeaseObligations, String longTermDebtTotal,
                String nonCurrentLiabilitiesOther, String nonCurrentLiabilitiesTotal,
                String negativeGoodwill, String warrants, String preferredStockRedeemable,
                String capitalSurpluse, String liabilitiesAndStockholdersEquity,
                String cashAndShortTermInvestments, String propertyPlantAndEquipmentGross,
                String propertyPlantAndEquipmentNet, String accumulatedDepreciation,
                String netWorkingCapital, String netInvestedCapital,
                String commonStockSharesOutstanding) {
            this.date = date;
            this.filingDate = filingDate;
            this.currencySymbol = currencySymbol;
            this.totalAssets = totalAssets;
            this.intangibleAssets = intangibleAssets;
            this.earningAssets = earningAssets;
            this.otherCurrentAssets = otherCurrentAssets;
            this.totalLiab = totalLiab;
            this.totalStockholderEquity = totalStockholderEquity;
            this.deferredLongTermLiab = deferredLongTermLiab;
            this.otherCurrentLiab = otherCurrentLiab;
            this.commonStock = commonStock;
            this.capitalStock = capitalStock;
            this.retainedEarnings = retainedEarnings;
            this.otherLiab = otherLiab;
            this.goodWill = goodWill;
            this.otherAssets = otherAssets;
            this.cash = cash;
            this.cashAndEquivalents = cashAndEquivalents;
            this.totalCurrentLiabilities = totalCurrentLiabilities;
            this.netDebt = netDebt;
            this.shortTermDebt = shortTermDebt;
            this.shortLongTermDebt = shortLongTermDebt;
            this.shortLongTermDebtTotal = shortLongTermDebtTotal;
            this.otherStockholderEquity = otherStockholderEquity;
            this.propertyPlantEquipment = propertyPlantEquipment;
            this.totalCurrentAssets = totalCurrentAssets;
            this.longTermInvestments = longTermInvestments;
            this.netTangibleAssets = netTangibleAssets;
            this.shortTermInvestments = shortTermInvestments;
            this.netReceivables = netReceivables;
            this.longTermDebt = longTermDebt;
            this.inventory = inventory;
            this.accountsPayable = accountsPayable;
            this.totalPermanentEquity = totalPermanentEquity;
            this.noncontrollingInterestInConsolidatedEntity =
                    noncontrollingInterestInConsolidatedEntity;
            this.temporaryEquityRedeemableNoncontrollingInterests =
                    temporaryEquityRedeemableNoncontrollingInterests;
            this.accumulatedOtherComprehensiveIncome = accumulatedOtherComprehensiveIncome;
            this.additionalPaidInCapital = additionalPaidInCapital;
            this.commonStockTotalEquity = commonStockTotalEquity;
            this.preferredStockTotalEquity = preferredStockTotalEquity;
            this.retainedEarningsTotalEquity = retainedEarningsTotalEquity;
            this.treasuryStock = treasuryStock;
            this.accumulatedAmortization = accumulatedAmortization;
            this.nonCurrrentAssetsOther = nonCurrrentAssetsOther;
            this.deferredLongTermAssetCharges = deferredLongTermAssetCharges;
            this.nonCurrentAssetsTotal = nonCurrentAssetsTotal;
            this.capitalLeaseObligations = capitalLeaseObligations;
            this.longTermDebtTotal = longTermDebtTotal;
            this.nonCurrentLiabilitiesOther = nonCurrentLiabilitiesOther;
            this.nonCurrentLiabilitiesTotal = nonCurrentLiabilitiesTotal;
            this.negativeGoodwill = negativeGoodwill;
            this.warrants = warrants;
            this.preferredStockRedeemable = preferredStockRedeemable;
            this.capitalSurpluse = capitalSurpluse;
            this.liabilitiesAndStockholdersEquity = liabilitiesAndStockholdersEquity;
            this.cashAndShortTermInvestments = cashAndShortTermInvestments;
            this.propertyPlantAndEquipmentGross = propertyPlantAndEquipmentGross;
            this.propertyPlantAndEquipmentNet = propertyPlantAndEquipmentNet;
            this.accumulatedDepreciation = accumulatedDepreciation;
            this.netWorkingCapital = netWorkingCapital;
            this.netInvestedCapital = netInvestedCapital;
            this.commonStockSharesOutstanding = commonStockSharesOutstanding;
        }

        /**
         * Setter for date.
         * @param  date  String value for date.
         * @return Builder
         */
        public Builder date(String date) {
            this.date = date;
            return this;
        }

        /**
         * Setter for filingDate.
         * @param  filingDate  String value for filingDate.
         * @return Builder
         */
        public Builder filingDate(String filingDate) {
            this.filingDate = filingDate;
            return this;
        }

        /**
         * Setter for currencySymbol.
         * @param  currencySymbol  String value for currencySymbol.
         * @return Builder
         */
        public Builder currencySymbol(String currencySymbol) {
            this.currencySymbol = currencySymbol;
            return this;
        }

        /**
         * Setter for totalAssets.
         * @param  totalAssets  String value for totalAssets.
         * @return Builder
         */
        public Builder totalAssets(String totalAssets) {
            this.totalAssets = totalAssets;
            return this;
        }

        /**
         * Setter for intangibleAssets.
         * @param  intangibleAssets  String value for intangibleAssets.
         * @return Builder
         */
        public Builder intangibleAssets(String intangibleAssets) {
            this.intangibleAssets = intangibleAssets;
            return this;
        }

        /**
         * Setter for earningAssets.
         * @param  earningAssets  String value for earningAssets.
         * @return Builder
         */
        public Builder earningAssets(String earningAssets) {
            this.earningAssets = earningAssets;
            return this;
        }

        /**
         * Setter for otherCurrentAssets.
         * @param  otherCurrentAssets  String value for otherCurrentAssets.
         * @return Builder
         */
        public Builder otherCurrentAssets(String otherCurrentAssets) {
            this.otherCurrentAssets = otherCurrentAssets;
            return this;
        }

        /**
         * Setter for totalLiab.
         * @param  totalLiab  String value for totalLiab.
         * @return Builder
         */
        public Builder totalLiab(String totalLiab) {
            this.totalLiab = totalLiab;
            return this;
        }

        /**
         * Setter for totalStockholderEquity.
         * @param  totalStockholderEquity  String value for totalStockholderEquity.
         * @return Builder
         */
        public Builder totalStockholderEquity(String totalStockholderEquity) {
            this.totalStockholderEquity = totalStockholderEquity;
            return this;
        }

        /**
         * Setter for deferredLongTermLiab.
         * @param  deferredLongTermLiab  String value for deferredLongTermLiab.
         * @return Builder
         */
        public Builder deferredLongTermLiab(String deferredLongTermLiab) {
            this.deferredLongTermLiab = deferredLongTermLiab;
            return this;
        }

        /**
         * Setter for otherCurrentLiab.
         * @param  otherCurrentLiab  String value for otherCurrentLiab.
         * @return Builder
         */
        public Builder otherCurrentLiab(String otherCurrentLiab) {
            this.otherCurrentLiab = otherCurrentLiab;
            return this;
        }

        /**
         * Setter for commonStock.
         * @param  commonStock  String value for commonStock.
         * @return Builder
         */
        public Builder commonStock(String commonStock) {
            this.commonStock = commonStock;
            return this;
        }

        /**
         * Setter for capitalStock.
         * @param  capitalStock  String value for capitalStock.
         * @return Builder
         */
        public Builder capitalStock(String capitalStock) {
            this.capitalStock = capitalStock;
            return this;
        }

        /**
         * Setter for retainedEarnings.
         * @param  retainedEarnings  String value for retainedEarnings.
         * @return Builder
         */
        public Builder retainedEarnings(String retainedEarnings) {
            this.retainedEarnings = retainedEarnings;
            return this;
        }

        /**
         * Setter for otherLiab.
         * @param  otherLiab  String value for otherLiab.
         * @return Builder
         */
        public Builder otherLiab(String otherLiab) {
            this.otherLiab = otherLiab;
            return this;
        }

        /**
         * Setter for goodWill.
         * @param  goodWill  String value for goodWill.
         * @return Builder
         */
        public Builder goodWill(String goodWill) {
            this.goodWill = goodWill;
            return this;
        }

        /**
         * Setter for otherAssets.
         * @param  otherAssets  String value for otherAssets.
         * @return Builder
         */
        public Builder otherAssets(String otherAssets) {
            this.otherAssets = otherAssets;
            return this;
        }

        /**
         * Setter for cash.
         * @param  cash  String value for cash.
         * @return Builder
         */
        public Builder cash(String cash) {
            this.cash = cash;
            return this;
        }

        /**
         * Setter for cashAndEquivalents.
         * @param  cashAndEquivalents  String value for cashAndEquivalents.
         * @return Builder
         */
        public Builder cashAndEquivalents(String cashAndEquivalents) {
            this.cashAndEquivalents = cashAndEquivalents;
            return this;
        }

        /**
         * Setter for totalCurrentLiabilities.
         * @param  totalCurrentLiabilities  String value for totalCurrentLiabilities.
         * @return Builder
         */
        public Builder totalCurrentLiabilities(String totalCurrentLiabilities) {
            this.totalCurrentLiabilities = totalCurrentLiabilities;
            return this;
        }

        /**
         * Setter for netDebt.
         * @param  netDebt  String value for netDebt.
         * @return Builder
         */
        public Builder netDebt(String netDebt) {
            this.netDebt = netDebt;
            return this;
        }

        /**
         * Setter for shortTermDebt.
         * @param  shortTermDebt  String value for shortTermDebt.
         * @return Builder
         */
        public Builder shortTermDebt(String shortTermDebt) {
            this.shortTermDebt = shortTermDebt;
            return this;
        }

        /**
         * Setter for shortLongTermDebt.
         * @param  shortLongTermDebt  String value for shortLongTermDebt.
         * @return Builder
         */
        public Builder shortLongTermDebt(String shortLongTermDebt) {
            this.shortLongTermDebt = shortLongTermDebt;
            return this;
        }

        /**
         * Setter for shortLongTermDebtTotal.
         * @param  shortLongTermDebtTotal  String value for shortLongTermDebtTotal.
         * @return Builder
         */
        public Builder shortLongTermDebtTotal(String shortLongTermDebtTotal) {
            this.shortLongTermDebtTotal = shortLongTermDebtTotal;
            return this;
        }

        /**
         * Setter for otherStockholderEquity.
         * @param  otherStockholderEquity  String value for otherStockholderEquity.
         * @return Builder
         */
        public Builder otherStockholderEquity(String otherStockholderEquity) {
            this.otherStockholderEquity = otherStockholderEquity;
            return this;
        }

        /**
         * Setter for propertyPlantEquipment.
         * @param  propertyPlantEquipment  String value for propertyPlantEquipment.
         * @return Builder
         */
        public Builder propertyPlantEquipment(String propertyPlantEquipment) {
            this.propertyPlantEquipment = propertyPlantEquipment;
            return this;
        }

        /**
         * Setter for totalCurrentAssets.
         * @param  totalCurrentAssets  String value for totalCurrentAssets.
         * @return Builder
         */
        public Builder totalCurrentAssets(String totalCurrentAssets) {
            this.totalCurrentAssets = totalCurrentAssets;
            return this;
        }

        /**
         * Setter for longTermInvestments.
         * @param  longTermInvestments  String value for longTermInvestments.
         * @return Builder
         */
        public Builder longTermInvestments(String longTermInvestments) {
            this.longTermInvestments = longTermInvestments;
            return this;
        }

        /**
         * Setter for netTangibleAssets.
         * @param  netTangibleAssets  String value for netTangibleAssets.
         * @return Builder
         */
        public Builder netTangibleAssets(String netTangibleAssets) {
            this.netTangibleAssets = netTangibleAssets;
            return this;
        }

        /**
         * Setter for shortTermInvestments.
         * @param  shortTermInvestments  String value for shortTermInvestments.
         * @return Builder
         */
        public Builder shortTermInvestments(String shortTermInvestments) {
            this.shortTermInvestments = shortTermInvestments;
            return this;
        }

        /**
         * Setter for netReceivables.
         * @param  netReceivables  String value for netReceivables.
         * @return Builder
         */
        public Builder netReceivables(String netReceivables) {
            this.netReceivables = netReceivables;
            return this;
        }

        /**
         * Setter for longTermDebt.
         * @param  longTermDebt  String value for longTermDebt.
         * @return Builder
         */
        public Builder longTermDebt(String longTermDebt) {
            this.longTermDebt = longTermDebt;
            return this;
        }

        /**
         * Setter for inventory.
         * @param  inventory  String value for inventory.
         * @return Builder
         */
        public Builder inventory(String inventory) {
            this.inventory = inventory;
            return this;
        }

        /**
         * Setter for accountsPayable.
         * @param  accountsPayable  String value for accountsPayable.
         * @return Builder
         */
        public Builder accountsPayable(String accountsPayable) {
            this.accountsPayable = accountsPayable;
            return this;
        }

        /**
         * Setter for totalPermanentEquity.
         * @param  totalPermanentEquity  String value for totalPermanentEquity.
         * @return Builder
         */
        public Builder totalPermanentEquity(String totalPermanentEquity) {
            this.totalPermanentEquity = totalPermanentEquity;
            return this;
        }

        /**
         * Setter for noncontrollingInterestInConsolidatedEntity.
         * @param  noncontrollingInterestInConsolidatedEntity  String value for
         *         noncontrollingInterestInConsolidatedEntity.
         * @return Builder
         */
        public Builder noncontrollingInterestInConsolidatedEntity(
                String noncontrollingInterestInConsolidatedEntity) {
            this.noncontrollingInterestInConsolidatedEntity =
                    noncontrollingInterestInConsolidatedEntity;
            return this;
        }

        /**
         * Setter for temporaryEquityRedeemableNoncontrollingInterests.
         * @param  temporaryEquityRedeemableNoncontrollingInterests  String value for
         *         temporaryEquityRedeemableNoncontrollingInterests.
         * @return Builder
         */
        public Builder temporaryEquityRedeemableNoncontrollingInterests(
                String temporaryEquityRedeemableNoncontrollingInterests) {
            this.temporaryEquityRedeemableNoncontrollingInterests =
                    temporaryEquityRedeemableNoncontrollingInterests;
            return this;
        }

        /**
         * Setter for accumulatedOtherComprehensiveIncome.
         * @param  accumulatedOtherComprehensiveIncome  String value for
         *         accumulatedOtherComprehensiveIncome.
         * @return Builder
         */
        public Builder accumulatedOtherComprehensiveIncome(
                String accumulatedOtherComprehensiveIncome) {
            this.accumulatedOtherComprehensiveIncome = accumulatedOtherComprehensiveIncome;
            return this;
        }

        /**
         * Setter for additionalPaidInCapital.
         * @param  additionalPaidInCapital  String value for additionalPaidInCapital.
         * @return Builder
         */
        public Builder additionalPaidInCapital(String additionalPaidInCapital) {
            this.additionalPaidInCapital = additionalPaidInCapital;
            return this;
        }

        /**
         * Setter for commonStockTotalEquity.
         * @param  commonStockTotalEquity  String value for commonStockTotalEquity.
         * @return Builder
         */
        public Builder commonStockTotalEquity(String commonStockTotalEquity) {
            this.commonStockTotalEquity = commonStockTotalEquity;
            return this;
        }

        /**
         * Setter for preferredStockTotalEquity.
         * @param  preferredStockTotalEquity  String value for preferredStockTotalEquity.
         * @return Builder
         */
        public Builder preferredStockTotalEquity(String preferredStockTotalEquity) {
            this.preferredStockTotalEquity = preferredStockTotalEquity;
            return this;
        }

        /**
         * Setter for retainedEarningsTotalEquity.
         * @param  retainedEarningsTotalEquity  String value for retainedEarningsTotalEquity.
         * @return Builder
         */
        public Builder retainedEarningsTotalEquity(String retainedEarningsTotalEquity) {
            this.retainedEarningsTotalEquity = retainedEarningsTotalEquity;
            return this;
        }

        /**
         * Setter for treasuryStock.
         * @param  treasuryStock  String value for treasuryStock.
         * @return Builder
         */
        public Builder treasuryStock(String treasuryStock) {
            this.treasuryStock = treasuryStock;
            return this;
        }

        /**
         * Setter for accumulatedAmortization.
         * @param  accumulatedAmortization  String value for accumulatedAmortization.
         * @return Builder
         */
        public Builder accumulatedAmortization(String accumulatedAmortization) {
            this.accumulatedAmortization = accumulatedAmortization;
            return this;
        }

        /**
         * Setter for nonCurrrentAssetsOther.
         * @param  nonCurrrentAssetsOther  String value for nonCurrrentAssetsOther.
         * @return Builder
         */
        public Builder nonCurrrentAssetsOther(String nonCurrrentAssetsOther) {
            this.nonCurrrentAssetsOther = nonCurrrentAssetsOther;
            return this;
        }

        /**
         * Setter for deferredLongTermAssetCharges.
         * @param  deferredLongTermAssetCharges  String value for deferredLongTermAssetCharges.
         * @return Builder
         */
        public Builder deferredLongTermAssetCharges(String deferredLongTermAssetCharges) {
            this.deferredLongTermAssetCharges = deferredLongTermAssetCharges;
            return this;
        }

        /**
         * Setter for nonCurrentAssetsTotal.
         * @param  nonCurrentAssetsTotal  String value for nonCurrentAssetsTotal.
         * @return Builder
         */
        public Builder nonCurrentAssetsTotal(String nonCurrentAssetsTotal) {
            this.nonCurrentAssetsTotal = nonCurrentAssetsTotal;
            return this;
        }

        /**
         * Setter for capitalLeaseObligations.
         * @param  capitalLeaseObligations  String value for capitalLeaseObligations.
         * @return Builder
         */
        public Builder capitalLeaseObligations(String capitalLeaseObligations) {
            this.capitalLeaseObligations = capitalLeaseObligations;
            return this;
        }

        /**
         * Setter for longTermDebtTotal.
         * @param  longTermDebtTotal  String value for longTermDebtTotal.
         * @return Builder
         */
        public Builder longTermDebtTotal(String longTermDebtTotal) {
            this.longTermDebtTotal = longTermDebtTotal;
            return this;
        }

        /**
         * Setter for nonCurrentLiabilitiesOther.
         * @param  nonCurrentLiabilitiesOther  String value for nonCurrentLiabilitiesOther.
         * @return Builder
         */
        public Builder nonCurrentLiabilitiesOther(String nonCurrentLiabilitiesOther) {
            this.nonCurrentLiabilitiesOther = nonCurrentLiabilitiesOther;
            return this;
        }

        /**
         * Setter for nonCurrentLiabilitiesTotal.
         * @param  nonCurrentLiabilitiesTotal  String value for nonCurrentLiabilitiesTotal.
         * @return Builder
         */
        public Builder nonCurrentLiabilitiesTotal(String nonCurrentLiabilitiesTotal) {
            this.nonCurrentLiabilitiesTotal = nonCurrentLiabilitiesTotal;
            return this;
        }

        /**
         * Setter for negativeGoodwill.
         * @param  negativeGoodwill  String value for negativeGoodwill.
         * @return Builder
         */
        public Builder negativeGoodwill(String negativeGoodwill) {
            this.negativeGoodwill = negativeGoodwill;
            return this;
        }

        /**
         * Setter for warrants.
         * @param  warrants  String value for warrants.
         * @return Builder
         */
        public Builder warrants(String warrants) {
            this.warrants = warrants;
            return this;
        }

        /**
         * Setter for preferredStockRedeemable.
         * @param  preferredStockRedeemable  String value for preferredStockRedeemable.
         * @return Builder
         */
        public Builder preferredStockRedeemable(String preferredStockRedeemable) {
            this.preferredStockRedeemable = preferredStockRedeemable;
            return this;
        }

        /**
         * Setter for capitalSurpluse.
         * @param  capitalSurpluse  String value for capitalSurpluse.
         * @return Builder
         */
        public Builder capitalSurpluse(String capitalSurpluse) {
            this.capitalSurpluse = capitalSurpluse;
            return this;
        }

        /**
         * Setter for liabilitiesAndStockholdersEquity.
         * @param  liabilitiesAndStockholdersEquity  String value for
         *         liabilitiesAndStockholdersEquity.
         * @return Builder
         */
        public Builder liabilitiesAndStockholdersEquity(String liabilitiesAndStockholdersEquity) {
            this.liabilitiesAndStockholdersEquity = liabilitiesAndStockholdersEquity;
            return this;
        }

        /**
         * Setter for cashAndShortTermInvestments.
         * @param  cashAndShortTermInvestments  String value for cashAndShortTermInvestments.
         * @return Builder
         */
        public Builder cashAndShortTermInvestments(String cashAndShortTermInvestments) {
            this.cashAndShortTermInvestments = cashAndShortTermInvestments;
            return this;
        }

        /**
         * Setter for propertyPlantAndEquipmentGross.
         * @param  propertyPlantAndEquipmentGross  String value for propertyPlantAndEquipmentGross.
         * @return Builder
         */
        public Builder propertyPlantAndEquipmentGross(String propertyPlantAndEquipmentGross) {
            this.propertyPlantAndEquipmentGross = propertyPlantAndEquipmentGross;
            return this;
        }

        /**
         * Setter for propertyPlantAndEquipmentNet.
         * @param  propertyPlantAndEquipmentNet  String value for propertyPlantAndEquipmentNet.
         * @return Builder
         */
        public Builder propertyPlantAndEquipmentNet(String propertyPlantAndEquipmentNet) {
            this.propertyPlantAndEquipmentNet = propertyPlantAndEquipmentNet;
            return this;
        }

        /**
         * Setter for accumulatedDepreciation.
         * @param  accumulatedDepreciation  String value for accumulatedDepreciation.
         * @return Builder
         */
        public Builder accumulatedDepreciation(String accumulatedDepreciation) {
            this.accumulatedDepreciation = accumulatedDepreciation;
            return this;
        }

        /**
         * Setter for netWorkingCapital.
         * @param  netWorkingCapital  String value for netWorkingCapital.
         * @return Builder
         */
        public Builder netWorkingCapital(String netWorkingCapital) {
            this.netWorkingCapital = netWorkingCapital;
            return this;
        }

        /**
         * Setter for netInvestedCapital.
         * @param  netInvestedCapital  String value for netInvestedCapital.
         * @return Builder
         */
        public Builder netInvestedCapital(String netInvestedCapital) {
            this.netInvestedCapital = netInvestedCapital;
            return this;
        }

        /**
         * Setter for commonStockSharesOutstanding.
         * @param  commonStockSharesOutstanding  String value for commonStockSharesOutstanding.
         * @return Builder
         */
        public Builder commonStockSharesOutstanding(String commonStockSharesOutstanding) {
            this.commonStockSharesOutstanding = commonStockSharesOutstanding;
            return this;
        }

        /**
         * Builds a new {@link GeneratedObject17} object using the set fields.
         * @return {@link GeneratedObject17}
         */
        public GeneratedObject17 build() {
            return new GeneratedObject17(date, filingDate, currencySymbol, totalAssets,
                    intangibleAssets, earningAssets, otherCurrentAssets, totalLiab,
                    totalStockholderEquity, deferredLongTermLiab, otherCurrentLiab, commonStock,
                    capitalStock, retainedEarnings, otherLiab, goodWill, otherAssets, cash,
                    cashAndEquivalents, totalCurrentLiabilities, netDebt, shortTermDebt,
                    shortLongTermDebt, shortLongTermDebtTotal, otherStockholderEquity,
                    propertyPlantEquipment, totalCurrentAssets, longTermInvestments,
                    netTangibleAssets, shortTermInvestments, netReceivables, longTermDebt,
                    inventory, accountsPayable, totalPermanentEquity,
                    noncontrollingInterestInConsolidatedEntity,
                    temporaryEquityRedeemableNoncontrollingInterests,
                    accumulatedOtherComprehensiveIncome, additionalPaidInCapital,
                    commonStockTotalEquity, preferredStockTotalEquity, retainedEarningsTotalEquity,
                    treasuryStock, accumulatedAmortization, nonCurrrentAssetsOther,
                    deferredLongTermAssetCharges, nonCurrentAssetsTotal, capitalLeaseObligations,
                    longTermDebtTotal, nonCurrentLiabilitiesOther, nonCurrentLiabilitiesTotal,
                    negativeGoodwill, warrants, preferredStockRedeemable, capitalSurpluse,
                    liabilitiesAndStockholdersEquity, cashAndShortTermInvestments,
                    propertyPlantAndEquipmentGross, propertyPlantAndEquipmentNet,
                    accumulatedDepreciation, netWorkingCapital, netInvestedCapital,
                    commonStockSharesOutstanding);
        }
    }
}
