/*
 * EODHistoricalDataFundamentalLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.eodhistoricaldata.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for GeneratedObject15 type.
 */
public class GeneratedObject15 {
    private String date;
    private String period;
    private String growth;
    private String earningsEstimateAvg;
    private String earningsEstimateLow;
    private String earningsEstimateHigh;
    private String earningsEstimateYearAgoEps;
    private String earningsEstimateNumberOfAnalysts;
    private String earningsEstimateGrowth;
    private String revenueEstimateAvg;
    private String revenueEstimateLow;
    private String revenueEstimateHigh;
    private String revenueEstimateYearAgoEps;
    private String revenueEstimateNumberOfAnalysts;
    private String revenueEstimateGrowth;
    private String epsTrendCurrent;
    private String epsTrend7daysAgo;
    private String epsTrend30daysAgo;
    private String epsTrend60daysAgo;
    private String epsTrend90daysAgo;
    private String epsRevisionsUpLast7days;
    private String epsRevisionsUpLast30days;
    private String epsRevisionsDownLast7days;
    private String epsRevisionsDownLast30days;

    /**
     * Default constructor.
     */
    public GeneratedObject15() {
    }

    /**
     * Initialization constructor.
     * @param  date  String value for date.
     * @param  period  String value for period.
     * @param  growth  String value for growth.
     * @param  earningsEstimateAvg  String value for earningsEstimateAvg.
     * @param  earningsEstimateLow  String value for earningsEstimateLow.
     * @param  earningsEstimateHigh  String value for earningsEstimateHigh.
     * @param  earningsEstimateYearAgoEps  String value for earningsEstimateYearAgoEps.
     * @param  earningsEstimateNumberOfAnalysts  String value for earningsEstimateNumberOfAnalysts.
     * @param  earningsEstimateGrowth  String value for earningsEstimateGrowth.
     * @param  revenueEstimateAvg  String value for revenueEstimateAvg.
     * @param  revenueEstimateLow  String value for revenueEstimateLow.
     * @param  revenueEstimateHigh  String value for revenueEstimateHigh.
     * @param  revenueEstimateYearAgoEps  String value for revenueEstimateYearAgoEps.
     * @param  revenueEstimateNumberOfAnalysts  String value for revenueEstimateNumberOfAnalysts.
     * @param  revenueEstimateGrowth  String value for revenueEstimateGrowth.
     * @param  epsTrendCurrent  String value for epsTrendCurrent.
     * @param  epsTrend7daysAgo  String value for epsTrend7daysAgo.
     * @param  epsTrend30daysAgo  String value for epsTrend30daysAgo.
     * @param  epsTrend60daysAgo  String value for epsTrend60daysAgo.
     * @param  epsTrend90daysAgo  String value for epsTrend90daysAgo.
     * @param  epsRevisionsUpLast7days  String value for epsRevisionsUpLast7days.
     * @param  epsRevisionsUpLast30days  String value for epsRevisionsUpLast30days.
     * @param  epsRevisionsDownLast7days  String value for epsRevisionsDownLast7days.
     * @param  epsRevisionsDownLast30days  String value for epsRevisionsDownLast30days.
     */
    public GeneratedObject15(
            String date,
            String period,
            String growth,
            String earningsEstimateAvg,
            String earningsEstimateLow,
            String earningsEstimateHigh,
            String earningsEstimateYearAgoEps,
            String earningsEstimateNumberOfAnalysts,
            String earningsEstimateGrowth,
            String revenueEstimateAvg,
            String revenueEstimateLow,
            String revenueEstimateHigh,
            String revenueEstimateYearAgoEps,
            String revenueEstimateNumberOfAnalysts,
            String revenueEstimateGrowth,
            String epsTrendCurrent,
            String epsTrend7daysAgo,
            String epsTrend30daysAgo,
            String epsTrend60daysAgo,
            String epsTrend90daysAgo,
            String epsRevisionsUpLast7days,
            String epsRevisionsUpLast30days,
            String epsRevisionsDownLast7days,
            String epsRevisionsDownLast30days) {
        this.date = date;
        this.period = period;
        this.growth = growth;
        this.earningsEstimateAvg = earningsEstimateAvg;
        this.earningsEstimateLow = earningsEstimateLow;
        this.earningsEstimateHigh = earningsEstimateHigh;
        this.earningsEstimateYearAgoEps = earningsEstimateYearAgoEps;
        this.earningsEstimateNumberOfAnalysts = earningsEstimateNumberOfAnalysts;
        this.earningsEstimateGrowth = earningsEstimateGrowth;
        this.revenueEstimateAvg = revenueEstimateAvg;
        this.revenueEstimateLow = revenueEstimateLow;
        this.revenueEstimateHigh = revenueEstimateHigh;
        this.revenueEstimateYearAgoEps = revenueEstimateYearAgoEps;
        this.revenueEstimateNumberOfAnalysts = revenueEstimateNumberOfAnalysts;
        this.revenueEstimateGrowth = revenueEstimateGrowth;
        this.epsTrendCurrent = epsTrendCurrent;
        this.epsTrend7daysAgo = epsTrend7daysAgo;
        this.epsTrend30daysAgo = epsTrend30daysAgo;
        this.epsTrend60daysAgo = epsTrend60daysAgo;
        this.epsTrend90daysAgo = epsTrend90daysAgo;
        this.epsRevisionsUpLast7days = epsRevisionsUpLast7days;
        this.epsRevisionsUpLast30days = epsRevisionsUpLast30days;
        this.epsRevisionsDownLast7days = epsRevisionsDownLast7days;
        this.epsRevisionsDownLast30days = epsRevisionsDownLast30days;
    }

    /**
     * Getter for Date.
     * @return Returns the String
     */
    @JsonGetter("date")
    public String getDate() {
        return date;
    }

    /**
     * Setter for Date.
     * @param date Value for String
     */
    @JsonSetter("date")
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * Getter for Period.
     * @return Returns the String
     */
    @JsonGetter("period")
    public String getPeriod() {
        return period;
    }

    /**
     * Setter for Period.
     * @param period Value for String
     */
    @JsonSetter("period")
    public void setPeriod(String period) {
        this.period = period;
    }

    /**
     * Getter for Growth.
     * @return Returns the String
     */
    @JsonGetter("growth")
    public String getGrowth() {
        return growth;
    }

    /**
     * Setter for Growth.
     * @param growth Value for String
     */
    @JsonSetter("growth")
    public void setGrowth(String growth) {
        this.growth = growth;
    }

    /**
     * Getter for EarningsEstimateAvg.
     * @return Returns the String
     */
    @JsonGetter("earningsEstimateAvg")
    public String getEarningsEstimateAvg() {
        return earningsEstimateAvg;
    }

    /**
     * Setter for EarningsEstimateAvg.
     * @param earningsEstimateAvg Value for String
     */
    @JsonSetter("earningsEstimateAvg")
    public void setEarningsEstimateAvg(String earningsEstimateAvg) {
        this.earningsEstimateAvg = earningsEstimateAvg;
    }

    /**
     * Getter for EarningsEstimateLow.
     * @return Returns the String
     */
    @JsonGetter("earningsEstimateLow")
    public String getEarningsEstimateLow() {
        return earningsEstimateLow;
    }

    /**
     * Setter for EarningsEstimateLow.
     * @param earningsEstimateLow Value for String
     */
    @JsonSetter("earningsEstimateLow")
    public void setEarningsEstimateLow(String earningsEstimateLow) {
        this.earningsEstimateLow = earningsEstimateLow;
    }

    /**
     * Getter for EarningsEstimateHigh.
     * @return Returns the String
     */
    @JsonGetter("earningsEstimateHigh")
    public String getEarningsEstimateHigh() {
        return earningsEstimateHigh;
    }

    /**
     * Setter for EarningsEstimateHigh.
     * @param earningsEstimateHigh Value for String
     */
    @JsonSetter("earningsEstimateHigh")
    public void setEarningsEstimateHigh(String earningsEstimateHigh) {
        this.earningsEstimateHigh = earningsEstimateHigh;
    }

    /**
     * Getter for EarningsEstimateYearAgoEps.
     * @return Returns the String
     */
    @JsonGetter("earningsEstimateYearAgoEps")
    public String getEarningsEstimateYearAgoEps() {
        return earningsEstimateYearAgoEps;
    }

    /**
     * Setter for EarningsEstimateYearAgoEps.
     * @param earningsEstimateYearAgoEps Value for String
     */
    @JsonSetter("earningsEstimateYearAgoEps")
    public void setEarningsEstimateYearAgoEps(String earningsEstimateYearAgoEps) {
        this.earningsEstimateYearAgoEps = earningsEstimateYearAgoEps;
    }

    /**
     * Getter for EarningsEstimateNumberOfAnalysts.
     * @return Returns the String
     */
    @JsonGetter("earningsEstimateNumberOfAnalysts")
    public String getEarningsEstimateNumberOfAnalysts() {
        return earningsEstimateNumberOfAnalysts;
    }

    /**
     * Setter for EarningsEstimateNumberOfAnalysts.
     * @param earningsEstimateNumberOfAnalysts Value for String
     */
    @JsonSetter("earningsEstimateNumberOfAnalysts")
    public void setEarningsEstimateNumberOfAnalysts(String earningsEstimateNumberOfAnalysts) {
        this.earningsEstimateNumberOfAnalysts = earningsEstimateNumberOfAnalysts;
    }

    /**
     * Getter for EarningsEstimateGrowth.
     * @return Returns the String
     */
    @JsonGetter("earningsEstimateGrowth")
    public String getEarningsEstimateGrowth() {
        return earningsEstimateGrowth;
    }

    /**
     * Setter for EarningsEstimateGrowth.
     * @param earningsEstimateGrowth Value for String
     */
    @JsonSetter("earningsEstimateGrowth")
    public void setEarningsEstimateGrowth(String earningsEstimateGrowth) {
        this.earningsEstimateGrowth = earningsEstimateGrowth;
    }

    /**
     * Getter for RevenueEstimateAvg.
     * @return Returns the String
     */
    @JsonGetter("revenueEstimateAvg")
    public String getRevenueEstimateAvg() {
        return revenueEstimateAvg;
    }

    /**
     * Setter for RevenueEstimateAvg.
     * @param revenueEstimateAvg Value for String
     */
    @JsonSetter("revenueEstimateAvg")
    public void setRevenueEstimateAvg(String revenueEstimateAvg) {
        this.revenueEstimateAvg = revenueEstimateAvg;
    }

    /**
     * Getter for RevenueEstimateLow.
     * @return Returns the String
     */
    @JsonGetter("revenueEstimateLow")
    public String getRevenueEstimateLow() {
        return revenueEstimateLow;
    }

    /**
     * Setter for RevenueEstimateLow.
     * @param revenueEstimateLow Value for String
     */
    @JsonSetter("revenueEstimateLow")
    public void setRevenueEstimateLow(String revenueEstimateLow) {
        this.revenueEstimateLow = revenueEstimateLow;
    }

    /**
     * Getter for RevenueEstimateHigh.
     * @return Returns the String
     */
    @JsonGetter("revenueEstimateHigh")
    public String getRevenueEstimateHigh() {
        return revenueEstimateHigh;
    }

    /**
     * Setter for RevenueEstimateHigh.
     * @param revenueEstimateHigh Value for String
     */
    @JsonSetter("revenueEstimateHigh")
    public void setRevenueEstimateHigh(String revenueEstimateHigh) {
        this.revenueEstimateHigh = revenueEstimateHigh;
    }

    /**
     * Getter for RevenueEstimateYearAgoEps.
     * @return Returns the String
     */
    @JsonGetter("revenueEstimateYearAgoEps")
    public String getRevenueEstimateYearAgoEps() {
        return revenueEstimateYearAgoEps;
    }

    /**
     * Setter for RevenueEstimateYearAgoEps.
     * @param revenueEstimateYearAgoEps Value for String
     */
    @JsonSetter("revenueEstimateYearAgoEps")
    public void setRevenueEstimateYearAgoEps(String revenueEstimateYearAgoEps) {
        this.revenueEstimateYearAgoEps = revenueEstimateYearAgoEps;
    }

    /**
     * Getter for RevenueEstimateNumberOfAnalysts.
     * @return Returns the String
     */
    @JsonGetter("revenueEstimateNumberOfAnalysts")
    public String getRevenueEstimateNumberOfAnalysts() {
        return revenueEstimateNumberOfAnalysts;
    }

    /**
     * Setter for RevenueEstimateNumberOfAnalysts.
     * @param revenueEstimateNumberOfAnalysts Value for String
     */
    @JsonSetter("revenueEstimateNumberOfAnalysts")
    public void setRevenueEstimateNumberOfAnalysts(String revenueEstimateNumberOfAnalysts) {
        this.revenueEstimateNumberOfAnalysts = revenueEstimateNumberOfAnalysts;
    }

    /**
     * Getter for RevenueEstimateGrowth.
     * @return Returns the String
     */
    @JsonGetter("revenueEstimateGrowth")
    public String getRevenueEstimateGrowth() {
        return revenueEstimateGrowth;
    }

    /**
     * Setter for RevenueEstimateGrowth.
     * @param revenueEstimateGrowth Value for String
     */
    @JsonSetter("revenueEstimateGrowth")
    public void setRevenueEstimateGrowth(String revenueEstimateGrowth) {
        this.revenueEstimateGrowth = revenueEstimateGrowth;
    }

    /**
     * Getter for EpsTrendCurrent.
     * @return Returns the String
     */
    @JsonGetter("epsTrendCurrent")
    public String getEpsTrendCurrent() {
        return epsTrendCurrent;
    }

    /**
     * Setter for EpsTrendCurrent.
     * @param epsTrendCurrent Value for String
     */
    @JsonSetter("epsTrendCurrent")
    public void setEpsTrendCurrent(String epsTrendCurrent) {
        this.epsTrendCurrent = epsTrendCurrent;
    }

    /**
     * Getter for EpsTrend7daysAgo.
     * @return Returns the String
     */
    @JsonGetter("epsTrend7daysAgo")
    public String getEpsTrend7daysAgo() {
        return epsTrend7daysAgo;
    }

    /**
     * Setter for EpsTrend7daysAgo.
     * @param epsTrend7daysAgo Value for String
     */
    @JsonSetter("epsTrend7daysAgo")
    public void setEpsTrend7daysAgo(String epsTrend7daysAgo) {
        this.epsTrend7daysAgo = epsTrend7daysAgo;
    }

    /**
     * Getter for EpsTrend30daysAgo.
     * @return Returns the String
     */
    @JsonGetter("epsTrend30daysAgo")
    public String getEpsTrend30daysAgo() {
        return epsTrend30daysAgo;
    }

    /**
     * Setter for EpsTrend30daysAgo.
     * @param epsTrend30daysAgo Value for String
     */
    @JsonSetter("epsTrend30daysAgo")
    public void setEpsTrend30daysAgo(String epsTrend30daysAgo) {
        this.epsTrend30daysAgo = epsTrend30daysAgo;
    }

    /**
     * Getter for EpsTrend60daysAgo.
     * @return Returns the String
     */
    @JsonGetter("epsTrend60daysAgo")
    public String getEpsTrend60daysAgo() {
        return epsTrend60daysAgo;
    }

    /**
     * Setter for EpsTrend60daysAgo.
     * @param epsTrend60daysAgo Value for String
     */
    @JsonSetter("epsTrend60daysAgo")
    public void setEpsTrend60daysAgo(String epsTrend60daysAgo) {
        this.epsTrend60daysAgo = epsTrend60daysAgo;
    }

    /**
     * Getter for EpsTrend90daysAgo.
     * @return Returns the String
     */
    @JsonGetter("epsTrend90daysAgo")
    public String getEpsTrend90daysAgo() {
        return epsTrend90daysAgo;
    }

    /**
     * Setter for EpsTrend90daysAgo.
     * @param epsTrend90daysAgo Value for String
     */
    @JsonSetter("epsTrend90daysAgo")
    public void setEpsTrend90daysAgo(String epsTrend90daysAgo) {
        this.epsTrend90daysAgo = epsTrend90daysAgo;
    }

    /**
     * Getter for EpsRevisionsUpLast7days.
     * @return Returns the String
     */
    @JsonGetter("epsRevisionsUpLast7days")
    public String getEpsRevisionsUpLast7days() {
        return epsRevisionsUpLast7days;
    }

    /**
     * Setter for EpsRevisionsUpLast7days.
     * @param epsRevisionsUpLast7days Value for String
     */
    @JsonSetter("epsRevisionsUpLast7days")
    public void setEpsRevisionsUpLast7days(String epsRevisionsUpLast7days) {
        this.epsRevisionsUpLast7days = epsRevisionsUpLast7days;
    }

    /**
     * Getter for EpsRevisionsUpLast30days.
     * @return Returns the String
     */
    @JsonGetter("epsRevisionsUpLast30days")
    public String getEpsRevisionsUpLast30days() {
        return epsRevisionsUpLast30days;
    }

    /**
     * Setter for EpsRevisionsUpLast30days.
     * @param epsRevisionsUpLast30days Value for String
     */
    @JsonSetter("epsRevisionsUpLast30days")
    public void setEpsRevisionsUpLast30days(String epsRevisionsUpLast30days) {
        this.epsRevisionsUpLast30days = epsRevisionsUpLast30days;
    }

    /**
     * Getter for EpsRevisionsDownLast7days.
     * @return Returns the String
     */
    @JsonGetter("epsRevisionsDownLast7days")
    public String getEpsRevisionsDownLast7days() {
        return epsRevisionsDownLast7days;
    }

    /**
     * Setter for EpsRevisionsDownLast7days.
     * @param epsRevisionsDownLast7days Value for String
     */
    @JsonSetter("epsRevisionsDownLast7days")
    public void setEpsRevisionsDownLast7days(String epsRevisionsDownLast7days) {
        this.epsRevisionsDownLast7days = epsRevisionsDownLast7days;
    }

    /**
     * Getter for EpsRevisionsDownLast30days.
     * @return Returns the String
     */
    @JsonGetter("epsRevisionsDownLast30days")
    public String getEpsRevisionsDownLast30days() {
        return epsRevisionsDownLast30days;
    }

    /**
     * Setter for EpsRevisionsDownLast30days.
     * @param epsRevisionsDownLast30days Value for String
     */
    @JsonSetter("epsRevisionsDownLast30days")
    public void setEpsRevisionsDownLast30days(String epsRevisionsDownLast30days) {
        this.epsRevisionsDownLast30days = epsRevisionsDownLast30days;
    }

    /**
     * Converts this GeneratedObject15 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GeneratedObject15 [" + "date=" + date + ", period=" + period + ", growth=" + growth
                + ", earningsEstimateAvg=" + earningsEstimateAvg + ", earningsEstimateLow="
                + earningsEstimateLow + ", earningsEstimateHigh=" + earningsEstimateHigh
                + ", earningsEstimateYearAgoEps=" + earningsEstimateYearAgoEps
                + ", earningsEstimateNumberOfAnalysts=" + earningsEstimateNumberOfAnalysts
                + ", earningsEstimateGrowth=" + earningsEstimateGrowth + ", revenueEstimateAvg="
                + revenueEstimateAvg + ", revenueEstimateLow=" + revenueEstimateLow
                + ", revenueEstimateHigh=" + revenueEstimateHigh + ", revenueEstimateYearAgoEps="
                + revenueEstimateYearAgoEps + ", revenueEstimateNumberOfAnalysts="
                + revenueEstimateNumberOfAnalysts + ", revenueEstimateGrowth="
                + revenueEstimateGrowth + ", epsTrendCurrent=" + epsTrendCurrent
                + ", epsTrend7daysAgo=" + epsTrend7daysAgo + ", epsTrend30daysAgo="
                + epsTrend30daysAgo + ", epsTrend60daysAgo=" + epsTrend60daysAgo
                + ", epsTrend90daysAgo=" + epsTrend90daysAgo + ", epsRevisionsUpLast7days="
                + epsRevisionsUpLast7days + ", epsRevisionsUpLast30days=" + epsRevisionsUpLast30days
                + ", epsRevisionsDownLast7days=" + epsRevisionsDownLast7days
                + ", epsRevisionsDownLast30days=" + epsRevisionsDownLast30days + "]";
    }

    /**
     * Builds a new {@link GeneratedObject15.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GeneratedObject15.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(date, period, growth, earningsEstimateAvg,
                earningsEstimateLow, earningsEstimateHigh, earningsEstimateYearAgoEps,
                earningsEstimateNumberOfAnalysts, earningsEstimateGrowth, revenueEstimateAvg,
                revenueEstimateLow, revenueEstimateHigh, revenueEstimateYearAgoEps,
                revenueEstimateNumberOfAnalysts, revenueEstimateGrowth, epsTrendCurrent,
                epsTrend7daysAgo, epsTrend30daysAgo, epsTrend60daysAgo, epsTrend90daysAgo,
                epsRevisionsUpLast7days, epsRevisionsUpLast30days, epsRevisionsDownLast7days,
                epsRevisionsDownLast30days);
        return builder;
    }

    /**
     * Class to build instances of {@link GeneratedObject15}.
     */
    public static class Builder {
        private String date;
        private String period;
        private String growth;
        private String earningsEstimateAvg;
        private String earningsEstimateLow;
        private String earningsEstimateHigh;
        private String earningsEstimateYearAgoEps;
        private String earningsEstimateNumberOfAnalysts;
        private String earningsEstimateGrowth;
        private String revenueEstimateAvg;
        private String revenueEstimateLow;
        private String revenueEstimateHigh;
        private String revenueEstimateYearAgoEps;
        private String revenueEstimateNumberOfAnalysts;
        private String revenueEstimateGrowth;
        private String epsTrendCurrent;
        private String epsTrend7daysAgo;
        private String epsTrend30daysAgo;
        private String epsTrend60daysAgo;
        private String epsTrend90daysAgo;
        private String epsRevisionsUpLast7days;
        private String epsRevisionsUpLast30days;
        private String epsRevisionsDownLast7days;
        private String epsRevisionsDownLast30days;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  date  String value for date.
         * @param  period  String value for period.
         * @param  growth  String value for growth.
         * @param  earningsEstimateAvg  String value for earningsEstimateAvg.
         * @param  earningsEstimateLow  String value for earningsEstimateLow.
         * @param  earningsEstimateHigh  String value for earningsEstimateHigh.
         * @param  earningsEstimateYearAgoEps  String value for earningsEstimateYearAgoEps.
         * @param  earningsEstimateNumberOfAnalysts  String value for
         *         earningsEstimateNumberOfAnalysts.
         * @param  earningsEstimateGrowth  String value for earningsEstimateGrowth.
         * @param  revenueEstimateAvg  String value for revenueEstimateAvg.
         * @param  revenueEstimateLow  String value for revenueEstimateLow.
         * @param  revenueEstimateHigh  String value for revenueEstimateHigh.
         * @param  revenueEstimateYearAgoEps  String value for revenueEstimateYearAgoEps.
         * @param  revenueEstimateNumberOfAnalysts  String value for
         *         revenueEstimateNumberOfAnalysts.
         * @param  revenueEstimateGrowth  String value for revenueEstimateGrowth.
         * @param  epsTrendCurrent  String value for epsTrendCurrent.
         * @param  epsTrend7daysAgo  String value for epsTrend7daysAgo.
         * @param  epsTrend30daysAgo  String value for epsTrend30daysAgo.
         * @param  epsTrend60daysAgo  String value for epsTrend60daysAgo.
         * @param  epsTrend90daysAgo  String value for epsTrend90daysAgo.
         * @param  epsRevisionsUpLast7days  String value for epsRevisionsUpLast7days.
         * @param  epsRevisionsUpLast30days  String value for epsRevisionsUpLast30days.
         * @param  epsRevisionsDownLast7days  String value for epsRevisionsDownLast7days.
         * @param  epsRevisionsDownLast30days  String value for epsRevisionsDownLast30days.
         */
        public Builder(String date, String period, String growth, String earningsEstimateAvg,
                String earningsEstimateLow, String earningsEstimateHigh,
                String earningsEstimateYearAgoEps, String earningsEstimateNumberOfAnalysts,
                String earningsEstimateGrowth, String revenueEstimateAvg, String revenueEstimateLow,
                String revenueEstimateHigh, String revenueEstimateYearAgoEps,
                String revenueEstimateNumberOfAnalysts, String revenueEstimateGrowth,
                String epsTrendCurrent, String epsTrend7daysAgo, String epsTrend30daysAgo,
                String epsTrend60daysAgo, String epsTrend90daysAgo, String epsRevisionsUpLast7days,
                String epsRevisionsUpLast30days, String epsRevisionsDownLast7days,
                String epsRevisionsDownLast30days) {
            this.date = date;
            this.period = period;
            this.growth = growth;
            this.earningsEstimateAvg = earningsEstimateAvg;
            this.earningsEstimateLow = earningsEstimateLow;
            this.earningsEstimateHigh = earningsEstimateHigh;
            this.earningsEstimateYearAgoEps = earningsEstimateYearAgoEps;
            this.earningsEstimateNumberOfAnalysts = earningsEstimateNumberOfAnalysts;
            this.earningsEstimateGrowth = earningsEstimateGrowth;
            this.revenueEstimateAvg = revenueEstimateAvg;
            this.revenueEstimateLow = revenueEstimateLow;
            this.revenueEstimateHigh = revenueEstimateHigh;
            this.revenueEstimateYearAgoEps = revenueEstimateYearAgoEps;
            this.revenueEstimateNumberOfAnalysts = revenueEstimateNumberOfAnalysts;
            this.revenueEstimateGrowth = revenueEstimateGrowth;
            this.epsTrendCurrent = epsTrendCurrent;
            this.epsTrend7daysAgo = epsTrend7daysAgo;
            this.epsTrend30daysAgo = epsTrend30daysAgo;
            this.epsTrend60daysAgo = epsTrend60daysAgo;
            this.epsTrend90daysAgo = epsTrend90daysAgo;
            this.epsRevisionsUpLast7days = epsRevisionsUpLast7days;
            this.epsRevisionsUpLast30days = epsRevisionsUpLast30days;
            this.epsRevisionsDownLast7days = epsRevisionsDownLast7days;
            this.epsRevisionsDownLast30days = epsRevisionsDownLast30days;
        }

        /**
         * Setter for date.
         * @param  date  String value for date.
         * @return Builder
         */
        public Builder date(String date) {
            this.date = date;
            return this;
        }

        /**
         * Setter for period.
         * @param  period  String value for period.
         * @return Builder
         */
        public Builder period(String period) {
            this.period = period;
            return this;
        }

        /**
         * Setter for growth.
         * @param  growth  String value for growth.
         * @return Builder
         */
        public Builder growth(String growth) {
            this.growth = growth;
            return this;
        }

        /**
         * Setter for earningsEstimateAvg.
         * @param  earningsEstimateAvg  String value for earningsEstimateAvg.
         * @return Builder
         */
        public Builder earningsEstimateAvg(String earningsEstimateAvg) {
            this.earningsEstimateAvg = earningsEstimateAvg;
            return this;
        }

        /**
         * Setter for earningsEstimateLow.
         * @param  earningsEstimateLow  String value for earningsEstimateLow.
         * @return Builder
         */
        public Builder earningsEstimateLow(String earningsEstimateLow) {
            this.earningsEstimateLow = earningsEstimateLow;
            return this;
        }

        /**
         * Setter for earningsEstimateHigh.
         * @param  earningsEstimateHigh  String value for earningsEstimateHigh.
         * @return Builder
         */
        public Builder earningsEstimateHigh(String earningsEstimateHigh) {
            this.earningsEstimateHigh = earningsEstimateHigh;
            return this;
        }

        /**
         * Setter for earningsEstimateYearAgoEps.
         * @param  earningsEstimateYearAgoEps  String value for earningsEstimateYearAgoEps.
         * @return Builder
         */
        public Builder earningsEstimateYearAgoEps(String earningsEstimateYearAgoEps) {
            this.earningsEstimateYearAgoEps = earningsEstimateYearAgoEps;
            return this;
        }

        /**
         * Setter for earningsEstimateNumberOfAnalysts.
         * @param  earningsEstimateNumberOfAnalysts  String value for
         *         earningsEstimateNumberOfAnalysts.
         * @return Builder
         */
        public Builder earningsEstimateNumberOfAnalysts(String earningsEstimateNumberOfAnalysts) {
            this.earningsEstimateNumberOfAnalysts = earningsEstimateNumberOfAnalysts;
            return this;
        }

        /**
         * Setter for earningsEstimateGrowth.
         * @param  earningsEstimateGrowth  String value for earningsEstimateGrowth.
         * @return Builder
         */
        public Builder earningsEstimateGrowth(String earningsEstimateGrowth) {
            this.earningsEstimateGrowth = earningsEstimateGrowth;
            return this;
        }

        /**
         * Setter for revenueEstimateAvg.
         * @param  revenueEstimateAvg  String value for revenueEstimateAvg.
         * @return Builder
         */
        public Builder revenueEstimateAvg(String revenueEstimateAvg) {
            this.revenueEstimateAvg = revenueEstimateAvg;
            return this;
        }

        /**
         * Setter for revenueEstimateLow.
         * @param  revenueEstimateLow  String value for revenueEstimateLow.
         * @return Builder
         */
        public Builder revenueEstimateLow(String revenueEstimateLow) {
            this.revenueEstimateLow = revenueEstimateLow;
            return this;
        }

        /**
         * Setter for revenueEstimateHigh.
         * @param  revenueEstimateHigh  String value for revenueEstimateHigh.
         * @return Builder
         */
        public Builder revenueEstimateHigh(String revenueEstimateHigh) {
            this.revenueEstimateHigh = revenueEstimateHigh;
            return this;
        }

        /**
         * Setter for revenueEstimateYearAgoEps.
         * @param  revenueEstimateYearAgoEps  String value for revenueEstimateYearAgoEps.
         * @return Builder
         */
        public Builder revenueEstimateYearAgoEps(String revenueEstimateYearAgoEps) {
            this.revenueEstimateYearAgoEps = revenueEstimateYearAgoEps;
            return this;
        }

        /**
         * Setter for revenueEstimateNumberOfAnalysts.
         * @param  revenueEstimateNumberOfAnalysts  String value for
         *         revenueEstimateNumberOfAnalysts.
         * @return Builder
         */
        public Builder revenueEstimateNumberOfAnalysts(String revenueEstimateNumberOfAnalysts) {
            this.revenueEstimateNumberOfAnalysts = revenueEstimateNumberOfAnalysts;
            return this;
        }

        /**
         * Setter for revenueEstimateGrowth.
         * @param  revenueEstimateGrowth  String value for revenueEstimateGrowth.
         * @return Builder
         */
        public Builder revenueEstimateGrowth(String revenueEstimateGrowth) {
            this.revenueEstimateGrowth = revenueEstimateGrowth;
            return this;
        }

        /**
         * Setter for epsTrendCurrent.
         * @param  epsTrendCurrent  String value for epsTrendCurrent.
         * @return Builder
         */
        public Builder epsTrendCurrent(String epsTrendCurrent) {
            this.epsTrendCurrent = epsTrendCurrent;
            return this;
        }

        /**
         * Setter for epsTrend7daysAgo.
         * @param  epsTrend7daysAgo  String value for epsTrend7daysAgo.
         * @return Builder
         */
        public Builder epsTrend7daysAgo(String epsTrend7daysAgo) {
            this.epsTrend7daysAgo = epsTrend7daysAgo;
            return this;
        }

        /**
         * Setter for epsTrend30daysAgo.
         * @param  epsTrend30daysAgo  String value for epsTrend30daysAgo.
         * @return Builder
         */
        public Builder epsTrend30daysAgo(String epsTrend30daysAgo) {
            this.epsTrend30daysAgo = epsTrend30daysAgo;
            return this;
        }

        /**
         * Setter for epsTrend60daysAgo.
         * @param  epsTrend60daysAgo  String value for epsTrend60daysAgo.
         * @return Builder
         */
        public Builder epsTrend60daysAgo(String epsTrend60daysAgo) {
            this.epsTrend60daysAgo = epsTrend60daysAgo;
            return this;
        }

        /**
         * Setter for epsTrend90daysAgo.
         * @param  epsTrend90daysAgo  String value for epsTrend90daysAgo.
         * @return Builder
         */
        public Builder epsTrend90daysAgo(String epsTrend90daysAgo) {
            this.epsTrend90daysAgo = epsTrend90daysAgo;
            return this;
        }

        /**
         * Setter for epsRevisionsUpLast7days.
         * @param  epsRevisionsUpLast7days  String value for epsRevisionsUpLast7days.
         * @return Builder
         */
        public Builder epsRevisionsUpLast7days(String epsRevisionsUpLast7days) {
            this.epsRevisionsUpLast7days = epsRevisionsUpLast7days;
            return this;
        }

        /**
         * Setter for epsRevisionsUpLast30days.
         * @param  epsRevisionsUpLast30days  String value for epsRevisionsUpLast30days.
         * @return Builder
         */
        public Builder epsRevisionsUpLast30days(String epsRevisionsUpLast30days) {
            this.epsRevisionsUpLast30days = epsRevisionsUpLast30days;
            return this;
        }

        /**
         * Setter for epsRevisionsDownLast7days.
         * @param  epsRevisionsDownLast7days  String value for epsRevisionsDownLast7days.
         * @return Builder
         */
        public Builder epsRevisionsDownLast7days(String epsRevisionsDownLast7days) {
            this.epsRevisionsDownLast7days = epsRevisionsDownLast7days;
            return this;
        }

        /**
         * Setter for epsRevisionsDownLast30days.
         * @param  epsRevisionsDownLast30days  String value for epsRevisionsDownLast30days.
         * @return Builder
         */
        public Builder epsRevisionsDownLast30days(String epsRevisionsDownLast30days) {
            this.epsRevisionsDownLast30days = epsRevisionsDownLast30days;
            return this;
        }

        /**
         * Builds a new {@link GeneratedObject15} object using the set fields.
         * @return {@link GeneratedObject15}
         */
        public GeneratedObject15 build() {
            return new GeneratedObject15(date, period, growth, earningsEstimateAvg,
                    earningsEstimateLow, earningsEstimateHigh, earningsEstimateYearAgoEps,
                    earningsEstimateNumberOfAnalysts, earningsEstimateGrowth, revenueEstimateAvg,
                    revenueEstimateLow, revenueEstimateHigh, revenueEstimateYearAgoEps,
                    revenueEstimateNumberOfAnalysts, revenueEstimateGrowth, epsTrendCurrent,
                    epsTrend7daysAgo, epsTrend30daysAgo, epsTrend60daysAgo, epsTrend90daysAgo,
                    epsRevisionsUpLast7days, epsRevisionsUpLast30days, epsRevisionsDownLast7days,
                    epsRevisionsDownLast30days);
        }
    }
}
