/*
 * EODHistoricalDataFundamentalLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.eodhistoricaldata.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for GeneratedObject2 type.
 */
public class GeneratedObject2 {
    private int year;
    private int count;

    /**
     * Default constructor.
     */
    public GeneratedObject2() {
    }

    /**
     * Initialization constructor.
     * @param  year  int value for year.
     * @param  count  int value for count.
     */
    public GeneratedObject2(
            int year,
            int count) {
        this.year = year;
        this.count = count;
    }

    /**
     * Getter for Year.
     * @return Returns the int
     */
    @JsonGetter("Year")
    public int getYear() {
        return year;
    }

    /**
     * Setter for Year.
     * @param year Value for int
     */
    @JsonSetter("Year")
    public void setYear(int year) {
        this.year = year;
    }

    /**
     * Getter for Count.
     * @return Returns the int
     */
    @JsonGetter("Count")
    public int getCount() {
        return count;
    }

    /**
     * Setter for Count.
     * @param count Value for int
     */
    @JsonSetter("Count")
    public void setCount(int count) {
        this.count = count;
    }

    /**
     * Converts this GeneratedObject2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GeneratedObject2 [" + "year=" + year + ", count=" + count + "]";
    }

    /**
     * Builds a new {@link GeneratedObject2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GeneratedObject2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(year, count);
        return builder;
    }

    /**
     * Class to build instances of {@link GeneratedObject2}.
     */
    public static class Builder {
        private int year;
        private int count;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  year  int value for year.
         * @param  count  int value for count.
         */
        public Builder(int year, int count) {
            this.year = year;
            this.count = count;
        }

        /**
         * Setter for year.
         * @param  year  int value for year.
         * @return Builder
         */
        public Builder year(int year) {
            this.year = year;
            return this;
        }

        /**
         * Setter for count.
         * @param  count  int value for count.
         * @return Builder
         */
        public Builder count(int count) {
            this.count = count;
            return this;
        }

        /**
         * Builds a new {@link GeneratedObject2} object using the set fields.
         * @return {@link GeneratedObject2}
         */
        public GeneratedObject2 build() {
            return new GeneratedObject2(year, count);
        }
    }
}
