/*
 * EODHistoricalDataFundamentalLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.eodhistoricaldata.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for SharesStats type.
 */
public class SharesStats {
    private long sharesOutstanding;
    private long sharesFloat;
    private double percentInsiders;
    private double percentInstitutions;
    private String sharesShort;
    private String sharesShortPriorMonth;
    private String shortRatio;
    private String shortPercentOutstanding;
    private String shortPercentFloat;

    /**
     * Default constructor.
     */
    public SharesStats() {
    }

    /**
     * Initialization constructor.
     * @param  sharesOutstanding  long value for sharesOutstanding.
     * @param  sharesFloat  long value for sharesFloat.
     * @param  percentInsiders  double value for percentInsiders.
     * @param  percentInstitutions  double value for percentInstitutions.
     * @param  sharesShort  String value for sharesShort.
     * @param  sharesShortPriorMonth  String value for sharesShortPriorMonth.
     * @param  shortRatio  String value for shortRatio.
     * @param  shortPercentOutstanding  String value for shortPercentOutstanding.
     * @param  shortPercentFloat  String value for shortPercentFloat.
     */
    public SharesStats(
            long sharesOutstanding,
            long sharesFloat,
            double percentInsiders,
            double percentInstitutions,
            String sharesShort,
            String sharesShortPriorMonth,
            String shortRatio,
            String shortPercentOutstanding,
            String shortPercentFloat) {
        this.sharesOutstanding = sharesOutstanding;
        this.sharesFloat = sharesFloat;
        this.percentInsiders = percentInsiders;
        this.percentInstitutions = percentInstitutions;
        this.sharesShort = sharesShort;
        this.sharesShortPriorMonth = sharesShortPriorMonth;
        this.shortRatio = shortRatio;
        this.shortPercentOutstanding = shortPercentOutstanding;
        this.shortPercentFloat = shortPercentFloat;
    }

    /**
     * Getter for SharesOutstanding.
     * @return Returns the long
     */
    @JsonGetter("SharesOutstanding")
    public long getSharesOutstanding() {
        return sharesOutstanding;
    }

    /**
     * Setter for SharesOutstanding.
     * @param sharesOutstanding Value for long
     */
    @JsonSetter("SharesOutstanding")
    public void setSharesOutstanding(long sharesOutstanding) {
        this.sharesOutstanding = sharesOutstanding;
    }

    /**
     * Getter for SharesFloat.
     * @return Returns the long
     */
    @JsonGetter("SharesFloat")
    public long getSharesFloat() {
        return sharesFloat;
    }

    /**
     * Setter for SharesFloat.
     * @param sharesFloat Value for long
     */
    @JsonSetter("SharesFloat")
    public void setSharesFloat(long sharesFloat) {
        this.sharesFloat = sharesFloat;
    }

    /**
     * Getter for PercentInsiders.
     * @return Returns the double
     */
    @JsonGetter("PercentInsiders")
    public double getPercentInsiders() {
        return percentInsiders;
    }

    /**
     * Setter for PercentInsiders.
     * @param percentInsiders Value for double
     */
    @JsonSetter("PercentInsiders")
    public void setPercentInsiders(double percentInsiders) {
        this.percentInsiders = percentInsiders;
    }

    /**
     * Getter for PercentInstitutions.
     * @return Returns the double
     */
    @JsonGetter("PercentInstitutions")
    public double getPercentInstitutions() {
        return percentInstitutions;
    }

    /**
     * Setter for PercentInstitutions.
     * @param percentInstitutions Value for double
     */
    @JsonSetter("PercentInstitutions")
    public void setPercentInstitutions(double percentInstitutions) {
        this.percentInstitutions = percentInstitutions;
    }

    /**
     * Getter for SharesShort.
     * @return Returns the String
     */
    @JsonGetter("SharesShort")
    public String getSharesShort() {
        return sharesShort;
    }

    /**
     * Setter for SharesShort.
     * @param sharesShort Value for String
     */
    @JsonSetter("SharesShort")
    public void setSharesShort(String sharesShort) {
        this.sharesShort = sharesShort;
    }

    /**
     * Getter for SharesShortPriorMonth.
     * @return Returns the String
     */
    @JsonGetter("SharesShortPriorMonth")
    public String getSharesShortPriorMonth() {
        return sharesShortPriorMonth;
    }

    /**
     * Setter for SharesShortPriorMonth.
     * @param sharesShortPriorMonth Value for String
     */
    @JsonSetter("SharesShortPriorMonth")
    public void setSharesShortPriorMonth(String sharesShortPriorMonth) {
        this.sharesShortPriorMonth = sharesShortPriorMonth;
    }

    /**
     * Getter for ShortRatio.
     * @return Returns the String
     */
    @JsonGetter("ShortRatio")
    public String getShortRatio() {
        return shortRatio;
    }

    /**
     * Setter for ShortRatio.
     * @param shortRatio Value for String
     */
    @JsonSetter("ShortRatio")
    public void setShortRatio(String shortRatio) {
        this.shortRatio = shortRatio;
    }

    /**
     * Getter for ShortPercentOutstanding.
     * @return Returns the String
     */
    @JsonGetter("ShortPercentOutstanding")
    public String getShortPercentOutstanding() {
        return shortPercentOutstanding;
    }

    /**
     * Setter for ShortPercentOutstanding.
     * @param shortPercentOutstanding Value for String
     */
    @JsonSetter("ShortPercentOutstanding")
    public void setShortPercentOutstanding(String shortPercentOutstanding) {
        this.shortPercentOutstanding = shortPercentOutstanding;
    }

    /**
     * Getter for ShortPercentFloat.
     * @return Returns the String
     */
    @JsonGetter("ShortPercentFloat")
    public String getShortPercentFloat() {
        return shortPercentFloat;
    }

    /**
     * Setter for ShortPercentFloat.
     * @param shortPercentFloat Value for String
     */
    @JsonSetter("ShortPercentFloat")
    public void setShortPercentFloat(String shortPercentFloat) {
        this.shortPercentFloat = shortPercentFloat;
    }

    /**
     * Converts this SharesStats into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SharesStats [" + "sharesOutstanding=" + sharesOutstanding + ", sharesFloat="
                + sharesFloat + ", percentInsiders=" + percentInsiders + ", percentInstitutions="
                + percentInstitutions + ", sharesShort=" + sharesShort + ", sharesShortPriorMonth="
                + sharesShortPriorMonth + ", shortRatio=" + shortRatio
                + ", shortPercentOutstanding=" + shortPercentOutstanding + ", shortPercentFloat="
                + shortPercentFloat + "]";
    }

    /**
     * Builds a new {@link SharesStats.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SharesStats.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(sharesOutstanding, sharesFloat, percentInsiders,
                percentInstitutions, sharesShort, sharesShortPriorMonth, shortRatio,
                shortPercentOutstanding, shortPercentFloat);
        return builder;
    }

    /**
     * Class to build instances of {@link SharesStats}.
     */
    public static class Builder {
        private long sharesOutstanding;
        private long sharesFloat;
        private double percentInsiders;
        private double percentInstitutions;
        private String sharesShort;
        private String sharesShortPriorMonth;
        private String shortRatio;
        private String shortPercentOutstanding;
        private String shortPercentFloat;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  sharesOutstanding  long value for sharesOutstanding.
         * @param  sharesFloat  long value for sharesFloat.
         * @param  percentInsiders  double value for percentInsiders.
         * @param  percentInstitutions  double value for percentInstitutions.
         * @param  sharesShort  String value for sharesShort.
         * @param  sharesShortPriorMonth  String value for sharesShortPriorMonth.
         * @param  shortRatio  String value for shortRatio.
         * @param  shortPercentOutstanding  String value for shortPercentOutstanding.
         * @param  shortPercentFloat  String value for shortPercentFloat.
         */
        public Builder(long sharesOutstanding, long sharesFloat, double percentInsiders,
                double percentInstitutions, String sharesShort, String sharesShortPriorMonth,
                String shortRatio, String shortPercentOutstanding, String shortPercentFloat) {
            this.sharesOutstanding = sharesOutstanding;
            this.sharesFloat = sharesFloat;
            this.percentInsiders = percentInsiders;
            this.percentInstitutions = percentInstitutions;
            this.sharesShort = sharesShort;
            this.sharesShortPriorMonth = sharesShortPriorMonth;
            this.shortRatio = shortRatio;
            this.shortPercentOutstanding = shortPercentOutstanding;
            this.shortPercentFloat = shortPercentFloat;
        }

        /**
         * Setter for sharesOutstanding.
         * @param  sharesOutstanding  long value for sharesOutstanding.
         * @return Builder
         */
        public Builder sharesOutstanding(long sharesOutstanding) {
            this.sharesOutstanding = sharesOutstanding;
            return this;
        }

        /**
         * Setter for sharesFloat.
         * @param  sharesFloat  long value for sharesFloat.
         * @return Builder
         */
        public Builder sharesFloat(long sharesFloat) {
            this.sharesFloat = sharesFloat;
            return this;
        }

        /**
         * Setter for percentInsiders.
         * @param  percentInsiders  double value for percentInsiders.
         * @return Builder
         */
        public Builder percentInsiders(double percentInsiders) {
            this.percentInsiders = percentInsiders;
            return this;
        }

        /**
         * Setter for percentInstitutions.
         * @param  percentInstitutions  double value for percentInstitutions.
         * @return Builder
         */
        public Builder percentInstitutions(double percentInstitutions) {
            this.percentInstitutions = percentInstitutions;
            return this;
        }

        /**
         * Setter for sharesShort.
         * @param  sharesShort  String value for sharesShort.
         * @return Builder
         */
        public Builder sharesShort(String sharesShort) {
            this.sharesShort = sharesShort;
            return this;
        }

        /**
         * Setter for sharesShortPriorMonth.
         * @param  sharesShortPriorMonth  String value for sharesShortPriorMonth.
         * @return Builder
         */
        public Builder sharesShortPriorMonth(String sharesShortPriorMonth) {
            this.sharesShortPriorMonth = sharesShortPriorMonth;
            return this;
        }

        /**
         * Setter for shortRatio.
         * @param  shortRatio  String value for shortRatio.
         * @return Builder
         */
        public Builder shortRatio(String shortRatio) {
            this.shortRatio = shortRatio;
            return this;
        }

        /**
         * Setter for shortPercentOutstanding.
         * @param  shortPercentOutstanding  String value for shortPercentOutstanding.
         * @return Builder
         */
        public Builder shortPercentOutstanding(String shortPercentOutstanding) {
            this.shortPercentOutstanding = shortPercentOutstanding;
            return this;
        }

        /**
         * Setter for shortPercentFloat.
         * @param  shortPercentFloat  String value for shortPercentFloat.
         * @return Builder
         */
        public Builder shortPercentFloat(String shortPercentFloat) {
            this.shortPercentFloat = shortPercentFloat;
            return this;
        }

        /**
         * Builds a new {@link SharesStats} object using the set fields.
         * @return {@link SharesStats}
         */
        public SharesStats build() {
            return new SharesStats(sharesOutstanding, sharesFloat, percentInsiders,
                    percentInstitutions, sharesShort, sharesShortPriorMonth, shortRatio,
                    shortPercentOutstanding, shortPercentFloat);
        }
    }
}
