/*
 * EODHistoricalDataFundamentalLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.eodhistoricaldata.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Technicals type.
 */
public class Technicals {
    private double beta;
    private double m52WeekHigh;
    private double m52WeekLow;
    private double m50DayMA;
    private double m200DayMA;
    private int sharesShort;
    private int sharesShortPriorMonth;
    private double shortRatio;
    private double shortPercent;

    /**
     * Default constructor.
     */
    public Technicals() {
    }

    /**
     * Initialization constructor.
     * @param  beta  double value for beta.
     * @param  m52WeekHigh  double value for m52WeekHigh.
     * @param  m52WeekLow  double value for m52WeekLow.
     * @param  m50DayMA  double value for m50DayMA.
     * @param  m200DayMA  double value for m200DayMA.
     * @param  sharesShort  int value for sharesShort.
     * @param  sharesShortPriorMonth  int value for sharesShortPriorMonth.
     * @param  shortRatio  double value for shortRatio.
     * @param  shortPercent  double value for shortPercent.
     */
    public Technicals(
            double beta,
            double m52WeekHigh,
            double m52WeekLow,
            double m50DayMA,
            double m200DayMA,
            int sharesShort,
            int sharesShortPriorMonth,
            double shortRatio,
            double shortPercent) {
        this.beta = beta;
        this.m52WeekHigh = m52WeekHigh;
        this.m52WeekLow = m52WeekLow;
        this.m50DayMA = m50DayMA;
        this.m200DayMA = m200DayMA;
        this.sharesShort = sharesShort;
        this.sharesShortPriorMonth = sharesShortPriorMonth;
        this.shortRatio = shortRatio;
        this.shortPercent = shortPercent;
    }

    /**
     * Getter for Beta.
     * @return Returns the double
     */
    @JsonGetter("Beta")
    public double getBeta() {
        return beta;
    }

    /**
     * Setter for Beta.
     * @param beta Value for double
     */
    @JsonSetter("Beta")
    public void setBeta(double beta) {
        this.beta = beta;
    }

    /**
     * Getter for M52WeekHigh.
     * @return Returns the double
     */
    @JsonGetter("52WeekHigh")
    public double getM52WeekHigh() {
        return m52WeekHigh;
    }

    /**
     * Setter for M52WeekHigh.
     * @param m52WeekHigh Value for double
     */
    @JsonSetter("52WeekHigh")
    public void setM52WeekHigh(double m52WeekHigh) {
        this.m52WeekHigh = m52WeekHigh;
    }

    /**
     * Getter for M52WeekLow.
     * @return Returns the double
     */
    @JsonGetter("52WeekLow")
    public double getM52WeekLow() {
        return m52WeekLow;
    }

    /**
     * Setter for M52WeekLow.
     * @param m52WeekLow Value for double
     */
    @JsonSetter("52WeekLow")
    public void setM52WeekLow(double m52WeekLow) {
        this.m52WeekLow = m52WeekLow;
    }

    /**
     * Getter for M50DayMA.
     * @return Returns the double
     */
    @JsonGetter("50DayMA")
    public double getM50DayMA() {
        return m50DayMA;
    }

    /**
     * Setter for M50DayMA.
     * @param m50DayMA Value for double
     */
    @JsonSetter("50DayMA")
    public void setM50DayMA(double m50DayMA) {
        this.m50DayMA = m50DayMA;
    }

    /**
     * Getter for M200DayMA.
     * @return Returns the double
     */
    @JsonGetter("200DayMA")
    public double getM200DayMA() {
        return m200DayMA;
    }

    /**
     * Setter for M200DayMA.
     * @param m200DayMA Value for double
     */
    @JsonSetter("200DayMA")
    public void setM200DayMA(double m200DayMA) {
        this.m200DayMA = m200DayMA;
    }

    /**
     * Getter for SharesShort.
     * @return Returns the int
     */
    @JsonGetter("SharesShort")
    public int getSharesShort() {
        return sharesShort;
    }

    /**
     * Setter for SharesShort.
     * @param sharesShort Value for int
     */
    @JsonSetter("SharesShort")
    public void setSharesShort(int sharesShort) {
        this.sharesShort = sharesShort;
    }

    /**
     * Getter for SharesShortPriorMonth.
     * @return Returns the int
     */
    @JsonGetter("SharesShortPriorMonth")
    public int getSharesShortPriorMonth() {
        return sharesShortPriorMonth;
    }

    /**
     * Setter for SharesShortPriorMonth.
     * @param sharesShortPriorMonth Value for int
     */
    @JsonSetter("SharesShortPriorMonth")
    public void setSharesShortPriorMonth(int sharesShortPriorMonth) {
        this.sharesShortPriorMonth = sharesShortPriorMonth;
    }

    /**
     * Getter for ShortRatio.
     * @return Returns the double
     */
    @JsonGetter("ShortRatio")
    public double getShortRatio() {
        return shortRatio;
    }

    /**
     * Setter for ShortRatio.
     * @param shortRatio Value for double
     */
    @JsonSetter("ShortRatio")
    public void setShortRatio(double shortRatio) {
        this.shortRatio = shortRatio;
    }

    /**
     * Getter for ShortPercent.
     * @return Returns the double
     */
    @JsonGetter("ShortPercent")
    public double getShortPercent() {
        return shortPercent;
    }

    /**
     * Setter for ShortPercent.
     * @param shortPercent Value for double
     */
    @JsonSetter("ShortPercent")
    public void setShortPercent(double shortPercent) {
        this.shortPercent = shortPercent;
    }

    /**
     * Converts this Technicals into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Technicals [" + "beta=" + beta + ", m52WeekHigh=" + m52WeekHigh + ", m52WeekLow="
                + m52WeekLow + ", m50DayMA=" + m50DayMA + ", m200DayMA=" + m200DayMA
                + ", sharesShort=" + sharesShort + ", sharesShortPriorMonth="
                + sharesShortPriorMonth + ", shortRatio=" + shortRatio + ", shortPercent="
                + shortPercent + "]";
    }

    /**
     * Builds a new {@link Technicals.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Technicals.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(beta, m52WeekHigh, m52WeekLow, m50DayMA, m200DayMA,
                sharesShort, sharesShortPriorMonth, shortRatio, shortPercent);
        return builder;
    }

    /**
     * Class to build instances of {@link Technicals}.
     */
    public static class Builder {
        private double beta;
        private double m52WeekHigh;
        private double m52WeekLow;
        private double m50DayMA;
        private double m200DayMA;
        private int sharesShort;
        private int sharesShortPriorMonth;
        private double shortRatio;
        private double shortPercent;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  beta  double value for beta.
         * @param  m52WeekHigh  double value for m52WeekHigh.
         * @param  m52WeekLow  double value for m52WeekLow.
         * @param  m50DayMA  double value for m50DayMA.
         * @param  m200DayMA  double value for m200DayMA.
         * @param  sharesShort  int value for sharesShort.
         * @param  sharesShortPriorMonth  int value for sharesShortPriorMonth.
         * @param  shortRatio  double value for shortRatio.
         * @param  shortPercent  double value for shortPercent.
         */
        public Builder(double beta, double m52WeekHigh, double m52WeekLow, double m50DayMA,
                double m200DayMA, int sharesShort, int sharesShortPriorMonth, double shortRatio,
                double shortPercent) {
            this.beta = beta;
            this.m52WeekHigh = m52WeekHigh;
            this.m52WeekLow = m52WeekLow;
            this.m50DayMA = m50DayMA;
            this.m200DayMA = m200DayMA;
            this.sharesShort = sharesShort;
            this.sharesShortPriorMonth = sharesShortPriorMonth;
            this.shortRatio = shortRatio;
            this.shortPercent = shortPercent;
        }

        /**
         * Setter for beta.
         * @param  beta  double value for beta.
         * @return Builder
         */
        public Builder beta(double beta) {
            this.beta = beta;
            return this;
        }

        /**
         * Setter for m52WeekHigh.
         * @param  m52WeekHigh  double value for m52WeekHigh.
         * @return Builder
         */
        public Builder m52WeekHigh(double m52WeekHigh) {
            this.m52WeekHigh = m52WeekHigh;
            return this;
        }

        /**
         * Setter for m52WeekLow.
         * @param  m52WeekLow  double value for m52WeekLow.
         * @return Builder
         */
        public Builder m52WeekLow(double m52WeekLow) {
            this.m52WeekLow = m52WeekLow;
            return this;
        }

        /**
         * Setter for m50DayMA.
         * @param  m50DayMA  double value for m50DayMA.
         * @return Builder
         */
        public Builder m50DayMA(double m50DayMA) {
            this.m50DayMA = m50DayMA;
            return this;
        }

        /**
         * Setter for m200DayMA.
         * @param  m200DayMA  double value for m200DayMA.
         * @return Builder
         */
        public Builder m200DayMA(double m200DayMA) {
            this.m200DayMA = m200DayMA;
            return this;
        }

        /**
         * Setter for sharesShort.
         * @param  sharesShort  int value for sharesShort.
         * @return Builder
         */
        public Builder sharesShort(int sharesShort) {
            this.sharesShort = sharesShort;
            return this;
        }

        /**
         * Setter for sharesShortPriorMonth.
         * @param  sharesShortPriorMonth  int value for sharesShortPriorMonth.
         * @return Builder
         */
        public Builder sharesShortPriorMonth(int sharesShortPriorMonth) {
            this.sharesShortPriorMonth = sharesShortPriorMonth;
            return this;
        }

        /**
         * Setter for shortRatio.
         * @param  shortRatio  double value for shortRatio.
         * @return Builder
         */
        public Builder shortRatio(double shortRatio) {
            this.shortRatio = shortRatio;
            return this;
        }

        /**
         * Setter for shortPercent.
         * @param  shortPercent  double value for shortPercent.
         * @return Builder
         */
        public Builder shortPercent(double shortPercent) {
            this.shortPercent = shortPercent;
            return this;
        }

        /**
         * Builds a new {@link Technicals} object using the set fields.
         * @return {@link Technicals}
         */
        public Technicals build() {
            return new Technicals(beta, m52WeekHigh, m52WeekLow, m50DayMA, m200DayMA, sharesShort,
                    sharesShortPriorMonth, shortRatio, shortPercent);
        }
    }
}
