/*
 * EODHistoricalDataFundamentalLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.eodhistoricaldata.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Valuation type.
 */
public class Valuation {
    private double trailingPE;
    private double forwardPE;
    private double priceSalesTTM;
    private double priceBookMRQ;
    private long enterpriseValue;
    private double enterpriseValueRevenue;
    private double enterpriseValueEbitda;

    /**
     * Default constructor.
     */
    public Valuation() {
    }

    /**
     * Initialization constructor.
     * @param  trailingPE  double value for trailingPE.
     * @param  forwardPE  double value for forwardPE.
     * @param  priceSalesTTM  double value for priceSalesTTM.
     * @param  priceBookMRQ  double value for priceBookMRQ.
     * @param  enterpriseValue  long value for enterpriseValue.
     * @param  enterpriseValueRevenue  double value for enterpriseValueRevenue.
     * @param  enterpriseValueEbitda  double value for enterpriseValueEbitda.
     */
    public Valuation(
            double trailingPE,
            double forwardPE,
            double priceSalesTTM,
            double priceBookMRQ,
            long enterpriseValue,
            double enterpriseValueRevenue,
            double enterpriseValueEbitda) {
        this.trailingPE = trailingPE;
        this.forwardPE = forwardPE;
        this.priceSalesTTM = priceSalesTTM;
        this.priceBookMRQ = priceBookMRQ;
        this.enterpriseValue = enterpriseValue;
        this.enterpriseValueRevenue = enterpriseValueRevenue;
        this.enterpriseValueEbitda = enterpriseValueEbitda;
    }

    /**
     * Getter for TrailingPE.
     * @return Returns the double
     */
    @JsonGetter("TrailingPE")
    public double getTrailingPE() {
        return trailingPE;
    }

    /**
     * Setter for TrailingPE.
     * @param trailingPE Value for double
     */
    @JsonSetter("TrailingPE")
    public void setTrailingPE(double trailingPE) {
        this.trailingPE = trailingPE;
    }

    /**
     * Getter for ForwardPE.
     * @return Returns the double
     */
    @JsonGetter("ForwardPE")
    public double getForwardPE() {
        return forwardPE;
    }

    /**
     * Setter for ForwardPE.
     * @param forwardPE Value for double
     */
    @JsonSetter("ForwardPE")
    public void setForwardPE(double forwardPE) {
        this.forwardPE = forwardPE;
    }

    /**
     * Getter for PriceSalesTTM.
     * @return Returns the double
     */
    @JsonGetter("PriceSalesTTM")
    public double getPriceSalesTTM() {
        return priceSalesTTM;
    }

    /**
     * Setter for PriceSalesTTM.
     * @param priceSalesTTM Value for double
     */
    @JsonSetter("PriceSalesTTM")
    public void setPriceSalesTTM(double priceSalesTTM) {
        this.priceSalesTTM = priceSalesTTM;
    }

    /**
     * Getter for PriceBookMRQ.
     * @return Returns the double
     */
    @JsonGetter("PriceBookMRQ")
    public double getPriceBookMRQ() {
        return priceBookMRQ;
    }

    /**
     * Setter for PriceBookMRQ.
     * @param priceBookMRQ Value for double
     */
    @JsonSetter("PriceBookMRQ")
    public void setPriceBookMRQ(double priceBookMRQ) {
        this.priceBookMRQ = priceBookMRQ;
    }

    /**
     * Getter for EnterpriseValue.
     * @return Returns the long
     */
    @JsonGetter("EnterpriseValue")
    public long getEnterpriseValue() {
        return enterpriseValue;
    }

    /**
     * Setter for EnterpriseValue.
     * @param enterpriseValue Value for long
     */
    @JsonSetter("EnterpriseValue")
    public void setEnterpriseValue(long enterpriseValue) {
        this.enterpriseValue = enterpriseValue;
    }

    /**
     * Getter for EnterpriseValueRevenue.
     * @return Returns the double
     */
    @JsonGetter("EnterpriseValueRevenue")
    public double getEnterpriseValueRevenue() {
        return enterpriseValueRevenue;
    }

    /**
     * Setter for EnterpriseValueRevenue.
     * @param enterpriseValueRevenue Value for double
     */
    @JsonSetter("EnterpriseValueRevenue")
    public void setEnterpriseValueRevenue(double enterpriseValueRevenue) {
        this.enterpriseValueRevenue = enterpriseValueRevenue;
    }

    /**
     * Getter for EnterpriseValueEbitda.
     * @return Returns the double
     */
    @JsonGetter("EnterpriseValueEbitda")
    public double getEnterpriseValueEbitda() {
        return enterpriseValueEbitda;
    }

    /**
     * Setter for EnterpriseValueEbitda.
     * @param enterpriseValueEbitda Value for double
     */
    @JsonSetter("EnterpriseValueEbitda")
    public void setEnterpriseValueEbitda(double enterpriseValueEbitda) {
        this.enterpriseValueEbitda = enterpriseValueEbitda;
    }

    /**
     * Converts this Valuation into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Valuation [" + "trailingPE=" + trailingPE + ", forwardPE=" + forwardPE
                + ", priceSalesTTM=" + priceSalesTTM + ", priceBookMRQ=" + priceBookMRQ
                + ", enterpriseValue=" + enterpriseValue + ", enterpriseValueRevenue="
                + enterpriseValueRevenue + ", enterpriseValueEbitda=" + enterpriseValueEbitda + "]";
    }

    /**
     * Builds a new {@link Valuation.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Valuation.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(trailingPE, forwardPE, priceSalesTTM, priceBookMRQ,
                enterpriseValue, enterpriseValueRevenue, enterpriseValueEbitda);
        return builder;
    }

    /**
     * Class to build instances of {@link Valuation}.
     */
    public static class Builder {
        private double trailingPE;
        private double forwardPE;
        private double priceSalesTTM;
        private double priceBookMRQ;
        private long enterpriseValue;
        private double enterpriseValueRevenue;
        private double enterpriseValueEbitda;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  trailingPE  double value for trailingPE.
         * @param  forwardPE  double value for forwardPE.
         * @param  priceSalesTTM  double value for priceSalesTTM.
         * @param  priceBookMRQ  double value for priceBookMRQ.
         * @param  enterpriseValue  long value for enterpriseValue.
         * @param  enterpriseValueRevenue  double value for enterpriseValueRevenue.
         * @param  enterpriseValueEbitda  double value for enterpriseValueEbitda.
         */
        public Builder(double trailingPE, double forwardPE, double priceSalesTTM,
                double priceBookMRQ, long enterpriseValue, double enterpriseValueRevenue,
                double enterpriseValueEbitda) {
            this.trailingPE = trailingPE;
            this.forwardPE = forwardPE;
            this.priceSalesTTM = priceSalesTTM;
            this.priceBookMRQ = priceBookMRQ;
            this.enterpriseValue = enterpriseValue;
            this.enterpriseValueRevenue = enterpriseValueRevenue;
            this.enterpriseValueEbitda = enterpriseValueEbitda;
        }

        /**
         * Setter for trailingPE.
         * @param  trailingPE  double value for trailingPE.
         * @return Builder
         */
        public Builder trailingPE(double trailingPE) {
            this.trailingPE = trailingPE;
            return this;
        }

        /**
         * Setter for forwardPE.
         * @param  forwardPE  double value for forwardPE.
         * @return Builder
         */
        public Builder forwardPE(double forwardPE) {
            this.forwardPE = forwardPE;
            return this;
        }

        /**
         * Setter for priceSalesTTM.
         * @param  priceSalesTTM  double value for priceSalesTTM.
         * @return Builder
         */
        public Builder priceSalesTTM(double priceSalesTTM) {
            this.priceSalesTTM = priceSalesTTM;
            return this;
        }

        /**
         * Setter for priceBookMRQ.
         * @param  priceBookMRQ  double value for priceBookMRQ.
         * @return Builder
         */
        public Builder priceBookMRQ(double priceBookMRQ) {
            this.priceBookMRQ = priceBookMRQ;
            return this;
        }

        /**
         * Setter for enterpriseValue.
         * @param  enterpriseValue  long value for enterpriseValue.
         * @return Builder
         */
        public Builder enterpriseValue(long enterpriseValue) {
            this.enterpriseValue = enterpriseValue;
            return this;
        }

        /**
         * Setter for enterpriseValueRevenue.
         * @param  enterpriseValueRevenue  double value for enterpriseValueRevenue.
         * @return Builder
         */
        public Builder enterpriseValueRevenue(double enterpriseValueRevenue) {
            this.enterpriseValueRevenue = enterpriseValueRevenue;
            return this;
        }

        /**
         * Setter for enterpriseValueEbitda.
         * @param  enterpriseValueEbitda  double value for enterpriseValueEbitda.
         * @return Builder
         */
        public Builder enterpriseValueEbitda(double enterpriseValueEbitda) {
            this.enterpriseValueEbitda = enterpriseValueEbitda;
            return this;
        }

        /**
         * Builds a new {@link Valuation} object using the set fields.
         * @return {@link Valuation}
         */
        public Valuation build() {
            return new Valuation(trailingPE, forwardPE, priceSalesTTM, priceBookMRQ,
                    enterpriseValue, enterpriseValueRevenue, enterpriseValueEbitda);
        }
    }
}
